"""Orchestrate Mistral projection and the canonical Rust SDK generator."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import json
from pathlib import Path
import subprocess
from typing import Any

from rust_types import parse_type
from sdk_autoproject import expand_manifest
from sdk_contracts import coverage_inventory, public_surface


GENERATED = "// @generated by tooling/pipeline/compile_sdk.py; do not edit by hand.\n"


class GenerationError(RuntimeError):
    """Consumer pipeline generation failure."""


@dataclass(frozen=True)
class BindingField:
    name: str
    type: str


@dataclass(frozen=True)
class BindingVariant:
    name: str
    payload: str | None
    wire_name: str | None


class CanonicalBindings:
    """Read-only consumer view over canonical Rust Bindings v3.

    The openapi-to-rust compatibility adapter owns normalization. This view only
    exposes the small access API used by Mistral's taxonomy projection.
    """

    def __init__(self, value: dict[str, Any]) -> None:
        if value.get("schema_version") != 3:
            raise GenerationError(
                f"canonical Bindings v3 required, got {value.get('schema_version')!r}"
            )
        self._value = value
        self.structs = value.get("structs", {})
        self.aliases = {
            name: parse_type(type_name)
            for name, type_name in value.get("aliases", {}).items()
        }
        self.enums = {
            name: [
                BindingVariant(
                    name=variant["name"],
                    payload=variant.get("payload"),
                    wire_name=variant.get("wire_name"),
                )
                for variant in variants
            ]
            for name, variants in value.get("enums", {}).items()
        }
        self.symbol_paths = value.get("symbol_paths", {})
        self.operations = value.get("operations", {})

    @classmethod
    def load(cls, path: Path) -> "CanonicalBindings":
        value = json.loads(path.read_text())
        if not isinstance(value, dict):
            raise GenerationError("canonical Bindings must be a JSON object")
        return cls(value)

    def fields(self, name: str) -> list[BindingField]:
        return [
            BindingField(name=field["name"], type=field["type"])
            for field in self.structs.get(name, [])
        ]


class OpenApi:
    """Minimal Mistral projection view over the fixed overlaid OpenAPI."""

    METHODS = {"get", "put", "post", "delete", "options", "head", "patch", "trace", "query"}

    def __init__(self, document: dict[str, Any]) -> None:
        self.document = document
        self.schemas = document.get("components", {}).get("schemas", {})
        self.operations: dict[str, dict[str, Any]] = {}
        for path, path_item in document.get("paths", {}).items():
            if not isinstance(path_item, dict):
                continue
            for method, operation in path_item.items():
                if method.lower() not in self.METHODS or not isinstance(operation, dict):
                    continue
                operation_id = operation.get("operationId")
                if not isinstance(operation_id, str) or not operation_id:
                    continue
                normalized = dict(operation)
                normalized["x-sdk-method"] = method.lower()
                normalized["x-sdk-path"] = path
                self.operations[operation_id] = normalized

    @classmethod
    def load(cls, path: Path) -> "OpenApi":
        value = json.loads(path.read_text())
        if not isinstance(value, dict):
            raise GenerationError("OpenAPI must be a JSON object")
        return cls(value)

    def request_schema(self, operation_id: str) -> str | None:
        operation = self.operations[operation_id]
        content = operation.get("requestBody", {}).get("content", {})
        if set(content) != {"application/json"}:
            return None
        schema = content["application/json"].get("schema", {})
        reference = schema.get("$ref")
        if not isinstance(reference, str):
            return None
        return reference.rsplit("/", 1)[-1]


def run(*args: object, cwd: Path | None = None) -> None:
    try:
        subprocess.run(
            [str(arg) for arg in args],
            cwd=cwd,
            check=True,
        )
    except subprocess.CalledProcessError as error:
        raise GenerationError(
            f"command failed ({error.returncode}): {' '.join(map(str, args))}"
        ) from error


def generated_sources(target: Path) -> dict[str, str]:
    return {
        path.relative_to(target).as_posix(): path.read_text()
        for path in sorted(target.rglob("*.rs"))
    }


def write_json(path: Path, value: Any) -> None:
    path.write_text(json.dumps(value, indent=2) + "\n")


def generate(
    raw: Path,
    target: Path,
    manifest_path: Path,
    *,
    bindings_path: Path,
    sdk_generator: Path,
    openapi_path: Path | None = None,
    taxonomy_path: Path | None = None,
) -> None:
    if openapi_path is None:
        candidate = manifest_path.parent.parent / "sources" / "openapi" / "openapi.yaml"
        if not candidate.exists():
            raise GenerationError("--openapi is required outside the repository layout")
        openapi_path = candidate
    if taxonomy_path is None:
        candidate = manifest_path.parent.parent / "sources" / "taxonomy.json"
        if candidate.exists():
            taxonomy_path = candidate

    manifest = json.loads(manifest_path.read_text())
    openapi = OpenApi.load(openapi_path)
    bindings = CanonicalBindings.load(bindings_path)
    projection_report = None
    if taxonomy_path is not None:
        taxonomy = json.loads(taxonomy_path.read_text())
        raw_coverage = json.loads((raw / "coverage.json").read_text())
        manifest, projection_report = expand_manifest(
            openapi, manifest, taxonomy, raw_coverage, bindings
        )

    work = target.parent
    definition_path = work / "sdk-definition.json"
    runtime_path = work / "sdk-runtime.json"
    inventory_path = work / "sdk-inventory.json"
    write_json(definition_path, manifest)
    write_json(
        runtime_path,
        {
            "error_type": "SdkError",
            "error_module": "error",
            "error_exports": ["ApiError", "SdkError", "TransportError", "TransportErrorKind"],
            "sse_module": "crate::streaming",
            "sse_function": "json_events",
            "generated_marker": GENERATED,
        },
    )

    target.mkdir(parents=True, exist_ok=True)
    run(
        sdk_generator,
        "generate",
        "--openapi",
        openapi_path,
        "--bindings",
        bindings_path,
        "--definition",
        definition_path,
        "--runtime",
        runtime_path,
        "--output",
        target,
        "--inventory",
        inventory_path,
    )

    files = generated_sources(target)
    try:
        surface = public_surface(files)
    except ValueError as error:
        raise GenerationError(str(error)) from error
    write_json(target / "api-surface.json", surface)

    coverage = {
        "schema_version": 2,
        "inventory": coverage_inventory(openapi, bindings, manifest),
        "resources": {
            resource_name: {
                "operations": [
                    operation["operation_id"]
                    for operation in resource.get("operations", {}).values()
                ]
            }
            for resource_name, resource in manifest.get("resources", {}).items()
        },
        "models": {
            model_name: {
                "raw": model.get("raw", model_name),
                "fields": sorted(
                    field.name
                    for field in bindings.fields(model.get("raw", model_name))
                )
                if model.get("raw", model_name) in bindings.structs
                else [],
            }
            for model_name, model in manifest.get("models", {}).items()
        },
    }
    if projection_report is not None:
        coverage["automatic_projection"] = projection_report
    write_json(target / "coverage.json", coverage)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("raw", type=Path)
    parser.add_argument("target", type=Path)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--bindings", type=Path, required=True)
    parser.add_argument("--sdk-generator", type=Path, required=True)
    parser.add_argument("--openapi", type=Path)
    parser.add_argument("--taxonomy", type=Path)
    args = parser.parse_args()
    generate(
        args.raw,
        args.target,
        args.manifest,
        bindings_path=args.bindings,
        sdk_generator=args.sdk_generator,
        openapi_path=args.openapi,
        taxonomy_path=args.taxonomy,
    )


if __name__ == "__main__":
    main()
