"""Orchestrate projection, generic compilation, and repository audit outputs."""

import argparse
import json
from pathlib import Path

from openapi_to_rust_bindings import read_bindings
from rust_sdk_compiler import GenerationError, OpenApi, Policy, Runtime, compile
from sdk_autoproject import expand_manifest
from sdk_contracts import coverage_inventory, public_surface


GENERATED = "// @generated by tooling/pipeline/compile_sdk.py; do not edit by hand.\n"
RUNTIME = Runtime(generated_marker=GENERATED)


def generate(raw: Path, target: Path, manifest_path: Path, openapi_path: Path | None = None,
             taxonomy_path: Path | None = None) -> None:
    if openapi_path is None:
        candidate = manifest_path.parent.parent / "sources" / "openapi" / "openapi.yaml"
        if not candidate.exists():
            raise GenerationError("--openapi is required outside the repository layout")
        openapi_path = candidate
    if taxonomy_path is None:
        candidate = manifest_path.parent.parent / "sources" / "taxonomy.json"
        if candidate.exists():
            taxonomy_path = candidate
    manifest = json.loads(manifest_path.read_text())
    openapi = OpenApi.load(openapi_path)
    bindings = read_bindings(raw)
    projection_report = None
    if taxonomy_path is not None:
        taxonomy = json.loads(taxonomy_path.read_text())
        raw_coverage = json.loads((raw / "coverage.json").read_text())
        manifest, projection_report = expand_manifest(
            openapi, manifest, taxonomy, raw_coverage, bindings
        )
    compilation = compile(
        openapi,
        bindings,
        Policy.from_dict(manifest),
        runtime=RUNTIME,
    )
    ir = compilation.ir
    files = dict(compilation.files)
    target.mkdir(parents=True, exist_ok=True)

    try:
        surface = public_surface(files)
    except ValueError as error:
        raise GenerationError(str(error)) from error
    for filename, source in files.items():
        (target / filename).write_text(source)
    (target / "api-surface.json").write_text(json.dumps(surface, indent=2) + "\n")
    coverage = {
        "schema_version": 2,
        "inventory": coverage_inventory(openapi, bindings, ir),
        "resources": {resource.module: {"operations": [operation.operation_id for operation in resource.operations]}
                      for resource in ir.resources},
        "models": {model.name: {"raw": model.raw, "fields": sorted(field.name for field in bindings.fields(model.raw)) if model.raw in bindings.structs else []}
                   for model in ir.models},
    }
    if projection_report is not None:
        coverage["automatic_projection"] = projection_report
    (target / "coverage.json").write_text(json.dumps(coverage, indent=2) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("raw", type=Path)
    parser.add_argument("target", type=Path)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--openapi", type=Path)
    parser.add_argument("--taxonomy", type=Path)
    args = parser.parse_args()
    generate(args.raw, args.target, args.manifest, args.openapi, args.taxonomy)


if __name__ == "__main__":
    main()
