overlay: 1.1.0
info:
  title: Mistral published OpenAPI corrections
  version: "1"
actions:
  - target: "$.components.schemas.ChatCompletionResponse.allOf[1].required[?@ == 'data']"
    remove: true
  - target: "$.components.schemas.SharingDelete.required[?@ == 'level']"
    remove: true
  - target: "$.components.schemas.WorkflowListResponse.required[?@ == 'beta.workflows']"
    update: workflows
