"""Repository compatibility shim over the pinned compiler packages."""

from openapi_to_rust_bindings import read_bindings
from rust_sdk_compiler import GenerationError, OpenApi, Policy, Runtime, compile, lower


GENERATED = "// @generated by codegen/sdk_facade.py; do not edit by hand.\n"
OpenApiIndex = OpenApi


def load_raw_ir(raw):
    return read_bindings(raw)


def compile_ir(openapi, bindings, manifest):
    return lower(openapi, bindings, Policy.from_dict(manifest))


def compile_facade(openapi, bindings, manifest):
    result = compile(
        openapi,
        bindings,
        Policy.from_dict(manifest),
        runtime=Runtime(generated_marker=GENERATED),
    )
    return result.ir, dict(result.files)
