"""Generate the idiomatic SDK facade from generated raw Rust bindings.

The semantic manifest controls stable public naming. Request setters and raw
operation contracts are derived from openapi-to-rust output, so regeneration
tracks compatible additions and fails closed on unsupported structural drift.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re


GENERATED = "// @generated by codegen/sdk_facade.py; do not edit by hand.\n"


def _balanced_body(source: str, marker: str) -> str:
    start = source.find(marker)
    if start < 0:
        raise ValueError(f"raw Rust item not found: {marker}")
    opening = source.find("{", start + len(marker))
    if opening < 0:
        raise ValueError(f"raw Rust item has no body: {marker}")
    depth = 0
    for index in range(opening, len(source)):
        char = source[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return source[opening + 1:index]
    raise ValueError(f"unterminated raw Rust item: {marker}")


def struct_fields(source: str, name: str) -> dict[str, str]:
    body = _balanced_body(source, f"pub struct {name}")
    fields = {}
    field_pattern = re.compile(r"(?m)^\s*pub (r#)?([A-Za-z0-9_]+):\s*")
    pairs = {">": "<", ")": "(", "]": "[", "}": "{"}
    for match in field_pattern.finditer(body):
        stack = []
        end = None
        for index in range(match.end(), len(body)):
            char = body[index]
            if char in "<([{":
                stack.append(char)
            elif char in pairs:
                if not stack or stack.pop() != pairs[char]:
                    raise ValueError(f"unbalanced field type in raw type {name}")
            elif char == "," and not stack:
                end = index
                break
        if end is None:
            raise ValueError(f"unterminated public field in raw type {name}")
        fields[(match.group(1) or "") + match.group(2)] = body[match.end():end].strip()
    if not fields:
        raise ValueError(f"no public fields parsed for raw type {name}")
    return fields


def require_type(source: str, name: str) -> None:
    if not re.search(rf"(?m)^pub (?:struct|enum) {re.escape(name)}\b", source):
        raise ValueError(f"raw Rust type not found: {name}")


def require_operation(source: str, name: str, request_type: str) -> None:
    pattern = rf"pub async fn {re.escape(name)}\s*\(\s*&self,\s*request: {re.escape(request_type)},"
    if not re.search(pattern, source):
        raise ValueError(
            f"raw operation {name} no longer accepts {request_type}; semantic review required"
        )


def _option_inner(rust_type: str) -> tuple[str, bool] | None:
    if not rust_type.startswith("Option<") or not rust_type.endswith(">"):
        return None
    inner = rust_type[7:-1]
    if inner.startswith("Option<") and inner.endswith(">"):
        return inner[7:-1], True
    return inner, False


def _argument(name: str, rust_type: str) -> tuple[str, str]:
    if rust_type == "String":
        return f"{name}: impl Into<String>", f"{name}.into()"
    return f"{name}: {rust_type}", name


def request_setters(fields: dict[str, str], reserved: set[str]) -> str:
    methods = []
    for raw_name, rust_type in fields.items():
        name = raw_name.removeprefix("r#")
        if name in reserved:
            continue
        optional = _option_inner(rust_type)
        if optional is None:
            raise ValueError(
                f"new required request field {raw_name}: {rust_type}; semantic review required"
            )
        inner, nullable = optional
        argument, value = _argument(name, inner)
        wrapped = f"Some(Some({value}))" if nullable else f"Some({value})"
        signature = f"    pub fn {name}(mut self, {argument}) -> Self {{"
        if len(signature) > 100:
            signature = (
                f"    pub fn {name}(\n"
                f"        mut self,\n"
                f"        {argument},\n"
                "    ) -> Self {"
            )
        methods.append(f"""
    #[must_use]
{signature}
        self.raw.{raw_name} = {wrapped};
        self
    }}
""")
        if nullable:
            methods.append(f"""
    #[must_use]
    pub fn {name}_null(mut self) -> Self {{
        self.raw.{raw_name} = Some(None);
        self
    }}
""")
    return "".join(methods)


def generate_chat(config: dict, fields: dict[str, str]) -> str:
    setters = request_setters(fields, set(config["reserved_request_fields"]))
    return GENERATED + f'''use std::pin::Pin;

use futures_util::{{Stream, StreamExt}};

use super::SdkError;
use crate::generated::client::HttpClient;
use crate::generated::types::*;
use crate::streaming;

/// A chat message with textual content.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum Message {{
    System(String),
    User(String),
    Assistant(String),
}}

impl Message {{
    pub fn system(content: impl Into<String>) -> Self {{
        Self::System(content.into())
    }}
    pub fn user(content: impl Into<String>) -> Self {{
        Self::User(content.into())
    }}
    pub fn assistant(content: impl Into<String>) -> Self {{
        Self::Assistant(content.into())
    }}
}}

impl From<Message> for ChatCompletionRequestMessagesItemUnion {{
    fn from(message: Message) -> Self {{
        match message {{
            Message::System(content) => Self::SystemMessage(SystemMessage {{
                content: SystemMessageContent::String(content),
                role: None,
            }}),
            Message::User(content) => Self::UserMessage(UserMessage {{
                content: Some(UserMessageContent::String(content)),
                role: None,
            }}),
            Message::Assistant(content) => Self::AssistantMessage(AssistantMessage {{
                content: Some(Some(AssistantMessageContent::String(content))),
                prefix: None,
                role: None,
                tool_calls: None,
            }}),
        }}
    }}
}}

/// A generated ergonomic wrapper over [`{config["request_type"]}`].
#[derive(Debug, Clone)]
pub struct {config["request_wrapper"]} {{
    raw: {config["request_type"]},
}}

impl {config["request_wrapper"]} {{
    pub fn new(model: impl Into<String>, messages: impl IntoIterator<Item = Message>) -> Self {{
        Self {{
            raw: {config["request_type"]}::new(
                messages.into_iter().map(Into::into).collect(),
                model.into(),
            ),
        }}
    }}

    pub fn from_raw(raw: {config["request_type"]}) -> Self {{
        Self {{ raw }}
    }}
{setters}
    pub fn as_raw(&self) -> &{config["request_type"]} {{
        &self.raw
    }}
    pub fn into_raw(self) -> {config["request_type"]} {{
        self.raw
    }}

    fn into_raw_with_stream(mut self, stream: bool) -> {config["request_type"]} {{
        self.raw.stream = Some(stream);
        self.raw
    }}
}}

/// A stable facade over the generated chat completion response.
#[derive(Debug, Clone)]
pub struct {config["response_wrapper"]} {{
    raw: {config["response_type"]},
}}

impl {config["response_wrapper"]} {{
    pub fn text(&self) -> Option<&str> {{
        let content = self
            .raw
            .choices
            .first()?
            .message
            .content
            .as_ref()?
            .as_ref()?;
        match content {{
            AssistantMessageContent::String(text) => Some(text),
            AssistantMessageContent::ContentChunkArray(_) => None,
        }}
    }}
    pub fn raw(&self) -> &{config["response_type"]} {{
        &self.raw
    }}
    pub fn into_raw(self) -> {config["response_type"]} {{
        self.raw
    }}
}}

impl From<{config["response_type"]}> for {config["response_wrapper"]} {{
    fn from(raw: {config["response_type"]}) -> Self {{
        Self {{ raw }}
    }}
}}

/// A stable facade over one generated streaming chunk.
#[derive(Debug, Clone)]
pub struct {config["stream_item_wrapper"]} {{
    raw: {config["stream_item_type"]},
}}

impl {config["stream_item_wrapper"]} {{
    pub fn text(&self) -> Option<&str> {{
        let content = self.raw.choices.first()?.delta.content.as_ref()?.as_ref()?;
        match content {{
            DeltaMessageContent::String(text) => Some(text),
            DeltaMessageContent::ContentChunkArrayInline(_) => None,
        }}
    }}
    pub fn raw(&self) -> &{config["stream_item_type"]} {{
        &self.raw
    }}
    pub fn into_raw(self) -> {config["stream_item_type"]} {{
        self.raw
    }}
}}

impl From<{config["stream_item_type"]}> for {config["stream_item_wrapper"]} {{
    fn from(raw: {config["stream_item_type"]}) -> Self {{
        Self {{ raw }}
    }}
}}

pub type {config["stream_type"]} =
    Pin<Box<dyn Stream<Item = Result<{config["stream_item_wrapper"]}, SdkError>> + Send + 'static>>;

#[derive(Clone, Copy)]
pub struct {config["resource_type"]}<'a> {{
    raw: &'a HttpClient,
}}

impl<'a> {config["resource_type"]}<'a> {{
    pub(crate) fn new(raw: &'a HttpClient) -> Self {{
        Self {{ raw }}
    }}

    pub async fn complete(&self, request: {config["request_wrapper"]}) -> Result<{config["response_wrapper"]}, SdkError> {{
        self.raw
            .{config["complete_operation"]}(request.into_raw_with_stream(false))
            .await
            .map(Into::into)
            .map_err(Into::into)
    }}

    pub async fn stream(&self, request: {config["request_wrapper"]}) -> Result<{config["stream_type"]}, SdkError> {{
        let bytes = self
            .raw
            .{config["stream_operation"]}(request.into_raw_with_stream(true))
            .await
            .map_err(SdkError::from)?;
        let events = streaming::json_events::<_, _, {config["stream_item_type"]}>(bytes)
            .map(|event| event.map(|event| event.data.into()).map_err(Into::into));
        Ok(Box::pin(events))
    }}
}}
'''


def generate_ocr(config: dict, fields: dict[str, str]) -> str:
    setters = request_setters(fields, set(config["reserved_request_fields"]))
    return GENERATED + f'''use super::SdkError;
use crate::generated::client::HttpClient;
use crate::generated::types::*;

#[derive(Debug)]
pub struct {config["response_wrapper"]} {{
    raw: {config["response_type"]},
}}

impl {config["response_wrapper"]} {{
    pub fn model(&self) -> &str {{
        &self.raw.model
    }}
    pub fn pages(&self) -> impl ExactSizeIterator<Item = OcrPage<'_>> {{
        self.raw.pages.iter().map(OcrPage::new)
    }}
    pub fn raw(&self) -> &{config["response_type"]} {{
        &self.raw
    }}
    pub fn into_raw(self) -> {config["response_type"]} {{
        self.raw
    }}
}}

impl From<{config["response_type"]}> for {config["response_wrapper"]} {{
    fn from(raw: {config["response_type"]}) -> Self {{
        Self {{ raw }}
    }}
}}

#[derive(Debug, Clone, Copy)]
pub struct OcrPage<'a> {{
    raw: &'a OCRPageObject,
}}

impl<'a> OcrPage<'a> {{
    fn new(raw: &'a OCRPageObject) -> Self {{
        Self {{ raw }}
    }}
    pub fn index(&self) -> i64 {{
        self.raw.index
    }}
    pub fn markdown(&self) -> &str {{
        &self.raw.markdown
    }}
    pub fn raw(&self) -> &OCRPageObject {{
        self.raw
    }}
}}

/// A generated ergonomic wrapper over [`{config["request_type"]}`].
#[derive(Debug, Clone)]
pub struct {config["request_wrapper"]} {{
    raw: {config["request_type"]},
}}

impl {config["request_wrapper"]} {{
    pub fn document_url(model: impl Into<String>, url: impl Into<String>) -> Self {{
        Self::new(
            model,
            OCRRequestDocument::DocumentURLChunk(DocumentURLChunk {{
                document_name: None,
                document_url: url.into(),
                r#type: None,
            }}),
        )
    }}
    pub fn image_url(model: impl Into<String>, url: impl Into<String>) -> Self {{
        Self::new(
            model,
            OCRRequestDocument::ImageURLChunk(ImageURLChunk {{
                image_url: ImageURLChunkImageUrl::String(url.into()),
                r#type: None,
            }}),
        )
    }}
    pub fn file_id(model: impl Into<String>, file_id: uuid::Uuid) -> Self {{
        Self::new(
            model,
            OCRRequestDocument::FileChunk(FileChunk {{
                file_id,
                r#type: None,
            }}),
        )
    }}
    fn new(model: impl Into<String>, document: OCRRequestDocument) -> Self {{
        Self {{
            raw: {config["request_type"]}::new(document, Some(model.into())),
        }}
    }}
    pub fn from_raw(raw: {config["request_type"]}) -> Self {{
        Self {{ raw }}
    }}
{setters}
    pub fn as_raw(&self) -> &{config["request_type"]} {{
        &self.raw
    }}
    pub fn into_raw(self) -> {config["request_type"]} {{
        self.raw
    }}
}}

#[derive(Clone, Copy)]
pub struct {config["resource_type"]}<'a> {{
    raw: &'a HttpClient,
}}

impl<'a> {config["resource_type"]}<'a> {{
    pub(crate) fn new(raw: &'a HttpClient) -> Self {{
        Self {{ raw }}
    }}
    pub async fn process(&self, request: {config["request_wrapper"]}) -> Result<{config["response_wrapper"]}, SdkError> {{
        self.raw
            .{config["operation"]}(request.into_raw())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }}
}}
'''


def generate_mod(chat: dict, ocr: dict) -> str:
    return GENERATED + f'''pub mod chat;
pub mod error;
pub mod ocr;

pub use chat::{{{chat["resource_type"]}, {chat["request_wrapper"]}, {chat["response_wrapper"]}, {chat["stream_type"]}, {chat["stream_item_wrapper"]}, Message}};
pub use error::{{ApiError, SdkError, TransportError, TransportErrorKind}};
pub use ocr::{{{ocr["resource_type"]}, OcrPage, {ocr["request_wrapper"]}, {ocr["response_wrapper"]}}};

use crate::generated::client::HttpClient;

#[derive(Clone)]
pub struct Mistral {{
    raw: HttpClient,
}}

impl Mistral {{
    pub fn new(api_key: impl Into<String>) -> Self {{
        Self {{
            raw: HttpClient::new().with_api_key(api_key),
        }}
    }}
    #[must_use]
    pub fn with_base_url(mut self, base_url: impl Into<String>) -> Self {{
        self.raw = self.raw.with_base_url(base_url);
        self
    }}
    pub fn chat(&self) -> {chat["resource_type"]}<'_> {{
        {chat["resource_type"]}::new(&self.raw)
    }}
    pub fn ocr(&self) -> {ocr["resource_type"]}<'_> {{
        {ocr["resource_type"]}::new(&self.raw)
    }}
    pub fn raw(&self) -> &HttpClient {{
        &self.raw
    }}
}}
'''


def generate(raw: Path, target: Path, manifest_path: Path) -> None:
    manifest = json.loads(manifest_path.read_text())
    if manifest.get("schema_version") != 1:
        raise ValueError("unsupported SDK semantic manifest version")
    types = (raw / "types.rs").read_text()
    client = (raw / "client.rs").read_text()
    chat = manifest["resources"]["chat"]
    ocr = manifest["resources"]["ocr"]

    for config in (chat, ocr):
        for key in ("request_type", "response_type"):
            require_type(types, config[key])
    require_type(types, chat["stream_item_type"])
    require_operation(client, chat["complete_operation"], chat["request_type"])
    require_operation(client, chat["stream_operation"], chat["request_type"])
    require_operation(client, ocr["operation"], ocr["request_type"])

    chat_fields = struct_fields(types, chat["request_type"])
    ocr_fields = struct_fields(types, ocr["request_type"])
    target.mkdir(parents=True, exist_ok=True)
    (target / "chat.rs").write_text(generate_chat(chat, chat_fields))
    (target / "ocr.rs").write_text(generate_ocr(ocr, ocr_fields))
    (target / "mod.rs").write_text(generate_mod(chat, ocr))
    coverage = {
        "schema_version": 1,
        "resources": {
            "chat": {
                "operations": [chat["complete_operation"], chat["stream_operation"]],
                "request_fields": sorted(chat_fields),
            },
            "ocr": {
                "operations": [ocr["operation"]],
                "request_fields": sorted(ocr_fields),
            },
        },
    }
    (target / "coverage.json").write_text(json.dumps(coverage, indent=2) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("raw", type=Path)
    parser.add_argument("target", type=Path)
    parser.add_argument("--manifest", type=Path, required=True)
    args = parser.parse_args()
    generate(args.raw, args.target, args.manifest)


if __name__ == "__main__":
    main()
