"""Compile OpenAPI plus a semantic overlay into a resource-oriented Rust SDK.

OpenAPI owns the wire contract. The overlay only supplies stable public names
and deliberate conveniences that HTTP cannot express. Generated Rust bindings
are reconciled through a real tree-sitter syntax tree, never regular expressions.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import json
from pathlib import Path
from typing import Any, Iterable

from ruamel.yaml import YAML
from tree_sitter import Language, Node, Parser
import tree_sitter_rust
from rust_types import RustType, parse_type
from rust_symbols import SymbolProvider, field_identifier
from jsonschema import Draft202012Validator
from sdk_contracts import public_surface, coverage_inventory
from sdk_autoproject import expand_manifest
from sdk_ir import (Accessor, ModelPolicy, RequestPolicy, SimpleUnionPolicy, UnionPolicy, ViewPolicy,
                    StreamPolicy, model_policy, stream_policy)


GENERATED = "// @generated by codegen/sdk_facade.py; do not edit by hand.\n"


class GenerationError(ValueError):
    """A source contract cannot be projected without semantic review."""


def _text(source: bytes, node: Node | None) -> str:
    if node is None:
        raise GenerationError("missing Rust AST node")
    return source[node.start_byte : node.end_byte].decode()


def _children(node: Node | None, kind: str) -> list[Node]:
    return [child for child in node.named_children if child.type == kind] if node else []


@dataclass(frozen=True)
class RustField:
    name: str
    syntax: RustType

    @property
    def type(self) -> str:
        return self.syntax.spelling


@dataclass(frozen=True)
class RustVariant:
    name: str
    payload: str | None


@dataclass(frozen=True)
class RustParameter:
    name: str
    syntax: RustType

    @property
    def type(self) -> str:
        return self.syntax.spelling


@dataclass(frozen=True)
class RustOperation:
    name: str
    parameters: tuple[RustParameter, ...]
    return_type: str
    success_type: str


class RustIndex:
    """Typed symbol table built from openapi-to-rust output."""

    def __init__(self, types_source: bytes, client_source: bytes):
        parser = Parser(Language(tree_sitter_rust.language()))
        self.structs: dict[str, tuple[RustField, ...]] = {}
        self.enums: dict[str, tuple[RustVariant, ...]] = {}
        self.aliases: dict[str, RustType] = {}
        self.operations: dict[str, RustOperation] = {}
        self.symbol_modules: dict[str, str] = {}
        for label, source in (("types", types_source), ("client", client_source)):
            root = parser.parse(source).root_node
            if root.has_error:
                raise GenerationError(f"invalid raw Rust {label} syntax")
            for item in root.named_children:
                if item.type in {"struct_item", "enum_item", "type_item"}:
                    name = _text(source, item.child_by_field_name("name"))
                    if name in self.symbol_modules:
                        raise GenerationError(f"ambiguous raw symbol {name}")
                    self.symbol_modules[name] = label
        self._index_types(types_source, parser.parse(types_source).root_node)
        self._index_client(client_source, parser.parse(client_source).root_node)

    @classmethod
    def load(cls, raw: Path) -> "RustIndex":
        return cls((raw / "types.rs").read_bytes(), (raw / "client.rs").read_bytes())

    def _index_types(self, source: bytes, root: Node) -> None:
        for item in root.named_children:
            if item.type == "struct_item":
                name = _text(source, item.child_by_field_name("name"))
                fields = []
                for field in _children(item.child_by_field_name("body"), "field_declaration"):
                    if not _children(field, "visibility_modifier"):
                        continue
                    fields.append(RustField(
                        _text(source, field.child_by_field_name("name")),
                        parse_type(_text(source, field.child_by_field_name("type"))),
                    ))
                self.structs[name] = tuple(fields)
            elif item.type == "enum_item":
                name = _text(source, item.child_by_field_name("name"))
                variants = []
                for variant in _children(item.child_by_field_name("body"), "enum_variant"):
                    variant_name = _text(source, variant.child_by_field_name("name"))
                    body = variant.child_by_field_name("body")
                    payload = None
                    if body and body.type == "ordered_field_declaration_list":
                        payload_nodes = [child for child in body.named_children]
                        if len(payload_nodes) != 1:
                            raise GenerationError(f"raw enum {name}::{variant_name} is not unary")
                        payload = _text(source, payload_nodes[0])
                    variants.append(RustVariant(variant_name, payload))
                self.enums[name] = tuple(variants)
            elif item.type == "type_item":
                name = _text(source, item.child_by_field_name("name"))
                self.aliases[name] = parse_type(_text(source, item.child_by_field_name("type")))

    def _index_client(self, source: bytes, root: Node) -> None:
        for item in root.named_children:
            if item.type != "impl_item":
                continue
            if _text(source, item.child_by_field_name("type")) != "HttpClient":
                continue
            for function in _children(item.child_by_field_name("body"), "function_item"):
                name = _text(source, function.child_by_field_name("name"))
                parameters = []
                for parameter in (function.child_by_field_name("parameters") or ()).named_children:
                    if parameter.type != "parameter":
                        continue
                    identifier = next((child for child in parameter.named_children
                                       if child.type in {"identifier", "field_identifier"}), None)
                    parameters.append(RustParameter(
                        _text(source, identifier),
                        parse_type(_text(source, parameter.child_by_field_name("type"))),
                    ))
                return_node = function.child_by_field_name("return_type")
                success_type = ""
                if return_node and return_node.type == "generic_type":
                    arguments = next((child for child in return_node.named_children
                                      if child.type == "type_arguments"), None)
                    if arguments and arguments.named_children:
                        success_type = _text(source, arguments.named_children[0])
                self.operations[name] = RustOperation(
                    name, tuple(parameters), _text(source, return_node), success_type,
                )

    def fields(self, name: str) -> tuple[RustField, ...]:
        try:
            return self.structs[name]
        except KeyError as error:
            raise GenerationError(f"raw Rust struct not found: {name}") from error

    def variants(self, name: str) -> tuple[RustVariant, ...]:
        try:
            return self.enums[name]
        except KeyError as error:
            raise GenerationError(f"raw Rust enum not found: {name}") from error

    def operation(self, name: str) -> RustOperation:
        try:
            return self.operations[name]
        except KeyError as error:
            raise GenerationError(f"raw Rust operation not found: {name}") from error

    def qualified_type(self, spelling: str) -> str:
        def render(syntax: RustType) -> str:
            if syntax.kind == "generic_type":
                return f"{syntax.constructor}<{', '.join(render(argument) for argument in syntax.arguments)}>"
            if syntax.spelling in self.symbol_modules:
                return f"crate::generated::{self.symbol_modules[syntax.spelling]}::{syntax.spelling}"
            return syntax.spelling
        return render(parse_type(spelling))


def _ref_name(schema: dict[str, Any]) -> str | None:
    ref = schema.get("$ref")
    return ref.rsplit("/", 1)[-1] if isinstance(ref, str) else None


def _success_schema(operation: dict[str, Any], media: str = "application/json") -> dict[str, Any]:
    for status, response in sorted(operation.get("responses", {}).items()):
        if str(status).startswith("2") and media in response.get("content", {}):
            return response["content"][media].get("schema", {})
    raise GenerationError(f"operation has no successful {media} response")


class OpenApiIndex:
    """Semantic source for schemas, HTTP operations and discriminators."""

    def __init__(self, document: dict[str, Any]):
        self.document = document
        self.schemas = document.get("components", {}).get("schemas", {})
        self.operations: dict[str, dict[str, Any]] = {}
        for path, path_item in document.get("paths", {}).items():
            for method in ("get", "put", "post", "delete", "patch", "head", "options"):
                operation = path_item.get(method)
                if not operation or "operationId" not in operation:
                    continue
                combined = dict(operation)
                combined["parameters"] = path_item.get("parameters", []) + operation.get("parameters", [])
                combined["x-sdk-path"] = path
                combined["x-sdk-method"] = method
                self.operations[operation["operationId"]] = combined

    @classmethod
    def load(cls, path: Path) -> "OpenApiIndex":
        return cls(YAML(typ="safe").load(path.read_text()))

    def schema(self, name: str) -> dict[str, Any]:
        try:
            return self.schemas[name]
        except KeyError as error:
            raise GenerationError(f"OpenAPI schema not found: {name}") from error

    def operation(self, operation_id: str) -> dict[str, Any]:
        try:
            return self.operations[operation_id]
        except KeyError as error:
            raise GenerationError(f"OpenAPI operation not found: {operation_id}") from error

    def request_schema(self, operation_id: str) -> str | None:
        request = self.operation(operation_id).get("requestBody", {})
        schema = request.get("content", {}).get("application/json", {}).get("schema", {})
        return _ref_name(schema)

    def response_schema(self, operation_id: str) -> str | None:
        return _ref_name(_success_schema(self.operation(operation_id)))

    def response_matches(self, operation_id: str, raw: str, rust: RustIndex) -> bool:
        """Reconcile named and inline successful response schemas with raw Rust."""
        schema = _success_schema(self.operation(operation_id))
        referenced = _ref_name(schema)
        if referenced:
            return referenced == raw
        branches = schema.get("oneOf", []) or schema.get("anyOf", [])
        payloads = {_ref_name(branch) for branch in branches}
        if branches and None not in payloads and raw in rust.enums:
            return payloads == {variant.payload for variant in rust.variants(raw)}
        return False

    def union(self, root: str, path: Iterable[str]) -> tuple[str, dict[str, str]]:
        schema = self.schema(root)
        for segment in path:
            schema = schema.get("items", {}) if segment == "items" else schema.get("properties", {}).get(segment, {})
            non_null = [part for part in schema.get("anyOf", []) if part.get("type") != "null"]
            if len(non_null) == 1:
                schema = non_null[0]
        discriminator = schema.get("discriminator", {})
        mapping = {tag: ref.rsplit("/", 1)[-1]
                   for tag, ref in discriminator.get("mapping", {}).items()}
        if not mapping:
            # OpenAPI authors often omit an explicit discriminator even though
            # every object branch carries the same const-valued tag. Infer the
            # semantic union exactly as modern SDK generators do.
            branches = schema.get("oneOf", []) or schema.get("anyOf", [])
            referenced = [_ref_name(branch) for branch in branches]
            if referenced and all(referenced):
                candidates: dict[str, dict[str, str]] = {}
                for name in referenced:
                    properties = self.schema(name).get("properties", {})
                    for property_name, property_schema in properties.items():
                        if "const" in property_schema:
                            candidates.setdefault(property_name, {})[str(property_schema["const"])] = name
                complete = [(name, values) for name, values in candidates.items()
                            if len(values) == len(referenced)]
                if len(complete) == 1:
                    property_name, mapping = complete[0]
                    discriminator = {"propertyName": property_name}
        if not mapping:
            raise GenerationError(f"{root}.{'.'.join(path)} is not a discriminated union")
        return discriminator["propertyName"], mapping


@dataclass(frozen=True)
class ModelSpec:
    name: str
    raw: str
    config: ModelPolicy


@dataclass(frozen=True)
class OperationSpec:
    name: str
    operation_id: str
    raw_method: str
    request: str | None
    response: str | None
    request_overrides: tuple[tuple[str, bool | None], ...]
    stream: StreamPolicy | None
    request_raw: str | None = None
    empty_response: bool = False
    binary_response: bool = False


@dataclass(frozen=True)
class ResourceSpec:
    path: tuple[str, ...]
    module: str
    name: str
    operations: tuple[OperationSpec, ...]


@dataclass(frozen=True)
class SdkIr:
    client_name: str
    models: tuple[ModelSpec, ...]
    resources: tuple[ResourceSpec, ...]


def _validate_keys(value: dict[str, Any], allowed: set[str], context: str) -> None:
    unknown = sorted(set(value) - allowed)
    if unknown:
        raise GenerationError(f"unknown {context} keys: {', '.join(unknown)}")


def build_ir(openapi: OpenApiIndex, rust: RustIndex, manifest: dict[str, Any]) -> SdkIr:
    schema = json.loads(Path(__file__).with_name("sdk-semantics.schema.json").read_text())
    errors = sorted(Draft202012Validator(schema).iter_errors(manifest), key=lambda error: str(error.path))
    if errors:
        error = errors[0]
        raise GenerationError(f"overlay /{'/'.join(map(str, error.absolute_path))}: {error.message}")
    _validate_keys(manifest, {"schema_version", "client", "models", "resources"}, "manifest")
    if manifest.get("schema_version") != 2:
        raise GenerationError("unsupported SDK semantic manifest version")
    models = []
    for name, config in manifest.get("models", {}).items():
        _validate_keys(config, {"raw", "constructor", "exclude", "adapters", "union", "simple_union", "union_factory", "accessors", "borrowed"}, f"model {name}")
        raw = config.get("raw", name)
        if "union" in config:
            union = config["union"]
            _validate_keys(union, {"root", "path", "payload", "targets"}, f"union {name}")
            _, mapping = openapi.union(union["root"], union["path"])
            for target in (raw, *union.get("targets", [])):
                variants = {variant.payload for variant in rust.variants(target)}
                missing = sorted(set(mapping.values()) - variants)
                extra = sorted(variants - set(mapping.values()))
                if missing or extra:
                    raise GenerationError(
                        f"raw union {target} branch drift: missing={missing}, extra={extra}"
                    )
        elif "simple_union" in config:
            configured = set(config["simple_union"]["variants"])
            actual = {variant.name for variant in rust.variants(raw)}
            if configured != actual:
                raise GenerationError(
                    f"raw union {raw} variant drift: missing={sorted(actual - configured)}, "
                    f"extra={sorted(configured - actual)}"
                )
        else:
            # Empty response views may deliberately encapsulate an inline raw
            # enum. Accessor-bearing views still require a struct.
            if config.get("accessors") or raw not in rust.enums:
                rust.fields(raw)
            if "constructor" in config or "union_factory" in config:
                schema = openapi.schema(raw)
                wire_fields = set(schema.get("properties", {}))
                raw_fields = {field.name.removeprefix("r#") for field in rust.fields(raw)}
                if wire_fields != raw_fields:
                    missing = sorted(wire_fields - raw_fields)
                    extra = sorted(raw_fields - wire_fields)
                    raise GenerationError(
                        f"OpenAPI/raw field drift for {raw}: missing={missing}, extra={extra}"
                    )
                covered = set(config.get("constructor", [])) | set(config.get("exclude", []))
                factory = config.get("union_factory", {})
                covered |= {factory.get("field"), *factory.get("leading", [])}
                uncovered_required = set(schema.get("required", [])) - covered
                if uncovered_required:
                    raise GenerationError(
                        f"required fields need constructor policy for {raw}: {sorted(uncovered_required)}"
                    )
        models.append(ModelSpec(name, raw, model_policy(config)))
    model_names = {model.name for model in models}
    for model in models:
        references = []
        if isinstance(model.config, RequestPolicy):
            references.extend(adapter for _, adapter in model.config.adapters)
        elif isinstance(model.config, SimpleUnionPolicy):
            references.extend(adapter for _, _, adapter in model.config.variants if adapter)
        elif isinstance(model.config, ViewPolicy):
            references.extend(accessor.wrapper for _, accessor in model.config.accessors
                              if accessor.wrapper)
        unknown = sorted(set(references) - model_names)
        if unknown:
            raise GenerationError(f"model {model.name} references unknown facade models: {unknown}")
    resources = []
    for module, config in manifest.get("resources", {}).items():
        _validate_keys(config, {"name", "path", "operations"}, f"resource {module}")
        operations = []
        for public_name, item in config.get("operations", {}).items():
            _validate_keys(item, {"operation_id", "raw_method", "request", "response", "empty_response", "binary_response", "request_overrides", "stream"}, f"operation {module}.{public_name}")
            operation_id = item["operation_id"]
            raw_method = item.get("raw_method", operation_id)
            raw_operation = rust.operation(raw_method)
            wire_operation = openapi.operation(operation_id)
            request, response = item.get("request"), item.get("response")
            empty_response = item.get("empty_response", False)
            binary_response = item.get("binary_response", False)
            success_modes = int(bool(response)) + int(bool(item.get("stream"))) + int(empty_response) + int(binary_response)
            if success_modes != 1:
                raise GenerationError(
                    f"operation {module}.{public_name} requires exactly one response, stream, empty_response or binary_response projection"
                )
            for referenced in (request, response):
                if referenced and referenced not in model_names:
                    raise GenerationError(f"unknown facade model {referenced}")
            if request:
                model = next(model for model in models if model.name == request)
                if openapi.request_schema(operation_id) != model.raw:
                    raise GenerationError(f"OpenAPI request drift for {operation_id}")
                body_parameters = [parameter for parameter in raw_operation.parameters
                                   if parameter.type == model.raw]
                if len(body_parameters) != 1:
                    raise GenerationError(f"raw signature drift for {raw_method}")
                request_fields = _field_map(rust, model.raw)
                unknown_overrides = set(item.get("request_overrides", {})) - set(request_fields)
                if unknown_overrides:
                    raise GenerationError(f"unknown request overrides for {raw_method}: {sorted(unknown_overrides)}")
                for field, value in item.get("request_overrides", {}).items():
                    syntax = request_fields[field].syntax
                    inner = syntax.unary("Option")
                    wire_field = openapi.schema(model.raw).get("properties", {}).get(field, {})
                    if inner is None or inner.spelling != "bool" or wire_field.get("type") != "boolean":
                        raise GenerationError(f"request override requires optional Boolean in both contracts: {model.raw}.{field}")
                    if value is not None and type(value) is not bool:
                        raise GenerationError(f"invalid Boolean override: {model.raw}.{field}")
            elif item.get("request_overrides"):
                raise GenerationError(f"request overrides require a body projection: {raw_method}")
            raw_parameters = tuple(parameter for parameter in raw_operation.parameters
                                   if not request or parameter.type != model.raw)
            wire_parameter_names = tuple(parameter["name"].replace("-", "_")
                                         for parameter in wire_operation.get("parameters", []))
            raw_parameter_names = tuple(parameter.name.removeprefix("r#") for parameter in raw_parameters)
            if len(set(raw_parameter_names)) != len(raw_parameter_names):
                raise GenerationError(f"duplicate raw parameter names for {raw_method}")
            if sorted(raw_parameter_names) != sorted(wire_parameter_names):
                raise GenerationError(f"OpenAPI/raw parameter drift for {raw_method}")
            if empty_response:
                success = [value for status, value in wire_operation.get("responses", {}).items()
                           if str(status).startswith("2")]
                if len(success) != 1 or success[0].get("content"):
                    raise GenerationError(f"empty response drift for {operation_id}")
                if raw_operation.success_type != "()":
                    raise GenerationError(f"raw empty response drift for {raw_method}")
            if binary_response:
                success = [value for status, value in wire_operation.get("responses", {}).items()
                           if str(status).startswith("2")]
                if len(success) != 1 or len(success[0].get("content", {})) != 1:
                    raise GenerationError(f"binary response drift for {operation_id}")
                payload = next(iter(success[0]["content"].values()))
                schema = payload.get("schema", {})
                if schema.get("type") != "string" or schema.get("format") != "binary":
                    raise GenerationError(f"binary response drift for {operation_id}")
                transport = parse_type(raw_operation.success_type)
                if transport.constructor != "futures_util::stream::BoxStream" or len(transport.arguments) != 2:
                    raise GenerationError(f"raw binary response is not an owned BoxStream: {raw_method}")
                lifetime, event = transport.arguments
                if lifetime.spelling != "'static" or event.constructor != "Result" or tuple(arg.spelling for arg in event.arguments) != ("bytes::Bytes", "reqwest::Error"):
                    raise GenerationError(f"raw binary response ownership/item drift: {raw_method}")
            if response and not item.get("stream"):
                model = next(model for model in models if model.name == response)
                if not openapi.response_matches(operation_id, model.raw, rust):
                    raise GenerationError(f"OpenAPI response drift for {operation_id}")
                if raw_operation.success_type != model.raw:
                    raise GenerationError(f"raw response drift for {raw_method}")
            if item.get("stream"):
                stream = stream_policy(item["stream"])
                if not request:
                    raise GenerationError(f"stream requires a request projection: {raw_method}")
                wire_schema = _success_schema(wire_operation, "text/event-stream")
                wire_item = _ref_name(wire_schema)
                if wire_item and wire_item != stream.item:
                    envelope = openapi.schema(wire_item)
                    wire_item = _ref_name(envelope.get("properties", {}).get("data", {}))
                    if "data" not in envelope.get("required", []):
                        raise GenerationError(f"stream envelope has no required data: {raw_method}")
                if wire_item != stream.item:
                    raise GenerationError(f"stream payload drift for {raw_method}: {wire_item} != {stream.item}")
                rust.fields(stream.item)
                wrapper = next((model for model in models if model.name == stream.wrapper), None)
                if wrapper is None or wrapper.raw != stream.item or not isinstance(wrapper.config, ViewPolicy) or wrapper.config.borrowed:
                    raise GenerationError(f"stream wrapper must own the configured item: {stream.wrapper}")
                transport = parse_type(raw_operation.success_type)
                if transport.constructor != "futures_util::stream::BoxStream" or len(transport.arguments) != 2:
                    raise GenerationError(f"stream transport is not an owned BoxStream: {raw_method}")
                lifetime, event = transport.arguments
                if lifetime.spelling != "'static" or event.constructor != "Result" or tuple(arg.spelling for arg in event.arguments) != ("bytes::Bytes", "reqwest::Error"):
                    raise GenerationError(f"stream transport ownership/item drift: {raw_method}")
            request_raw = (next(model.raw for model in models if model.name == request)
                           if request else None)
            operations.append(OperationSpec(public_name, operation_id, raw_method, request, response,
                                            tuple(item.get("request_overrides", {}).items()),
                                            stream_policy(item.get("stream")), request_raw, empty_response, binary_response))
        resource_path = tuple(config.get("path", (module,)))
        if not resource_path:
            raise GenerationError(f"resource {module} has an empty path")
        resources.append(ResourceSpec(resource_path, module, config["name"], tuple(operations)))
    ir = SdkIr(manifest.get("client", {}).get("name", "Client"), tuple(models), tuple(resources))
    _validate_symbols(ir, rust)
    return ir


def _validate_symbols(ir: SdkIr, rust: RustIndex) -> None:
    symbols = SymbolProvider()
    try:
        for reserved in ("SdkError", "ApiError", "TransportError", "TransportErrorKind", "HttpClient"):
            symbols.claim(reserved, "sdk", "runtime")
        symbols.claim(ir.client_name, "sdk", "client")
        for reserved in ("new", "raw", "with_base_url"):
            symbols.claim(reserved, ir.client_name, "client runtime")
        for model in ir.models:
            symbols.claim(model.name, "sdk", f"model {model.raw}", "facade_types")
            if model.name in rust.structs or model.name in rust.enums:
                raise ValueError(f"facade model {model.name} shadows imported raw type; choose an explicit semantic name")
        for reserved in ("error", "facade_types", "mod"):
            symbols.claim(reserved if reserved != "mod" else "mod_file", "modules", "runtime")
        by_path = {resource.path: resource for resource in ir.resources}
        for resource in ir.resources:
            if resource.module == "mod":
                raise ValueError("resource module mod is reserved")
            symbols.claim(resource.module, "modules", "resource")
            symbols.claim(resource.name, "sdk", "resource", resource.module)
            symbols.claim("new", resource.name, "resource constructor")
            if len(resource.path) == 1:
                symbols.claim(resource.path[0], ir.client_name, "resource accessor")
            else:
                parent = by_path.get(resource.path[:-1])
                if parent is None:
                    raise ValueError(f"resource {'.'.join(resource.path)} has no parent")
                symbols.claim(resource.path[-1], parent.name, "child resource accessor")
            for operation in resource.operations:
                symbols.claim(operation.name, resource.name, operation.operation_id)
                parameters = rust.operation(operation.raw_method).parameters
                if (not operation.request and parameters
                        and any(_option(parameter.type) for parameter in parameters)):
                    symbols.claim(_request_name(resource, operation), f"module:{resource.module}", operation.operation_id)
                    if all(_option(parameter.type) for parameter in parameters):
                        symbols.claim(operation.name + "_with", resource.name, operation.operation_id)
                if operation.stream:
                    symbols.claim(operation.stream.type, "sdk", operation.operation_id, "facade_types")
    except ValueError as error:
        raise GenerationError(str(error)) from error


def _option(type_name: str) -> tuple[str, bool] | None:
    inner = parse_type(type_name).unary("Option")
    if inner is None:
        return None
    nullable = inner.unary("Option")
    return (nullable.spelling, True) if nullable else (inner.spelling, False)


def _argument(name: str, type_name: str) -> tuple[str, str]:
    name = field_identifier(name)
    return ((f"{name}: impl Into<String>", f"{name}.into()")
            if type_name == "String" else (f"{name}: {type_name}", name))


def _indent(value: str, spaces: int = 4) -> str:
    prefix = " " * spaces
    return "\n".join(prefix + line if line else line for line in value.splitlines())


def _field_map(rust: RustIndex, raw: str) -> dict[str, RustField]:
    return {field.name.removeprefix("r#"): field for field in rust.fields(raw)}


def _wrap(type_name: str, value: str) -> str:
    optional = _option(type_name)
    if optional is None:
        return value
    return f"Some(Some({value}))" if optional[1] else f"Some({value})"


def _emit_setters(model: ModelSpec, rust: RustIndex) -> str:
    assert isinstance(model.config, RequestPolicy)
    excluded = set(model.config.exclude) | set(model.config.constructor)
    methods = []
    for field in rust.fields(model.raw):
        name = field.name.removeprefix("r#")
        if name in excluded:
            continue
        optional = _option(field.type)
        if optional is None:
            raise GenerationError(
                f"new required field {model.raw}.{name}; constructor policy needs semantic review"
            )
        inner, nullable = optional
        adapter = dict(model.config.adapters).get(name)
        if adapter:
            argument, value = _constructor_arg(name, RustField(name, parse_type(inner)), adapter)
        else:
            argument, value = _argument(name, inner)
        methods.append(
            f"#[must_use]\npub fn {field_identifier(name)}(mut self, {argument}) -> Self {{\n"
            f"    self.raw.{field.name} = {_wrap(field.type, value)};\n    self\n}}"
        )
        if nullable:
            methods.append(
                f"#[must_use]\npub fn {name}_null(mut self) -> Self {{\n"
                f"    self.raw.{field.name} = Some(None);\n    self\n}}"
            )
    return "\n\n".join(methods)


def _constructor_arg(name: str, field: RustField, adapter: str | None) -> tuple[str, str]:
    name = field_identifier(name)
    if adapter:
        if parse_type(field.type).unary("Vec") is not None:
            return (f"{name}: impl IntoIterator<Item = {adapter}>",
                    f"{name}.into_iter().map(Into::into).collect()")
        return (f"{name}: impl Into<{adapter}>",
                f"Into::<{adapter}>::into({name}).into()")
    optional = _option(field.type)
    effective = optional[0] if optional else field.type
    argument, value = _argument(name, effective)
    return argument, _wrap(field.type, value)


def _struct_literal(raw: str, fields: dict[str, RustField], values: dict[str, str]) -> str:
    assignments = []
    for name, field in fields.items():
        if name in values:
            value = values[name]
            assignments.append(field.name if value == field.name and not field.name.startswith("r#")
                               else f"{field.name}: {value}")
        elif _option(field.type):
            assignments.append(f"{field.name}: None")
        else:
            raise GenerationError(f"required raw field {raw}.{name} has no value")
    return f"{raw} {{ {', '.join(assignments)} }}"


def _factory_value(type_name: str, argument: str, rust: RustIndex) -> tuple[str, str]:
    argument = field_identifier(argument)
    optional = _option(type_name)
    core = optional[0] if optional else type_name
    if core == "String":
        declaration, value = f"{argument}: impl Into<String>", f"{argument}.into()"
    elif core in rust.enums:
        string = next((variant for variant in rust.variants(core) if variant.payload == "String"), None)
        if not string:
            declaration, value = f"{argument}: {core}", argument
        else:
            declaration, value = f"{argument}: impl Into<String>", f"{core}::{string.name}({argument}.into())"
    else:
        declaration, value = f"{argument}: {core}", argument
    return declaration, _wrap(type_name, value)


def _emit_union_factories(model: ModelSpec, openapi: OpenApiIndex, rust: RustIndex) -> str:
    assert isinstance(model.config, RequestPolicy) and model.config.factory is not None
    config = model.config.factory
    field_name = config.field
    fields = _field_map(rust, model.raw)
    union_type = _option(fields[field_name].type)
    raw_union = union_type[0] if union_type else fields[field_name].type
    discriminator, mapping = openapi.union(model.raw, [field_name])
    raw_variants = {variant.payload: variant.name for variant in rust.variants(raw_union)}
    methods = []
    for tag, payload in sorted(mapping.items()):
        payload_schema = openapi.schema(payload)
        candidates = [name for name in payload_schema.get("required", []) if name != discriminator]
        if len(candidates) != 1:
            raise GenerationError(f"factory branch {payload} needs one non-discriminator input, got {candidates}")
        input_name = candidates[0]
        payload_fields = _field_map(rust, payload)
        if input_name not in payload_fields:
            raise GenerationError(f"raw field {payload}.{input_name} not found")
        public_name = dict(config.rename).get(tag, tag.replace("-", "_"))
        arguments, outer_values = [], {}
        for leading in config.leading:
            declaration, value = _factory_value(fields[leading].type, leading, rust)
            arguments.append(declaration)
            outer_values[leading] = value
        declaration, value = _factory_value(payload_fields[input_name].type, input_name, rust)
        arguments.append(declaration)
        payload_value = _struct_literal(payload, payload_fields, {input_name: value})
        outer_values[field_name] = _wrap(fields[field_name].type, f"{raw_union}::{raw_variants[payload]}({payload_value})")
        raw_value = _struct_literal(model.raw, fields, outer_values)
        methods.append(f"pub fn {public_name}({', '.join(arguments)}) -> Self {{ Self {{ raw: {raw_value} }} }}")
    return "\n\n".join(methods)


def _emit_wrapper(model: ModelSpec, openapi: OpenApiIndex, rust: RustIndex) -> str:
    fields = _field_map(rust, model.raw)
    methods = []
    assert isinstance(model.config, RequestPolicy)
    constructor = model.config.constructor
    if constructor or model.config.factory is None:
        arguments, values = [], []
        for name in constructor:
            if name not in fields:
                raise GenerationError(f"constructor field {model.raw}.{name} not found")
            argument, value = _constructor_arg(name, fields[name], dict(model.config.adapters).get(name))
            arguments.append(argument)
            values.append(value)
        raw_values = {name: value for name, value in zip(constructor, values)}
        methods.append(f"pub fn new({', '.join(arguments)}) -> Self {{\n"
                       f"    Self {{ raw: {_struct_literal(model.raw, fields, raw_values)} }}\n}}")
    if model.config.factory is not None:
        methods.append(_emit_union_factories(model, openapi, rust))
    setters = _emit_setters(model, rust)
    if setters:
        methods.append(setters)
    methods.extend((
        f"pub fn from_raw(raw: {model.raw}) -> Self {{ Self {{ raw }} }}",
        f"pub fn as_raw(&self) -> &{model.raw} {{ &self.raw }}",
        f"pub fn into_raw(self) -> {model.raw} {{ self.raw }}",
    ))
    default = (
        f"\n\nimpl Default for {model.name} {{\n"
        f"    fn default() -> Self {{ Self::new() }}\n}}"
        if not constructor and model.config.factory is None else ""
    )
    return (
        f"#[derive(Debug, Clone)]\npub struct {model.name} {{ raw: {model.raw} }}\n\n"
        f"impl {model.name} {{\n{_indent(chr(10).join(methods))}\n}}\n\n"
        f"impl From<{model.raw}> for {model.name} {{\n"
        f"    fn from(raw: {model.raw}) -> Self {{ Self {{ raw }} }}\n}}\n\n"
        f"impl From<{model.name}> for {model.raw} {{\n"
        f"    fn from(value: {model.name}) -> Self {{ value.into_raw() }}\n}}" + default
    )


def _public_variant(tag: str) -> str:
    return "".join(part[:1].upper() + part[1:]
                   for part in tag.replace("-", "_").split("_") if part)


def _string_payload(raw_payload: str, payload_field: str, rust: RustIndex) -> str:
    assignments = []
    for field in rust.fields(raw_payload):
        name = field.name.removeprefix("r#")
        if name == payload_field:
            optional = _option(field.type)
            core = optional[0] if optional else field.type
            if core == "String":
                value = "content"
            else:
                string_variant = next((variant for variant in rust.variants(core)
                                       if variant.payload == "String"), None)
                if not string_variant:
                    raise GenerationError(f"{raw_payload}.{payload_field} has no String branch")
                value = f"{core}::{string_variant.name}(content)"
            assignments.append(f"{field.name}: {_wrap(field.type, value)}")
        elif _option(field.type):
            assignments.append(f"{field.name}: None")
        else:
            raise GenerationError(f"{raw_payload} also requires {name}")
    return f"{raw_payload} {{ {', '.join(assignments)} }}"


def _emit_union(model: ModelSpec, openapi: OpenApiIndex, rust: RustIndex) -> str:
    assert isinstance(model.config, UnionPolicy)
    config = model.config
    _, mapping = openapi.union(config.root, config.path)
    variants, constructors = [], []
    payload_expressions = {}
    for tag, raw_payload in sorted(mapping.items()):
        public = _public_variant(tag)
        try:
            expression = _string_payload(raw_payload, config.payload, rust)
        except GenerationError:
            variants.append(f"{public}({raw_payload})")
            constructors.append(f"pub fn {tag.replace('-', '_')}(value: {raw_payload}) -> Self {{ Self::{public}(value) }}")
            payload_expressions[raw_payload] = (public, "value")
        else:
            variants.append(f"{public}(String)")
            constructors.append(f"pub fn {tag.replace('-', '_')}(content: impl Into<String>) -> Self {{ Self::{public}(content.into()) }}")
            payload_expressions[raw_payload] = (public, expression)
    conversions = []
    for target in (model.raw, *config.targets):
        raw_variants = {variant.payload: variant.name for variant in rust.variants(target)}
        arms = []
        for raw_payload in mapping.values():
            public, expression = payload_expressions[raw_payload]
            binding = "value" if expression == "value" else "content"
            arms.append(f"{model.name}::{public}({binding}) => Self::{raw_variants[raw_payload]}({expression})")
        conversions.append(
            f"impl From<{model.name}> for {target} {{\n"
            f"    fn from(value: {model.name}) -> Self {{\n        match value {{\n"
            f"{_indent(','.join(arms), 12)}\n        }}\n    }}\n}}"
        )
    return (
        f"#[derive(Debug, Clone)]\n#[non_exhaustive]\npub enum {model.name} {{\n"
        f"{_indent(','.join(variants))}\n}}\n\n"
        f"impl {model.name} {{\n{_indent(chr(10).join(constructors))}\n}}\n\n"
        + "\n\n".join(conversions)
    )


def _emit_simple_union(model: ModelSpec, rust: RustIndex) -> str:
    assert isinstance(model.config, SimpleUnionPolicy)
    raw_variants = {variant.name: variant for variant in rust.variants(model.raw)}
    variants, arms, reverse_arms, conversions = [], [], [], []
    seen_payloads = set()
    def expand(syntax: RustType) -> RustType:
        return expand(rust.aliases[syntax.spelling]) if syntax.spelling in rust.aliases else syntax

    def adapt_type(syntax: RustType, adapter: str) -> str:
        syntax = expand(syntax)
        if syntax.constructor == "Vec":
            return f"Vec<{adapt_type(syntax.arguments[0], adapter)}>"
        return adapter

    def adapt_value(syntax: RustType, value: str) -> str:
        syntax = expand(syntax)
        if syntax.constructor == "Vec":
            return f"{value}.into_iter().map(|value| {adapt_value(syntax.arguments[0], 'value')}).collect()"
        return f"{value}.into()"

    for raw_name, public_name, adapter in model.config.variants:
        payload = raw_variants[raw_name].payload
        if payload is None:
            raise GenerationError(f"simple union {model.raw}::{raw_name} has no payload")
        raw_syntax = expand(parse_type(payload))
        public_type = (adapt_type(raw_syntax, adapter) if adapter
                       else rust.qualified_type(raw_syntax.spelling))
        raw_value = adapt_value(raw_syntax, "value") if adapter else "value"
        variants.append(f"{public_name}({public_type})")
        arms.append(f"{model.name}::{public_name}(value) => Self::{raw_name}({raw_value})")
        reverse_value = adapt_value(raw_syntax, "value") if adapter else "value"
        reverse_arms.append(f"{model.raw}::{raw_name}(value) => Self::{public_name}({reverse_value})")
        if public_type not in seen_payloads:
            conversions.append(
                f"impl From<{public_type}> for {model.name} {{\n"
                f"    fn from(value: {public_type}) -> Self {{ Self::{public_name}(value) }}\n}}"
            )
            seen_payloads.add(public_type)
        if public_type == "String":
            conversions.append(
                f"impl From<&str> for {model.name} {{\n"
                f"    fn from(value: &str) -> Self {{ Self::{public_name}(value.into()) }}\n}}"
            )
    reverse = (
        f"\n\nimpl From<{model.raw}> for {model.name} {{\n"
        f"    fn from(value: {model.raw}) -> Self {{ match value {{\n"
        f"{_indent(','.join(reverse_arms), 8)}\n    }} }}\n}}"
        if model.config.bidirectional else ""
    )
    return (
        f"#[derive(Debug, Clone)]\n#[non_exhaustive]\npub enum {model.name} {{\n"
        f"{_indent(','.join(variants))}\n}}\n\n"
        + "\n\n".join(conversions) + "\n\n"
        f"impl From<{model.name}> for {model.raw} {{\n"
        f"    fn from(value: {model.name}) -> Self {{ match value {{\n"
        f"{_indent(','.join(arms), 8)}\n    }} }}\n}}" + reverse
    )


def _generic_inner(type_name: str, constructor: str) -> str:
    inner = parse_type(type_name).unary(constructor)
    if inner is None:
        raise GenerationError(f"expected {constructor}, got {type_name}")
    return inner.spelling


def _accessor_type(raw: str, path: list[str], rust: RustIndex) -> str:
    current = raw
    for segment in path:
        if segment == "first":
            current = _generic_inner(current, "Vec")
        elif segment == "optional":
            current = _generic_inner(current, "Option")
        else:
            fields = _field_map(rust, current)
            if segment not in fields:
                raise GenerationError(f"accessor path field {current}.{segment} not found")
            current = fields[segment].type
    return current


def _emit_accessor(name: str, config: Accessor, raw: str, rust: RustIndex) -> str:
    kind, path = config.kind, config.path
    result_type = _accessor_type(raw, path, rust)
    expression = "self.raw"
    if kind in {"ref", "copy"}:
        expression += "".join(f".{field}" for field in path)
        public_type = "str" if kind == "ref" and result_type == "String" else result_type
        marker = "&" if kind == "ref" else ""
        value = f"&{expression}" if kind == "ref" else expression
        return f"pub fn {name}(&self) -> {marker}{public_type} {{ {value} }}"
    if kind in {"optional_ref", "optional_copy"}:
        expression += "".join(f".{field}" for field in path)
        inner = parse_type(result_type).unary("Option")
        if inner is None:
            raise GenerationError(f"accessor {name} expected Option, got {result_type}")
        if kind == "optional_copy":
            return f"pub fn {name}(&self) -> Option<{inner.spelling}> {{ {expression} }}"
        vector = inner.unary("Vec")
        if inner.spelling == "String":
            public_type = "str"
        elif vector:
            public_type = f"[{vector.spelling}]"
        else:
            public_type = inner.spelling
        return f"pub fn {name}(&self) -> Option<&{public_type}> {{ {expression}.as_deref() }}"
    if kind == "iter":
        expression += "".join(f".{field}" for field in path)
        _generic_inner(result_type, "Vec")
        wrapper = config.wrapper
        return (f"pub fn {name}(&self) -> impl ExactSizeIterator<Item = {wrapper}<'_>> {{\n"
                f"    {expression}.iter().map({wrapper}::new)\n}}")
    if kind == "first_string_variant":
        for segment in path:
            expression += (".first()?" if segment == "first" else
                           ".as_ref()?" if segment == "optional" else f".{segment}")
        string_variant = next((variant for variant in rust.variants(result_type)
                               if variant.payload == "String"), None)
        if not string_variant:
            raise GenerationError(f"accessor {name} target {result_type} has no String branch")
        return (f"pub fn {name}(&self) -> Option<&str> {{\n"
                f"    match {expression} {{ {result_type}::{string_variant.name}(value) => Some(value), _ => None }}\n}}")
    raise GenerationError(f"unsupported accessor kind: {kind}")


def _emit_view(model: ModelSpec, rust: RustIndex) -> str:
    assert isinstance(model.config, ViewPolicy)
    accessors = "\n".join(_emit_accessor(name, config, model.raw, rust)
                           for name, config in model.config.accessors)
    borrowed = model.config.borrowed
    if borrowed:
        return (
            f"#[derive(Debug, Clone, Copy)]\npub struct {model.name}<'a> {{ raw: &'a {model.raw} }}\n\n"
            f"impl<'a> {model.name}<'a> {{\n    pub(crate) fn new(raw: &'a {model.raw}) -> Self {{ Self {{ raw }} }}\n"
            f"{_indent(accessors)}\n    pub fn raw(&self) -> &'a {model.raw} {{ self.raw }}\n}}"
        )
    return (
        f"#[derive(Debug, Clone)]\npub struct {model.name} {{ raw: {model.raw} }}\n\n"
        f"impl {model.name} {{\n{_indent(accessors)}\n"
        f"    pub fn raw(&self) -> &{model.raw} {{ &self.raw }}\n"
        f"    pub fn into_raw(self) -> {model.raw} {{ self.raw }}\n}}\n\n"
        f"impl From<{model.raw}> for {model.name} {{ fn from(raw: {model.raw}) -> Self {{ Self {{ raw }} }} }}\n\n"
        f"impl From<{model.name}> for {model.raw} {{ fn from(value: {model.name}) -> Self {{ value.into_raw() }} }}"
    )


def _emit_model(model: ModelSpec, openapi: OpenApiIndex, rust: RustIndex) -> str:
    if isinstance(model.config, UnionPolicy):
        return _emit_union(model, openapi, rust)
    if isinstance(model.config, SimpleUnionPolicy):
        return _emit_simple_union(model, rust)
    if isinstance(model.config, ViewPolicy):
        return _emit_view(model, rust)
    return _emit_wrapper(model, openapi, rust)


def _request_name(resource: ResourceSpec, operation: OperationSpec) -> str:
    return "".join(part.title() for part in operation.name.split("_")) + resource.name + "Request"


def _owned_parameter(type_name: str) -> tuple[str, bool]:
    optional = parse_type(type_name).unary("Option")
    inner = optional.spelling if optional else type_name
    if inner in {"impl AsRef<str>", "&str"}:
        return ("Option<String>" if optional else "String"), True
    if "impl " in inner or "&" in inner:
        raise GenerationError(f"unsupported owned parameter projection: {type_name}")
    return type_name, False


def _direct_parameter(parameter: RustParameter, rust: RustIndex) -> tuple[str, str]:
    name = field_identifier(parameter.name)
    if parameter.type == "impl AsRef<str>":
        return f"{name}: impl AsRef<str>", f"{name}.as_ref()"
    if parameter.type == "&str":
        return f"{name}: &str", name
    owned, _ = _owned_parameter(parameter.type)
    owned = rust.qualified_type(owned)
    return _argument(parameter.name, owned)


def _emit_parameters(resource: ResourceSpec, operation: OperationSpec, rust: RustIndex) -> str:
    if operation.request:
        return ""
    parameters = rust.operation(operation.raw_method).parameters
    if not parameters or not any(_option(parameter.type) for parameter in parameters):
        return ""
    name = _request_name(resource, operation)
    fields, arguments, values, setters = [], [], [], []
    for parameter in parameters:
        owned, _ = _owned_parameter(parameter.type)
        owned = rust.qualified_type(owned)
        fields.append(f"{parameter.name}: {owned}")
        optional = parse_type(owned).unary("Option")
        if optional:
            values.append(f"{parameter.name}: None")
            argument, value = _argument(parameter.name, optional.spelling)
            setters.append(f"#[must_use] pub fn {parameter.name}(mut self, {argument}) -> Self {{ self.{parameter.name} = Some({value}); self }}")
        else:
            argument, value = _argument(parameter.name, owned)
            arguments.append(argument)
            values.append(f"{parameter.name}: {value}")
    derives = "Debug, Clone" + (", Default" if not arguments else "")
    return (f"#[derive({derives})]\npub struct {name} {{ {', '.join(fields)} }}\n"
            f"impl {name} {{ pub fn new({', '.join(arguments)}) -> Self {{ Self {{ {', '.join(values)} }} }}\n"
            + "\n".join(setters) + "\n}\n")


def _operation_arguments(operation: OperationSpec, rust: RustIndex, resource: ResourceSpec) -> tuple[str, str]:
    raw = rust.operation(operation.raw_method)
    if operation.request:
        body = "request.into_raw()"
        if operation.request_overrides:
            assignments = []
            for field, configured in operation.request_overrides:
                if configured is True:
                    value_expression = "Some(true)"
                elif configured is False:
                    value_expression = "Some(false)"
                elif configured is None:
                    value_expression = "None"
                else:
                    raise GenerationError(f"unsupported request override literal for {field}")
                assignments.append(f"raw.{field} = {value_expression};")
            body = f"{{ let mut raw = request.into_raw(); {' '.join(assignments)} raw }}"
        declarations, values = [], []
        for parameter in raw.parameters:
            if parameter.type == operation.request_raw:
                declarations.append(f"request: {operation.request}")
                values.append(body)
                continue
            declaration, value = _direct_parameter(parameter, rust)
            declarations.append(declaration)
            values.append(value)
        return ", ".join(declarations), ", ".join(values)
    if not raw.parameters:
        return "", ""
    if not any(_option(parameter.type) for parameter in raw.parameters):
        declarations, values = [], []
        for parameter in raw.parameters:
            declaration, value = _direct_parameter(parameter, rust)
            declarations.append(declaration)
            values.append(value)
        return ", ".join(declarations), ", ".join(values)
    values = []
    for parameter in raw.parameters:
        _, borrowed = _owned_parameter(parameter.type)
        value = f"request.{parameter.name}"
        if borrowed:
            value += ".as_deref()" if _option(parameter.type) else ".as_str()"
        values.append(value)
    return f"request: {_request_name(resource, operation)}", ", ".join(values)


def _emit_operation(operation: OperationSpec, rust: RustIndex, resource: ResourceSpec) -> str:
    arguments, call = _operation_arguments(operation, rust, resource)
    if operation.stream:
        stream = operation.stream
        item = stream.item
        wrapper = stream.wrapper
        return (
            f"pub async fn {operation.name}(&self, request: {operation.request}) -> Result<{stream.type}, SdkError> {{\n"
            f"    let bytes = self.raw.{operation.raw_method}({call}).await.map_err(SdkError::from)?;\n"
            f"    let events = streaming::json_events::<_, _, {item}>(bytes)\n"
            f"        .map(|event| event.map(|event| {wrapper}::from(event.data)).map_err(Into::into));\n"
            f"    Ok(Box::pin(events))\n}}"
        )
    if operation.empty_response:
        separator = ", " if arguments else ""
        return (
            f"pub async fn {operation.name}(&self{separator}{arguments}) -> Result<(), SdkError> {{\n"
            f"    self.raw.{operation.raw_method}({call}).await.map_err(Into::into)\n}}"
        )
    if operation.binary_response:
        separator = ", " if arguments else ""
        return (
            f"pub async fn {operation.name}(&self{separator}{arguments}) -> Result<BinaryStream, SdkError> {{\n"
            f"    let bytes = self.raw.{operation.raw_method}({call}).await.map_err(SdkError::from)?;\n"
            f"    let chunks = bytes.map(|chunk| chunk.map_err(|error| {{\n"
            f"        let transport = TransportError::from(crate::generated::client::HttpError::Network(error));\n"
            f"        SdkError::from(transport)\n"
            f"    }}));\n"
            f"    Ok(Box::pin(chunks))\n}}"
        )
    if not operation.response:
        raise GenerationError(f"operation {operation.operation_id} needs a response projection")
    raw_parameters = rust.operation(operation.raw_method).parameters
    if not operation.request and raw_parameters and all(_option(parameter.type) for parameter in raw_parameters):
        empty = ", ".join("None::<&str>" if parameter.type == "Option<impl AsRef<str>>" else "None"
                          for parameter in raw_parameters)
        configured = (
            f"pub async fn {operation.name}_with(&self, {arguments}) -> Result<{operation.response}, SdkError> {{\n"
            f"    self.raw.{operation.raw_method}({call}).await.map(Into::into).map_err(Into::into)\n}}"
        )
        return (
            f"pub async fn {operation.name}(&self) -> Result<{operation.response}, SdkError> {{\n"
            f"    self.raw.{operation.raw_method}({empty}).await.map(Into::into).map_err(Into::into)\n}}\n\n"
            + configured
        )
    separator = ", " if arguments else ""
    return (
        f"pub async fn {operation.name}(&self{separator}{arguments}) -> Result<{operation.response}, SdkError> {{\n"
        f"    self.raw.{operation.raw_method}({call}).await.map(Into::into).map_err(Into::into)\n}}"
    )


def _emit_resource(resource: ResourceSpec, rust: RustIndex, resources: tuple[ResourceSpec, ...]) -> str:
    streaming = any(operation.stream for operation in resource.operations)
    binary = any(operation.binary_response for operation in resource.operations)
    imports = "use futures_util::StreamExt;\n" if streaming or binary else ""
    if streaming:
        imports += "use crate::streaming;\nuse crate::generated::types::*;\n"
    operations = "\n\n".join(_emit_operation(operation, rust, resource) for operation in resource.operations)
    requests = "\n".join(_emit_parameters(resource, operation, rust) for operation in resource.operations)
    children = sorted(
        (candidate for candidate in resources
         if len(candidate.path) == len(resource.path) + 1 and candidate.path[:-1] == resource.path),
        key=lambda candidate: candidate.path,
    )
    child_accessors = "\n\n".join(
        f"pub fn {child.path[-1]}(&self) -> {child.name}<'a> {{ {child.name}::new(self.raw) }}"
        for child in children
    )
    members = "\n\n".join(part for part in (child_accessors, operations) if part)
    return GENERATED + imports + """use super::*;
use crate::generated::client::HttpClient;
""" + requests + (
        f"#[derive(Clone, Copy)]\npub struct {resource.name}<'a> {{ raw: &'a HttpClient }}\n\n"
        f"impl<'a> {resource.name}<'a> {{\n"
        f"    pub(crate) fn new(raw: &'a HttpClient) -> Self {{ Self {{ raw }} }}\n"
        f"{_indent(members)}\n}}\n"
    )


def _emit_mod(ir: SdkIr) -> str:
    declarations = "\n".join(
        ("pub mod " if len(resource.path) == 1 else "mod ") + f"{resource.module};"
        for resource in ir.resources
    )
    resources = "\n".join(f"pub use {resource.module}::{resource.name};" for resource in ir.resources)
    exported_types = [model.name for model in ir.models]
    exported_types.extend(operation.stream.type
                          for resource in ir.resources for operation in resource.operations
                          if operation.stream)
    if any(operation.binary_response for resource in ir.resources for operation in resource.operations):
        exported_types.append("BinaryStream")
    models = ", ".join(exported_types)
    accessors = "\n".join(
        f"pub fn {resource.path[0]}(&self) -> {resource.name}<'_> {{ {resource.name}::new(&self.raw) }}"
        for resource in ir.resources if len(resource.path) == 1
    )
    return GENERATED + f"""{declarations}
pub mod error;
mod facade_types;

{resources}
pub use error::{{ApiError, SdkError, TransportError, TransportErrorKind}};
pub use facade_types::{{{models}}};

use crate::generated::client::HttpClient;

#[derive(Clone)]
pub struct {ir.client_name} {{ raw: HttpClient }}

impl {ir.client_name} {{
    pub fn new(api_key: impl Into<String>) -> Self {{
        Self {{ raw: HttpClient::new().with_api_key(api_key) }}
    }}
    #[must_use]
    pub fn with_base_url(mut self, base_url: impl Into<String>) -> Self {{
        self.raw = self.raw.with_base_url(base_url);
        self
    }}
{_indent(accessors)}
    pub fn raw(&self) -> &HttpClient {{ &self.raw }}
}}
"""


def generate(raw: Path, target: Path, manifest_path: Path, openapi_path: Path | None = None,
             taxonomy_path: Path | None = None) -> None:
    if openapi_path is None:
        candidate = manifest_path.parent.parent / "spec" / "openapi.yaml"
        if not candidate.exists():
            raise GenerationError("--openapi is required outside the repository layout")
        openapi_path = candidate
    if taxonomy_path is None:
        candidate = manifest_path.with_name("sdk-taxonomy.json")
        if candidate.exists():
            taxonomy_path = candidate
    manifest = json.loads(manifest_path.read_text())
    openapi, rust = OpenApiIndex.load(openapi_path), RustIndex.load(raw)
    projection_report = None
    if taxonomy_path is not None:
        taxonomy = json.loads(taxonomy_path.read_text())
        raw_coverage = json.loads((raw / "coverage.json").read_text())
        manifest, projection_report = expand_manifest(openapi, manifest, taxonomy, raw_coverage)
    ir = build_ir(openapi, rust, manifest)
    target.mkdir(parents=True, exist_ok=True)

    model_source = GENERATED + "use std::pin::Pin;\nuse futures_util::Stream;\nuse super::SdkError;\nuse crate::generated::types::*;\n\n"
    model_source += "\n\n".join(_emit_model(model, openapi, rust) for model in ir.models)
    aliases = []
    if any(operation.binary_response for resource in ir.resources for operation in resource.operations):
        aliases.append(
            "pub type BinaryStream = Pin<Box<dyn Stream<Item = Result<bytes::Bytes, SdkError>> + Send + 'static>>;"
        )
    for resource in ir.resources:
        for operation in resource.operations:
            if operation.stream:
                stream = operation.stream
                aliases.append(
                    f"pub type {stream.type} = Pin<Box<dyn Stream<Item = Result<{stream.wrapper}, SdkError>> + Send + 'static>>;"
                )
    if aliases:
        model_source += "\n\n" + "\n".join(aliases) + "\n"
    files = {"facade_types.rs": model_source, "mod.rs": _emit_mod(ir)}
    for resource in ir.resources:
        filename = f"{resource.module}.rs"
        if filename in files or filename == "error.rs":
            raise GenerationError(f"resource collides with reserved output {filename}")
        files[filename] = _emit_resource(resource, rust, ir.resources)
    try:
        surface = public_surface(files)
    except ValueError as error:
        raise GenerationError(str(error)) from error
    for filename, source in files.items():
        (target / filename).write_text(source)
    (target / "api-surface.json").write_text(json.dumps(surface, indent=2) + "\n")
    coverage = {
        "schema_version": 2,
        "inventory": coverage_inventory(openapi, rust, ir),
        "resources": {resource.module: {"operations": [operation.operation_id for operation in resource.operations]}
                      for resource in ir.resources},
        "models": {model.name: {"raw": model.raw, "fields": sorted(field.name for field in rust.fields(model.raw)) if model.raw in rust.structs else []}
                   for model in ir.models},
    }
    if projection_report is not None:
        coverage["automatic_projection"] = projection_report
    (target / "coverage.json").write_text(json.dumps(coverage, indent=2) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("raw", type=Path)
    parser.add_argument("target", type=Path)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--openapi", type=Path)
    parser.add_argument("--taxonomy", type=Path)
    args = parser.parse_args()
    generate(args.raw, args.target, args.manifest, args.openapi, args.taxonomy)


if __name__ == "__main__":
    main()
