"""Compile OpenAPI plus a semantic overlay into a resource-oriented Rust SDK.

OpenAPI owns the wire contract. The overlay only supplies stable public names
and deliberate conveniences that HTTP cannot express. Generated Rust bindings
are reconciled through a real tree-sitter syntax tree, never regular expressions.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import json
from pathlib import Path
from typing import Any, Iterable

from ruamel.yaml import YAML
from tree_sitter import Language, Node, Parser
import tree_sitter_rust


GENERATED = "// @generated by codegen/sdk_facade.py; do not edit by hand.\n"


class GenerationError(ValueError):
    """A source contract cannot be projected without semantic review."""


def _text(source: bytes, node: Node | None) -> str:
    if node is None:
        raise GenerationError("missing Rust AST node")
    return source[node.start_byte : node.end_byte].decode()


def _children(node: Node | None, kind: str) -> list[Node]:
    return [child for child in node.named_children if child.type == kind] if node else []


@dataclass(frozen=True)
class RustField:
    name: str
    type: str


@dataclass(frozen=True)
class RustVariant:
    name: str
    payload: str | None


@dataclass(frozen=True)
class RustParameter:
    name: str
    type: str


@dataclass(frozen=True)
class RustOperation:
    name: str
    parameters: tuple[RustParameter, ...]
    return_type: str
    success_type: str


class RustIndex:
    """Typed symbol table built from openapi-to-rust output."""

    def __init__(self, types_source: bytes, client_source: bytes):
        parser = Parser(Language(tree_sitter_rust.language()))
        self.structs: dict[str, tuple[RustField, ...]] = {}
        self.enums: dict[str, tuple[RustVariant, ...]] = {}
        self.operations: dict[str, RustOperation] = {}
        self._index_types(types_source, parser.parse(types_source).root_node)
        self._index_client(client_source, parser.parse(client_source).root_node)

    @classmethod
    def load(cls, raw: Path) -> "RustIndex":
        return cls((raw / "types.rs").read_bytes(), (raw / "client.rs").read_bytes())

    def _index_types(self, source: bytes, root: Node) -> None:
        for item in root.named_children:
            if item.type == "struct_item":
                name = _text(source, item.child_by_field_name("name"))
                fields = []
                for field in _children(item.child_by_field_name("body"), "field_declaration"):
                    if not _children(field, "visibility_modifier"):
                        continue
                    fields.append(RustField(
                        _text(source, field.child_by_field_name("name")),
                        _text(source, field.child_by_field_name("type")),
                    ))
                self.structs[name] = tuple(fields)
            elif item.type == "enum_item":
                name = _text(source, item.child_by_field_name("name"))
                variants = []
                for variant in _children(item.child_by_field_name("body"), "enum_variant"):
                    variant_name = _text(source, variant.child_by_field_name("name"))
                    body = variant.child_by_field_name("body")
                    payload = None
                    if body and body.type == "ordered_field_declaration_list":
                        payload_nodes = [child for child in body.named_children]
                        if len(payload_nodes) != 1:
                            raise GenerationError(f"raw enum {name}::{variant_name} is not unary")
                        payload = _text(source, payload_nodes[0])
                    variants.append(RustVariant(variant_name, payload))
                self.enums[name] = tuple(variants)

    def _index_client(self, source: bytes, root: Node) -> None:
        for item in root.named_children:
            if item.type != "impl_item":
                continue
            if _text(source, item.child_by_field_name("type")) != "HttpClient":
                continue
            for function in _children(item.child_by_field_name("body"), "function_item"):
                name = _text(source, function.child_by_field_name("name"))
                parameters = []
                for parameter in (function.child_by_field_name("parameters") or ()).named_children:
                    if parameter.type != "parameter":
                        continue
                    identifier = next((child for child in parameter.named_children
                                       if child.type in {"identifier", "field_identifier"}), None)
                    parameters.append(RustParameter(
                        _text(source, identifier),
                        _text(source, parameter.child_by_field_name("type")),
                    ))
                return_node = function.child_by_field_name("return_type")
                success_type = ""
                if return_node and return_node.type == "generic_type":
                    arguments = next((child for child in return_node.named_children
                                      if child.type == "type_arguments"), None)
                    if arguments and arguments.named_children:
                        success_type = _text(source, arguments.named_children[0])
                self.operations[name] = RustOperation(
                    name, tuple(parameters), _text(source, return_node), success_type,
                )

    def fields(self, name: str) -> tuple[RustField, ...]:
        try:
            return self.structs[name]
        except KeyError as error:
            raise GenerationError(f"raw Rust struct not found: {name}") from error

    def variants(self, name: str) -> tuple[RustVariant, ...]:
        try:
            return self.enums[name]
        except KeyError as error:
            raise GenerationError(f"raw Rust enum not found: {name}") from error

    def operation(self, name: str) -> RustOperation:
        try:
            return self.operations[name]
        except KeyError as error:
            raise GenerationError(f"raw Rust operation not found: {name}") from error


def _ref_name(schema: dict[str, Any]) -> str | None:
    ref = schema.get("$ref")
    return ref.rsplit("/", 1)[-1] if isinstance(ref, str) else None


def _success_schema(operation: dict[str, Any], media: str = "application/json") -> dict[str, Any]:
    for status, response in sorted(operation.get("responses", {}).items()):
        if str(status).startswith("2") and media in response.get("content", {}):
            return response["content"][media].get("schema", {})
    raise GenerationError(f"operation has no successful {media} response")


class OpenApiIndex:
    """Semantic source for schemas, HTTP operations and discriminators."""

    def __init__(self, document: dict[str, Any]):
        self.document = document
        self.schemas = document.get("components", {}).get("schemas", {})
        self.operations: dict[str, dict[str, Any]] = {}
        for path, path_item in document.get("paths", {}).items():
            for method in ("get", "put", "post", "delete", "patch", "head", "options"):
                operation = path_item.get(method)
                if not operation or "operationId" not in operation:
                    continue
                combined = dict(operation)
                combined["parameters"] = path_item.get("parameters", []) + operation.get("parameters", [])
                combined["x-sdk-path"] = path
                combined["x-sdk-method"] = method
                self.operations[operation["operationId"]] = combined

    @classmethod
    def load(cls, path: Path) -> "OpenApiIndex":
        return cls(YAML(typ="safe").load(path.read_text()))

    def schema(self, name: str) -> dict[str, Any]:
        try:
            return self.schemas[name]
        except KeyError as error:
            raise GenerationError(f"OpenAPI schema not found: {name}") from error

    def operation(self, operation_id: str) -> dict[str, Any]:
        try:
            return self.operations[operation_id]
        except KeyError as error:
            raise GenerationError(f"OpenAPI operation not found: {operation_id}") from error

    def request_schema(self, operation_id: str) -> str | None:
        request = self.operation(operation_id).get("requestBody", {})
        schema = request.get("content", {}).get("application/json", {}).get("schema", {})
        return _ref_name(schema)

    def response_schema(self, operation_id: str) -> str | None:
        return _ref_name(_success_schema(self.operation(operation_id)))

    def union(self, root: str, path: Iterable[str]) -> tuple[str, dict[str, str]]:
        schema = self.schema(root)
        for segment in path:
            schema = schema.get("items", {}) if segment == "items" else schema.get("properties", {}).get(segment, {})
            non_null = [part for part in schema.get("anyOf", []) if part.get("type") != "null"]
            if len(non_null) == 1:
                schema = non_null[0]
        discriminator = schema.get("discriminator", {})
        mapping = {tag: ref.rsplit("/", 1)[-1]
                   for tag, ref in discriminator.get("mapping", {}).items()}
        if not mapping:
            # OpenAPI authors often omit an explicit discriminator even though
            # every object branch carries the same const-valued tag. Infer the
            # semantic union exactly as modern SDK generators do.
            branches = schema.get("oneOf", []) or schema.get("anyOf", [])
            referenced = [_ref_name(branch) for branch in branches]
            if referenced and all(referenced):
                candidates: dict[str, dict[str, str]] = {}
                for name in referenced:
                    properties = self.schema(name).get("properties", {})
                    for property_name, property_schema in properties.items():
                        if "const" in property_schema:
                            candidates.setdefault(property_name, {})[str(property_schema["const"])] = name
                complete = [(name, values) for name, values in candidates.items()
                            if len(values) == len(referenced)]
                if len(complete) == 1:
                    property_name, mapping = complete[0]
                    discriminator = {"propertyName": property_name}
        if not mapping:
            raise GenerationError(f"{root}.{'.'.join(path)} is not a discriminated union")
        return discriminator["propertyName"], mapping


@dataclass(frozen=True)
class ModelSpec:
    name: str
    raw: str
    config: dict[str, Any]


@dataclass(frozen=True)
class OperationSpec:
    name: str
    operation_id: str
    raw_method: str
    request: str | None
    response: str | None
    request_overrides: dict[str, Any]
    stream: dict[str, Any] | None


@dataclass(frozen=True)
class ResourceSpec:
    module: str
    name: str
    operations: tuple[OperationSpec, ...]


@dataclass(frozen=True)
class SdkIr:
    client_name: str
    models: tuple[ModelSpec, ...]
    resources: tuple[ResourceSpec, ...]


def _validate_keys(value: dict[str, Any], allowed: set[str], context: str) -> None:
    unknown = sorted(set(value) - allowed)
    if unknown:
        raise GenerationError(f"unknown {context} keys: {', '.join(unknown)}")


def build_ir(openapi: OpenApiIndex, rust: RustIndex, manifest: dict[str, Any]) -> SdkIr:
    _validate_keys(manifest, {"schema_version", "client", "models", "resources"}, "manifest")
    if manifest.get("schema_version") != 2:
        raise GenerationError("unsupported SDK semantic manifest version")
    models = []
    for name, config in manifest.get("models", {}).items():
        _validate_keys(config, {"raw", "constructor", "exclude", "adapters", "union", "union_factory", "accessors", "borrowed"}, f"model {name}")
        raw = config.get("raw", name)
        if "union" in config:
            union = config["union"]
            _validate_keys(union, {"root", "path", "payload"}, f"union {name}")
            _, mapping = openapi.union(union["root"], union["path"])
            variants = {variant.payload for variant in rust.variants(raw)}
            missing = sorted(set(mapping.values()) - variants)
            if missing:
                raise GenerationError(f"raw union {raw} misses branches: {', '.join(missing)}")
        else:
            rust.fields(raw)
            schema = openapi.schema(raw)
            if "constructor" in config or "union_factory" in config:
                wire_fields = set(schema.get("properties", {}))
                raw_fields = {field.name.removeprefix("r#") for field in rust.fields(raw)}
                if wire_fields != raw_fields:
                    missing = sorted(wire_fields - raw_fields)
                    extra = sorted(raw_fields - wire_fields)
                    raise GenerationError(
                        f"OpenAPI/raw field drift for {raw}: missing={missing}, extra={extra}"
                    )
                covered = set(config.get("constructor", [])) | set(config.get("exclude", []))
                factory = config.get("union_factory", {})
                covered |= {factory.get("field"), *factory.get("leading", [])}
                uncovered_required = set(schema.get("required", [])) - covered
                if uncovered_required:
                    raise GenerationError(
                        f"required fields need constructor policy for {raw}: {sorted(uncovered_required)}"
                    )
        models.append(ModelSpec(name, raw, config))
    model_names = {model.name for model in models}
    resources = []
    for module, config in manifest.get("resources", {}).items():
        _validate_keys(config, {"name", "operations"}, f"resource {module}")
        operations = []
        for public_name, item in config.get("operations", {}).items():
            _validate_keys(item, {"operation_id", "raw_method", "request", "response", "request_overrides", "stream"}, f"operation {module}.{public_name}")
            operation_id = item["operation_id"]
            raw_method = item.get("raw_method", operation_id)
            raw_operation = rust.operation(raw_method)
            wire_operation = openapi.operation(operation_id)
            request, response = item.get("request"), item.get("response")
            for referenced in (request, response):
                if referenced and referenced not in model_names:
                    raise GenerationError(f"unknown facade model {referenced}")
            if request:
                model = next(model for model in models if model.name == request)
                if openapi.request_schema(operation_id) != model.raw:
                    raise GenerationError(f"OpenAPI request drift for {operation_id}")
                if not raw_operation.parameters or raw_operation.parameters[0].type != model.raw:
                    raise GenerationError(f"raw signature drift for {raw_method}")
                request_fields = _field_map(rust, model.raw)
                unknown_overrides = set(item.get("request_overrides", {})) - set(request_fields)
                if unknown_overrides:
                    raise GenerationError(f"unknown request overrides for {raw_method}: {sorted(unknown_overrides)}")
            raw_parameters = raw_operation.parameters[1:] if request else raw_operation.parameters
            wire_parameter_names = tuple(parameter["name"].replace("-", "_")
                                         for parameter in wire_operation.get("parameters", []))
            if tuple(parameter.name for parameter in raw_parameters) != wire_parameter_names:
                raise GenerationError(f"OpenAPI/raw parameter drift for {raw_method}")
            if response and not item.get("stream"):
                model = next(model for model in models if model.name == response)
                if openapi.response_schema(operation_id) != model.raw:
                    raise GenerationError(f"OpenAPI response drift for {operation_id}")
                if raw_operation.success_type != model.raw:
                    raise GenerationError(f"raw response drift for {raw_method}")
            operations.append(OperationSpec(public_name, operation_id, raw_method, request, response,
                                            item.get("request_overrides", {}), item.get("stream")))
        resources.append(ResourceSpec(module, config["name"], tuple(operations)))
    return SdkIr(manifest.get("client", {}).get("name", "Client"), tuple(models), tuple(resources))


def _option(type_name: str) -> tuple[str, bool] | None:
    if not (type_name.startswith("Option<") and type_name.endswith(">")):
        return None
    inner = type_name[7:-1]
    if inner.startswith("Option<") and inner.endswith(">"):
        return inner[7:-1], True
    return inner, False


def _argument(name: str, type_name: str) -> tuple[str, str]:
    return ((f"{name}: impl Into<String>", f"{name}.into()")
            if type_name == "String" else (f"{name}: {type_name}", name))


def _indent(value: str, spaces: int = 4) -> str:
    prefix = " " * spaces
    return "\n".join(prefix + line if line else line for line in value.splitlines())


def _field_map(rust: RustIndex, raw: str) -> dict[str, RustField]:
    return {field.name.removeprefix("r#"): field for field in rust.fields(raw)}


def _wrap(type_name: str, value: str) -> str:
    optional = _option(type_name)
    if optional is None:
        return value
    return f"Some(Some({value}))" if optional[1] else f"Some({value})"


def _emit_setters(model: ModelSpec, rust: RustIndex) -> str:
    excluded = set(model.config.get("exclude", [])) | set(model.config.get("constructor", []))
    methods = []
    for field in rust.fields(model.raw):
        name = field.name.removeprefix("r#")
        if name in excluded:
            continue
        optional = _option(field.type)
        if optional is None:
            raise GenerationError(
                f"new required field {model.raw}.{name}; constructor policy needs semantic review"
            )
        inner, nullable = optional
        argument, value = _argument(name, inner)
        methods.append(
            f"#[must_use]\npub fn {name}(mut self, {argument}) -> Self {{\n"
            f"    self.raw.{field.name} = {_wrap(field.type, value)};\n    self\n}}"
        )
        if nullable:
            methods.append(
                f"#[must_use]\npub fn {name}_null(mut self) -> Self {{\n"
                f"    self.raw.{field.name} = Some(None);\n    self\n}}"
            )
    return "\n\n".join(methods)


def _constructor_arg(name: str, field: RustField, adapter: str | None) -> tuple[str, str]:
    if adapter:
        if not (field.type.startswith("Vec<") and field.type.endswith(">")):
            raise GenerationError(f"adapter for {name} requires a Vec raw field")
        return (f"{name}: impl IntoIterator<Item = {adapter}>",
                f"{name}.into_iter().map(Into::into).collect()")
    optional = _option(field.type)
    effective = optional[0] if optional else field.type
    argument, value = _argument(name, effective)
    return argument, _wrap(field.type, value)


def _struct_literal(raw: str, fields: dict[str, RustField], values: dict[str, str]) -> str:
    assignments = []
    for name, field in fields.items():
        if name in values:
            value = values[name]
            assignments.append(field.name if value == field.name and not field.name.startswith("r#")
                               else f"{field.name}: {value}")
        elif _option(field.type):
            assignments.append(f"{field.name}: None")
        else:
            raise GenerationError(f"required raw field {raw}.{name} has no value")
    return f"{raw} {{ {', '.join(assignments)} }}"


def _factory_value(type_name: str, argument: str, rust: RustIndex) -> tuple[str, str]:
    optional = _option(type_name)
    core = optional[0] if optional else type_name
    if core == "String":
        declaration, value = f"{argument}: impl Into<String>", f"{argument}.into()"
    elif core in rust.enums:
        string = next((variant for variant in rust.variants(core) if variant.payload == "String"), None)
        if not string:
            declaration, value = f"{argument}: {core}", argument
        else:
            declaration, value = f"{argument}: impl Into<String>", f"{core}::{string.name}({argument}.into())"
    else:
        declaration, value = f"{argument}: {core}", argument
    return declaration, _wrap(type_name, value)


def _emit_union_factories(model: ModelSpec, openapi: OpenApiIndex, rust: RustIndex) -> str:
    config = model.config["union_factory"]
    _validate_keys(config, {"field", "leading", "rename"}, f"union factory {model.name}")
    field_name = config["field"]
    fields = _field_map(rust, model.raw)
    union_type = _option(fields[field_name].type)
    raw_union = union_type[0] if union_type else fields[field_name].type
    discriminator, mapping = openapi.union(model.raw, [field_name])
    raw_variants = {variant.payload: variant.name for variant in rust.variants(raw_union)}
    methods = []
    for tag, payload in sorted(mapping.items()):
        payload_schema = openapi.schema(payload)
        candidates = [name for name in payload_schema.get("required", []) if name != discriminator]
        if len(candidates) != 1:
            raise GenerationError(f"factory branch {payload} needs one non-discriminator input, got {candidates}")
        input_name = candidates[0]
        payload_fields = _field_map(rust, payload)
        if input_name not in payload_fields:
            raise GenerationError(f"raw field {payload}.{input_name} not found")
        public_name = config.get("rename", {}).get(tag, tag.replace("-", "_"))
        arguments, outer_values = [], {}
        for leading in config.get("leading", []):
            declaration, value = _factory_value(fields[leading].type, leading, rust)
            arguments.append(declaration)
            outer_values[leading] = value
        declaration, value = _factory_value(payload_fields[input_name].type, input_name, rust)
        arguments.append(declaration)
        payload_value = _struct_literal(payload, payload_fields, {input_name: value})
        outer_values[field_name] = _wrap(fields[field_name].type, f"{raw_union}::{raw_variants[payload]}({payload_value})")
        raw_value = _struct_literal(model.raw, fields, outer_values)
        methods.append(f"pub fn {public_name}({', '.join(arguments)}) -> Self {{ Self {{ raw: {raw_value} }} }}")
    return "\n\n".join(methods)


def _emit_wrapper(model: ModelSpec, openapi: OpenApiIndex, rust: RustIndex) -> str:
    fields = _field_map(rust, model.raw)
    methods = []
    constructor = model.config.get("constructor", [])
    if constructor:
        arguments, values = [], []
        for name in constructor:
            if name not in fields:
                raise GenerationError(f"constructor field {model.raw}.{name} not found")
            argument, value = _constructor_arg(name, fields[name], model.config.get("adapters", {}).get(name))
            arguments.append(argument)
            values.append(value)
        raw_values = {name: value for name, value in zip(constructor, values)}
        methods.append(f"pub fn new({', '.join(arguments)}) -> Self {{\n"
                       f"    Self {{ raw: {_struct_literal(model.raw, fields, raw_values)} }}\n}}")
    if "union_factory" in model.config:
        methods.append(_emit_union_factories(model, openapi, rust))
    setters = _emit_setters(model, rust)
    if setters:
        methods.append(setters)
    methods.extend((
        f"pub fn from_raw(raw: {model.raw}) -> Self {{ Self {{ raw }} }}",
        f"pub fn as_raw(&self) -> &{model.raw} {{ &self.raw }}",
        f"pub fn into_raw(self) -> {model.raw} {{ self.raw }}",
    ))
    return (
        f"#[derive(Debug, Clone)]\npub struct {model.name} {{ raw: {model.raw} }}\n\n"
        f"impl {model.name} {{\n{_indent(chr(10).join(methods))}\n}}\n\n"
        f"impl From<{model.raw}> for {model.name} {{\n"
        f"    fn from(raw: {model.raw}) -> Self {{ Self {{ raw }} }}\n}}"
    )


def _public_variant(tag: str) -> str:
    return "".join(part[:1].upper() + part[1:]
                   for part in tag.replace("-", "_").split("_") if part)


def _string_payload(raw_payload: str, payload_field: str, rust: RustIndex) -> str:
    assignments = []
    for field in rust.fields(raw_payload):
        name = field.name.removeprefix("r#")
        if name == payload_field:
            optional = _option(field.type)
            core = optional[0] if optional else field.type
            if core == "String":
                value = "content"
            else:
                string_variant = next((variant for variant in rust.variants(core)
                                       if variant.payload == "String"), None)
                if not string_variant:
                    raise GenerationError(f"{raw_payload}.{payload_field} has no String branch")
                value = f"{core}::{string_variant.name}(content)"
            assignments.append(f"{field.name}: {_wrap(field.type, value)}")
        elif _option(field.type):
            assignments.append(f"{field.name}: None")
        else:
            raise GenerationError(f"{raw_payload} also requires {name}")
    return f"{raw_payload} {{ {', '.join(assignments)} }}"


def _emit_union(model: ModelSpec, openapi: OpenApiIndex, rust: RustIndex) -> str:
    config = model.config["union"]
    _, mapping = openapi.union(config["root"], config["path"])
    raw_variants = {variant.payload: variant.name for variant in rust.variants(model.raw)}
    variants, constructors, arms = [], [], []
    for tag, raw_payload in sorted(mapping.items()):
        public = _public_variant(tag)
        raw_variant = raw_variants[raw_payload]
        try:
            expression = _string_payload(raw_payload, config["payload"], rust)
        except GenerationError:
            variants.append(f"{public}({raw_payload})")
            constructors.append(f"pub fn {tag.replace('-', '_')}(value: {raw_payload}) -> Self {{ Self::{public}(value) }}")
            arms.append(f"{model.name}::{public}(value) => Self::{raw_variant}(value)")
        else:
            variants.append(f"{public}(String)")
            constructors.append(f"pub fn {tag.replace('-', '_')}(content: impl Into<String>) -> Self {{ Self::{public}(content.into()) }}")
            arms.append(f"{model.name}::{public}(content) => Self::{raw_variant}({expression})")
    return (
        f"#[derive(Debug, Clone)]\n#[non_exhaustive]\npub enum {model.name} {{\n"
        f"{_indent(','.join(variants))}\n}}\n\n"
        f"impl {model.name} {{\n{_indent(chr(10).join(constructors))}\n}}\n\n"
        f"impl From<{model.name}> for {model.raw} {{\n"
        f"    fn from(value: {model.name}) -> Self {{\n        match value {{\n"
        f"{_indent(','.join(arms), 12)}\n        }}\n    }}\n}}"
    )


def _generic_inner(type_name: str, constructor: str) -> str:
    prefix = constructor + "<"
    if not (type_name.startswith(prefix) and type_name.endswith(">")):
        raise GenerationError(f"expected {constructor}, got {type_name}")
    return type_name[len(prefix):-1]


def _accessor_type(raw: str, path: list[str], rust: RustIndex) -> str:
    current = raw
    for segment in path:
        if segment == "first":
            current = _generic_inner(current, "Vec")
        elif segment == "optional":
            current = _generic_inner(current, "Option")
        else:
            fields = _field_map(rust, current)
            if segment not in fields:
                raise GenerationError(f"accessor path field {current}.{segment} not found")
            current = fields[segment].type
    return current


def _emit_accessor(name: str, config: dict[str, Any], raw: str, rust: RustIndex) -> str:
    _validate_keys(config, {"kind", "path", "wrapper"}, f"accessor {name}")
    kind, path = config["kind"], config["path"]
    result_type = _accessor_type(raw, path, rust)
    expression = "self.raw"
    if kind in {"ref", "copy"}:
        expression += "".join(f".{field}" for field in path)
        public_type = "str" if kind == "ref" and result_type == "String" else result_type
        marker = "&" if kind == "ref" else ""
        value = f"&{expression}" if kind == "ref" else expression
        return f"pub fn {name}(&self) -> {marker}{public_type} {{ {value} }}"
    if kind == "iter":
        expression += "".join(f".{field}" for field in path)
        _generic_inner(result_type, "Vec")
        wrapper = config["wrapper"]
        return (f"pub fn {name}(&self) -> impl ExactSizeIterator<Item = {wrapper}<'_>> {{\n"
                f"    {expression}.iter().map({wrapper}::new)\n}}")
    if kind == "first_string_variant":
        for segment in path:
            expression += (".first()?" if segment == "first" else
                           ".as_ref()?" if segment == "optional" else f".{segment}")
        string_variant = next((variant for variant in rust.variants(result_type)
                               if variant.payload == "String"), None)
        if not string_variant:
            raise GenerationError(f"accessor {name} target {result_type} has no String branch")
        return (f"pub fn {name}(&self) -> Option<&str> {{\n"
                f"    match {expression} {{ {result_type}::{string_variant.name}(value) => Some(value), _ => None }}\n}}")
    raise GenerationError(f"unsupported accessor kind: {kind}")


def _emit_view(model: ModelSpec, rust: RustIndex) -> str:
    accessors = "\n".join(_emit_accessor(name, config, model.raw, rust)
                           for name, config in model.config.get("accessors", {}).items())
    borrowed = model.config.get("borrowed", True)
    if borrowed:
        return (
            f"#[derive(Debug, Clone, Copy)]\npub struct {model.name}<'a> {{ raw: &'a {model.raw} }}\n\n"
            f"impl<'a> {model.name}<'a> {{\n    pub(crate) fn new(raw: &'a {model.raw}) -> Self {{ Self {{ raw }} }}\n"
            f"{_indent(accessors)}\n    pub fn raw(&self) -> &'a {model.raw} {{ self.raw }}\n}}"
        )
    return (
        f"#[derive(Debug, Clone)]\npub struct {model.name} {{ raw: {model.raw} }}\n\n"
        f"impl {model.name} {{\n{_indent(accessors)}\n"
        f"    pub fn raw(&self) -> &{model.raw} {{ &self.raw }}\n"
        f"    pub fn into_raw(self) -> {model.raw} {{ self.raw }}\n}}\n\n"
        f"impl From<{model.raw}> for {model.name} {{ fn from(raw: {model.raw}) -> Self {{ Self {{ raw }} }} }}"
    )


def _emit_model(model: ModelSpec, openapi: OpenApiIndex, rust: RustIndex) -> str:
    if "union" in model.config:
        return _emit_union(model, openapi, rust)
    if "accessors" in model.config and "constructor" not in model.config:
        return _emit_view(model, rust)
    return _emit_wrapper(model, openapi, rust)


def _operation_arguments(operation: OperationSpec, rust: RustIndex) -> tuple[str, str]:
    raw = rust.operation(operation.raw_method)
    if operation.request:
        value = "request.into_raw()"
        if operation.request_overrides:
            assignments = []
            for field, configured in operation.request_overrides.items():
                if configured is True:
                    value_expression = "Some(true)"
                elif configured is False:
                    value_expression = "Some(false)"
                elif configured is None:
                    value_expression = "None"
                else:
                    raise GenerationError(f"unsupported request override literal for {field}")
                assignments.append(f"raw.{field} = {value_expression};")
            value = f"{{ let mut raw = request.into_raw(); {' '.join(assignments)} raw }}"
        return f"request: {operation.request}", value
    arguments = [f"{parameter.name}: {_public_parameter_type(parameter.type)}" for parameter in raw.parameters]
    values = [parameter.name for parameter in raw.parameters]
    return ", ".join(arguments), ", ".join(values)


def _public_parameter_type(raw_type: str) -> str:
    # Language policy: borrowed strings make `None` inferable and avoid exposing
    # `impl Trait` nested in Option at every resource call.
    return "Option<&str>" if raw_type == "Option<impl AsRef<str>>" else raw_type


def _emit_operation(operation: OperationSpec, rust: RustIndex) -> str:
    arguments, call = _operation_arguments(operation, rust)
    if operation.stream:
        stream = operation.stream
        _validate_keys(stream, {"item", "wrapper", "type"}, f"stream {operation.name}")
        item = stream["item"]
        wrapper = stream.get("wrapper", item)
        return (
            f"pub async fn {operation.name}(&self, request: {operation.request}) -> Result<{stream['type']}, SdkError> {{\n"
            f"    let bytes = self.raw.{operation.raw_method}({call}).await.map_err(SdkError::from)?;\n"
            f"    let events = streaming::json_events::<_, _, {item}>(bytes)\n"
            f"        .map(|event| event.map(|event| {wrapper}::from(event.data)).map_err(Into::into));\n"
            f"    Ok(Box::pin(events))\n}}"
        )
    if not operation.response:
        raise GenerationError(f"operation {operation.operation_id} needs a response projection")
    raw_parameters = rust.operation(operation.raw_method).parameters
    if not operation.request and raw_parameters and all(_option(parameter.type) for parameter in raw_parameters):
        empty = ", ".join("None::<&str>" if parameter.type == "Option<impl AsRef<str>>" else "None"
                          for parameter in raw_parameters)
        configured = (
            f"pub async fn {operation.name}_with(&self, {arguments}) -> Result<{operation.response}, SdkError> {{\n"
            f"    self.raw.{operation.raw_method}({call}).await.map(Into::into).map_err(Into::into)\n}}"
        )
        return (
            f"pub async fn {operation.name}(&self) -> Result<{operation.response}, SdkError> {{\n"
            f"    self.raw.{operation.raw_method}({empty}).await.map(Into::into).map_err(Into::into)\n}}\n\n"
            + configured
        )
    separator = ", " if arguments else ""
    return (
        f"pub async fn {operation.name}(&self{separator}{arguments}) -> Result<{operation.response}, SdkError> {{\n"
        f"    self.raw.{operation.raw_method}({call}).await.map(Into::into).map_err(Into::into)\n}}"
    )


def _emit_resource(resource: ResourceSpec, rust: RustIndex) -> str:
    streaming = any(operation.stream for operation in resource.operations)
    imports = ("use futures_util::StreamExt;\nuse crate::streaming;\n"
               "use crate::generated::types::*;\n" if streaming else "")
    operations = "\n\n".join(_emit_operation(operation, rust) for operation in resource.operations)
    return GENERATED + imports + """use super::*;
use crate::generated::client::HttpClient;
""" + (
        f"#[derive(Clone, Copy)]\npub struct {resource.name}<'a> {{ raw: &'a HttpClient }}\n\n"
        f"impl<'a> {resource.name}<'a> {{\n"
        f"    pub(crate) fn new(raw: &'a HttpClient) -> Self {{ Self {{ raw }} }}\n\n"
        f"{_indent(operations)}\n}}\n"
    )


def _emit_mod(ir: SdkIr) -> str:
    declarations = "\n".join(f"pub mod {resource.module};" for resource in ir.resources)
    resources = "\n".join(f"pub use {resource.module}::{resource.name};" for resource in ir.resources)
    exported_types = [model.name for model in ir.models]
    exported_types.extend(operation.stream["type"]
                          for resource in ir.resources for operation in resource.operations
                          if operation.stream)
    models = ", ".join(exported_types)
    accessors = "\n".join(
        f"pub fn {resource.module}(&self) -> {resource.name}<'_> {{ {resource.name}::new(&self.raw) }}"
        for resource in ir.resources
    )
    return GENERATED + f"""{declarations}
pub mod error;
mod facade_types;

{resources}
pub use error::{{ApiError, SdkError, TransportError, TransportErrorKind}};
pub use facade_types::{{{models}}};

use crate::generated::client::HttpClient;

#[derive(Clone)]
pub struct {ir.client_name} {{ raw: HttpClient }}

impl {ir.client_name} {{
    pub fn new(api_key: impl Into<String>) -> Self {{
        Self {{ raw: HttpClient::new().with_api_key(api_key) }}
    }}
    #[must_use]
    pub fn with_base_url(mut self, base_url: impl Into<String>) -> Self {{
        self.raw = self.raw.with_base_url(base_url);
        self
    }}
{_indent(accessors)}
    pub fn raw(&self) -> &HttpClient {{ &self.raw }}
}}
"""


def generate(raw: Path, target: Path, manifest_path: Path, openapi_path: Path | None = None) -> None:
    if openapi_path is None:
        candidate = manifest_path.parent.parent / "spec" / "openapi.yaml"
        if not candidate.exists():
            raise GenerationError("--openapi is required outside the repository layout")
        openapi_path = candidate
    manifest = json.loads(manifest_path.read_text())
    openapi, rust = OpenApiIndex.load(openapi_path), RustIndex.load(raw)
    ir = build_ir(openapi, rust, manifest)
    target.mkdir(parents=True, exist_ok=True)

    model_source = GENERATED + "use std::pin::Pin;\nuse futures_util::Stream;\nuse super::SdkError;\nuse crate::generated::types::*;\n\n"
    model_source += "\n\n".join(_emit_model(model, openapi, rust) for model in ir.models)
    aliases = []
    for resource in ir.resources:
        for operation in resource.operations:
            if operation.stream:
                stream = operation.stream
                aliases.append(
                    f"pub type {stream['type']} = Pin<Box<dyn Stream<Item = Result<{stream.get('wrapper', stream['item'])}, SdkError>> + Send + 'static>>;"
                )
    if aliases:
        model_source += "\n\n" + "\n".join(aliases) + "\n"
    (target / "facade_types.rs").write_text(model_source)
    for resource in ir.resources:
        (target / f"{resource.module}.rs").write_text(_emit_resource(resource, rust))
    (target / "mod.rs").write_text(_emit_mod(ir))
    coverage = {
        "schema_version": 2,
        "resources": {resource.module: {"operations": [operation.operation_id for operation in resource.operations]}
                      for resource in ir.resources},
        "models": {model.name: {"raw": model.raw, "fields": sorted(field.name for field in rust.fields(model.raw)) if model.raw in rust.structs else []}
                   for model in ir.models},
    }
    (target / "coverage.json").write_text(json.dumps(coverage, indent=2) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("raw", type=Path)
    parser.add_argument("target", type=Path)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--openapi", type=Path)
    args = parser.parse_args()
    generate(args.raw, args.target, args.manifest, args.openapi)


if __name__ == "__main__":
    main()
