"""Mistral integration boundary for the pinned generic facade compiler."""

from pathlib import Path
from typing import Any

from openapi_rust_facade import (
    GenerationError,
    OpenApiIndex,
    RustBindingsIr,
    RustFacadeRuntime,
    compile_facade as _compile_facade,
    compile_ir,
)
from openapi_rust_facade.adapters.openapi_to_rust import OpenApiToRustAdapter


GENERATED = "// @generated by codegen/sdk_facade.py; do not edit by hand.\n"
MISTRAL_RUNTIME = RustFacadeRuntime(generated_marker=GENERATED)


def load_raw_ir(raw: Path) -> RustBindingsIr:
    """Normalize the pinned openapi-to-rust output for the generic compiler."""
    try:
        return OpenApiToRustAdapter.load(raw)
    except ValueError as error:
        raise GenerationError(str(error)) from error


def compile_facade(
    openapi: OpenApiIndex,
    bindings: RustBindingsIr,
    manifest: dict[str, Any],
):
    """Compile with the Mistral-owned facade runtime contract."""
    return _compile_facade(openapi, bindings, manifest, runtime=MISTRAL_RUNTIME)


__all__ = [
    "GENERATED",
    "GenerationError",
    "MISTRAL_RUNTIME",
    "OpenApiIndex",
    "RustBindingsIr",
    "compile_facade",
    "compile_ir",
    "load_raw_ir",
]
