// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use futures_util::StreamExt;
use super::*;
use crate::generated::client::HttpClient;




#[derive(Debug, Clone, Default)]
pub struct ListAudioVoicesRequest { limit: Option<i64>, offset: Option<i64>, r#type: Option<crate::generated::client::ListVoicesV1AudioVoicesGetType> }
impl ListAudioVoicesRequest { pub fn new() -> Self { Self { limit: None, offset: None, r#type: None } }
#[must_use] pub fn limit(mut self, limit: i64) -> Self { self.limit = Some(limit); self }
#[must_use] pub fn offset(mut self, offset: i64) -> Self { self.offset = Some(offset); self }
#[must_use] pub fn r#type(mut self, r#type: crate::generated::client::ListVoicesV1AudioVoicesGetType) -> Self { self.r#type = Some(r#type); self }
}

#[derive(Clone, Copy)]
pub struct AudioVoices<'a> { raw: &'a HttpClient }

impl<'a> AudioVoices<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self { Self { raw } }
    pub async fn create(&self, request: CreateAudioVoicesRequest) -> Result<CreateAudioVoicesResponse, SdkError> {
        self.raw.create_voice_v1_audio_voices_post(request.into_raw()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn delete(&self, voice_id: impl AsRef<str>) -> Result<DeleteAudioVoicesResponse, SdkError> {
        self.raw.delete_voice_v1_audio_voices_voice_id_delete(voice_id.as_ref()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn get(&self, voice_id: impl AsRef<str>) -> Result<GetAudioVoicesResponse, SdkError> {
        self.raw.get_voice_v1_audio_voices_voice_id_get(voice_id.as_ref()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn get_sample_audio(&self, voice_id: impl AsRef<str>) -> Result<BinaryStream, SdkError> {
        let bytes = self.raw.get_voice_sample_audio_v1_audio_voices_voice_id_sample_get_stream(voice_id.as_ref()).await.map_err(SdkError::from)?;
        let chunks = bytes.map(|chunk| chunk.map_err(Into::into));
        Ok(Box::pin(chunks))
    }

    pub async fn list(&self) -> Result<ListAudioVoicesResponse, SdkError> {
        self.raw.list_voices_v1_audio_voices_get(None, None, None).await.map(Into::into).map_err(Into::into)
    }

    pub async fn list_with(&self, request: ListAudioVoicesRequest) -> Result<ListAudioVoicesResponse, SdkError> {
        self.raw.list_voices_v1_audio_voices_get(request.limit, request.offset, request.r#type).await.map(Into::into).map_err(Into::into)
    }

    pub async fn update(&self, voice_id: impl AsRef<str>, request: UpdateAudioVoicesRequest) -> Result<UpdateAudioVoicesResponse, SdkError> {
        self.raw.update_voice_v1_audio_voices_voice_id_patch(voice_id.as_ref(), request.into_raw()).await.map(Into::into).map_err(Into::into)
    }
}
