// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use futures_util::StreamExt;
use crate::generated::types::*;
use super::*;
use crate::generated::client::HttpClient;

#[derive(Clone, Copy)]
pub struct AudioTranscriptions<'a> { raw: &'a HttpClient }

impl<'a> AudioTranscriptions<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self { Self { raw } }
    pub async fn complete(&self, request: CompleteAudioTranscriptionsRequest) -> Result<CompleteAudioTranscriptionsResponse, SdkError> {
        self.raw.audio_api_v1_transcriptions_post({ let mut raw = request.into_raw(); raw.stream = Some(false); raw }).await.map(Into::into).map_err(Into::into)
    }

    pub async fn complete_with_filenames(&self, request: CompleteAudioTranscriptionsRequest, multipart_filenames: &[(&str, &str)]) -> Result<CompleteAudioTranscriptionsResponse, SdkError> {
        self.raw.audio_api_v1_transcriptions_post_with_multipart_filenames({ let mut raw = request.into_raw(); raw.stream = Some(false); raw }, multipart_filenames).await.map(Into::into).map_err(Into::into)
    }

    pub async fn stream(&self, request: StreamAudioTranscriptionsRequest) -> Result<StreamAudioTranscriptionsStream, SdkError> {
        let bytes = self.raw.audio_api_v1_transcriptions_post_stream({ let mut raw = request.into_raw(); raw.stream = Some(true); raw }).await.map_err(SdkError::from)?;
        let events = crate::streaming::json_events::<_, _, TranscriptionStreamEvents>(bytes)
            .map(|event| event.map(|event| StreamAudioTranscriptionsStreamItem::from(event.data)).map_err(Into::into));
        Ok(Box::pin(events))
    }

    pub async fn stream_with_filenames(&self, request: StreamAudioTranscriptionsRequest, multipart_filenames: &[(&str, &str)]) -> Result<StreamAudioTranscriptionsStream, SdkError> {
        let bytes = self.raw.audio_api_v1_transcriptions_post_stream_with_multipart_filenames({ let mut raw = request.into_raw(); raw.stream = Some(true); raw }, multipart_filenames).await.map_err(SdkError::from)?;
        let events = crate::streaming::json_events::<_, _, TranscriptionStreamEvents>(bytes)
            .map(|event| event.map(|event| StreamAudioTranscriptionsStreamItem::from(event.data)).map_err(Into::into));
        Ok(Box::pin(events))
    }
}
