// @generated by codegen/sdk_facade.py; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;

#[derive(Debug, Clone, Default)]
pub struct ListAudioVoicesRequest {
    limit: Option<i64>,
    offset: Option<i64>,
}
impl ListAudioVoicesRequest {
    pub fn new() -> Self {
        Self {
            limit: None,
            offset: None,
        }
    }
    #[must_use]
    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }
    #[must_use]
    pub fn offset(mut self, offset: i64) -> Self {
        self.offset = Some(offset);
        self
    }
}

#[derive(Clone, Copy)]
pub struct AudioVoices<'a> {
    raw: &'a HttpClient,
}

impl<'a> AudioVoices<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn create(
        &self,
        request: VoiceCreateRequestParams,
    ) -> Result<VoiceResponseView, SdkError> {
        self.raw
            .create_voice_v1_audio_voices_post(request.into_raw())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn delete(&self, voice_id: impl AsRef<str>) -> Result<VoiceResponseView, SdkError> {
        self.raw
            .delete_voice_v1_audio_voices_voice_id_delete(voice_id.as_ref())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn get(&self, voice_id: impl AsRef<str>) -> Result<VoiceResponseView, SdkError> {
        self.raw
            .get_voice_v1_audio_voices_voice_id_get(voice_id.as_ref())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn list(&self) -> Result<VoiceListResponseView, SdkError> {
        self.raw
            .list_voices_v1_audio_voices_get(None, None)
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn list_with(
        &self,
        request: ListAudioVoicesRequest,
    ) -> Result<VoiceListResponseView, SdkError> {
        self.raw
            .list_voices_v1_audio_voices_get(request.limit, request.offset)
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn update(
        &self,
        voice_id: impl AsRef<str>,
        request: VoiceUpdateRequestParams,
    ) -> Result<VoiceResponseView, SdkError> {
        self.raw
            .update_voice_v1_audio_voices_voice_id_patch(voice_id.as_ref(), request.into_raw())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
