// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;






#[derive(Debug, Clone, Default)]
pub struct UsersGetUsersBetaAdminUsersRequest { page: Option<i64>, page_size: Option<i64>, email: Option<String> }
impl UsersGetUsersBetaAdminUsersRequest { pub fn new() -> Self { Self { page: None, page_size: None, email: None } }
#[must_use] pub fn page(mut self, page: i64) -> Self { self.page = Some(page); self }
#[must_use] pub fn page_size(mut self, page_size: i64) -> Self { self.page_size = Some(page_size); self }
#[must_use] pub fn email(mut self, email: impl Into<String>) -> Self { self.email = Some(email.into()); self }
}


#[derive(Clone, Copy)]
pub struct BetaAdminUsers<'a> { raw: &'a HttpClient }

impl<'a> BetaAdminUsers<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self { Self { raw } }
    pub async fn roles_get_roles(&self) -> Result<RolesGetRolesBetaAdminUsersResponse, SdkError> {
        self.raw.users_api_admin_roles_get_roles().await.map(Into::into).map_err(Into::into)
    }

    pub async fn users_create_users(&self, request: UsersCreateUsersBetaAdminUsersRequest) -> Result<UsersCreateUsersBetaAdminUsersResponse, SdkError> {
        self.raw.users_api_admin_users_create_users(request.into_raw()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn users_delete_invite(&self, invite_uuid: impl AsRef<str>) -> Result<UsersDeleteInviteBetaAdminUsersResponse, SdkError> {
        self.raw.users_api_admin_users_delete_invite(invite_uuid.as_ref()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn users_delete_user(&self, user_id: impl AsRef<str>) -> Result<UsersDeleteUserBetaAdminUsersResponse, SdkError> {
        self.raw.users_api_admin_users_delete_user(user_id.as_ref()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn users_get_invite(&self) -> Result<UsersGetInviteBetaAdminUsersResponse, SdkError> {
        self.raw.users_api_admin_users_get_invite().await.map(Into::into).map_err(Into::into)
    }

    pub async fn users_get_user(&self, user_id: impl AsRef<str>) -> Result<UsersGetUserBetaAdminUsersResponse, SdkError> {
        self.raw.users_api_admin_users_get_user(user_id.as_ref()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn users_get_users(&self) -> Result<UsersGetUsersBetaAdminUsersResponse, SdkError> {
        self.raw.users_api_admin_users_get_users(None, None, None::<&str>).await.map(Into::into).map_err(Into::into)
    }

    pub async fn users_get_users_with(&self, request: UsersGetUsersBetaAdminUsersRequest) -> Result<UsersGetUsersBetaAdminUsersResponse, SdkError> {
        self.raw.users_api_admin_users_get_users(request.page, request.page_size, request.email.as_deref()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn users_invite_users(&self, request: UsersInviteUsersBetaAdminUsersRequest) -> Result<UsersInviteUsersBetaAdminUsersResponse, SdkError> {
        self.raw.users_api_admin_users_invite_users(request.into_raw()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn users_update_user(&self, user_id: impl AsRef<str>, request: UsersUpdateUserBetaAdminUsersRequest) -> Result<UsersUpdateUserBetaAdminUsersResponse, SdkError> {
        self.raw.users_api_admin_users_update_user(user_id.as_ref(), request.into_raw()).await.map(Into::into).map_err(Into::into)
    }
}
