// @generated by codegen/sdk_facade.py; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;

#[derive(Clone, Copy)]
pub struct BetaConversations<'a> {
    raw: &'a HttpClient,
}

impl<'a> BetaConversations<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn get_history(
        &self,
        conversation_id: impl AsRef<str>,
    ) -> Result<ConversationHistoryView, SdkError> {
        self.raw
            .agents_api_v1_conversations_history(conversation_id.as_ref())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn get_messages(
        &self,
        conversation_id: impl AsRef<str>,
    ) -> Result<ConversationMessagesView, SdkError> {
        self.raw
            .agents_api_v1_conversations_messages(conversation_id.as_ref())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
