// @generated by tooling/pipeline/compile_sdk.py; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;

#[derive(Clone, Copy)]
pub struct BetaLibraries<'a> {
    raw: &'a HttpClient,
}

impl<'a> BetaLibraries<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub fn accesses(&self) -> BetaLibrariesAccesses<'a> {
        BetaLibrariesAccesses::new(self.raw)
    }

    pub fn documents(&self) -> BetaLibrariesDocuments<'a> {
        BetaLibrariesDocuments::new(self.raw)
    }

    pub async fn create(&self, request: LibraryInParams) -> Result<LibraryOutView, SdkError> {
        self.raw
            .libraries_create_v1(request.into_raw())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn delete(&self, library_id: impl AsRef<str>) -> Result<LibraryOutView, SdkError> {
        self.raw
            .libraries_delete_v1(library_id.as_ref())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn get(&self, library_id: impl AsRef<str>) -> Result<LibraryOutView, SdkError> {
        self.raw
            .libraries_get_v1(library_id.as_ref())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn list(&self) -> Result<ListLibraryOutView, SdkError> {
        self.raw
            .libraries_list_v1()
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn libraries_update_v1(
        &self,
        library_id: impl AsRef<str>,
        request: LibraryInUpdateParams,
    ) -> Result<LibraryOutView, SdkError> {
        self.raw
            .libraries_update_v1(library_id.as_ref(), request.into_raw())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
