// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;

#[derive(Debug, Clone)]
pub struct FetchSpanEvalFieldOptionsBetaObservabilitySpansRequest {
    field_name: String,
    from: Option<String>,
    to: Option<String>,
}
impl FetchSpanEvalFieldOptionsBetaObservabilitySpansRequest {
    pub fn new(field_name: impl Into<String>) -> Self {
        Self {
            field_name: field_name.into(),
            from: None,
            to: None,
        }
    }
    #[must_use]
    pub fn from(mut self, from: impl Into<String>) -> Self {
        self.from = Some(from.into());
        self
    }
    #[must_use]
    pub fn to(mut self, to: impl Into<String>) -> Self {
        self.to = Some(to.into());
        self
    }
}

#[derive(Debug, Clone)]
pub struct FetchSpanFieldOptionsBetaObservabilitySpansRequest {
    field_name: String,
    from: Option<String>,
    to: Option<String>,
}
impl FetchSpanFieldOptionsBetaObservabilitySpansRequest {
    pub fn new(field_name: impl Into<String>) -> Self {
        Self {
            field_name: field_name.into(),
            from: None,
            to: None,
        }
    }
    #[must_use]
    pub fn from(mut self, from: impl Into<String>) -> Self {
        self.from = Some(from.into());
        self
    }
    #[must_use]
    pub fn to(mut self, to: impl Into<String>) -> Self {
        self.to = Some(to.into());
        self
    }
}

#[derive(Clone, Copy)]
pub struct BetaObservabilitySpans<'a> {
    raw: &'a HttpClient,
}

impl<'a> BetaObservabilitySpans<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn aggregate(
        &self,
        from: Option<String>,
        to: Option<String>,
        request: AggregateBetaObservabilitySpansRequest,
    ) -> Result<AggregateBetaObservabilitySpansResponse, SdkError> {
        self.raw
            .aggregate_spans_v1_observability_spans_aggregate_post(from, to, request.into_raw())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn fetch_span_eval_field_options(
        &self,
        request: FetchSpanEvalFieldOptionsBetaObservabilitySpansRequest,
    ) -> Result<FetchSpanEvalFieldOptionsBetaObservabilitySpansResponse, SdkError> {
        self.raw.get_span_evaluation_field_options_v1_observability_spans_evaluations_fields_field_name_options_get(request.field_name.as_str(), request.from.as_deref(), request.to.as_deref()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn fetch_span_field_options(
        &self,
        request: FetchSpanFieldOptionsBetaObservabilitySpansRequest,
    ) -> Result<FetchSpanFieldOptionsBetaObservabilitySpansResponse, SdkError> {
        self.raw
            .get_span_field_options_v1_observability_spans_fields_field_name_options_get(
                request.field_name.as_str(),
                request.from.as_deref(),
                request.to.as_deref(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn list_span_eval_fields(
        &self,
    ) -> Result<ListSpanEvalFieldsBetaObservabilitySpansResponse, SdkError> {
        self.raw
            .get_span_evaluation_fields_v1_observability_spans_evaluations_fields_get()
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn list_span_fields(
        &self,
    ) -> Result<ListSpanFieldsBetaObservabilitySpansResponse, SdkError> {
        self.raw
            .get_span_fields_v1_observability_spans_fields_get()
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn search_latest_span_evaluations(
        &self,
        from: Option<String>,
        to: Option<String>,
        page_size: Option<i64>,
        cursor: Option<String>,
        request: SearchLatestSpanEvaluationsBetaObservabilitySpansRequest,
    ) -> Result<SearchLatestSpanEvaluationsBetaObservabilitySpansResponse, SdkError> {
        self.raw
            .search_latest_span_evaluations_v1_observability_spans_evaluations_search_latest_post(
                from,
                to,
                page_size,
                cursor,
                request.into_raw(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn search_span_evaluations(
        &self,
        from: Option<String>,
        to: Option<String>,
        page_size: Option<i64>,
        cursor: Option<String>,
        request: SearchSpanEvaluationsBetaObservabilitySpansRequest,
    ) -> Result<SearchSpanEvaluationsBetaObservabilitySpansResponse, SdkError> {
        self.raw
            .search_span_evaluations_v1_observability_spans_evaluations_search_post(
                from,
                to,
                page_size,
                cursor,
                request.into_raw(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn search_spans(
        &self,
        from: Option<String>,
        to: Option<String>,
        page_size: Option<i64>,
        cursor: Option<String>,
        request: SearchSpansBetaObservabilitySpansRequest,
    ) -> Result<SearchSpansBetaObservabilitySpansResponse, SdkError> {
        self.raw
            .search_spans_v1_observability_spans_search_post(
                from,
                to,
                page_size,
                cursor,
                request.into_raw(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
