// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;

#[derive(Debug, Clone)]
pub struct GetCampaignSelectedEventsBetaObservabilityCampaignsRequest {
    campaign_id: String,
    page_size: Option<i64>,
    page: Option<i64>,
}
impl GetCampaignSelectedEventsBetaObservabilityCampaignsRequest {
    pub fn new(campaign_id: impl Into<String>) -> Self {
        Self {
            campaign_id: campaign_id.into(),
            page_size: None,
            page: None,
        }
    }
    #[must_use]
    pub fn page_size(mut self, page_size: i64) -> Self {
        self.page_size = Some(page_size);
        self
    }
    #[must_use]
    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }
}

#[derive(Debug, Clone, Default)]
pub struct GetCampaignsBetaObservabilityCampaignsRequest {
    page_size: Option<i64>,
    page: Option<i64>,
    q: Option<String>,
}
impl GetCampaignsBetaObservabilityCampaignsRequest {
    pub fn new() -> Self {
        Self {
            page_size: None,
            page: None,
            q: None,
        }
    }
    #[must_use]
    pub fn page_size(mut self, page_size: i64) -> Self {
        self.page_size = Some(page_size);
        self
    }
    #[must_use]
    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }
    #[must_use]
    pub fn q(mut self, q: impl Into<String>) -> Self {
        self.q = Some(q.into());
        self
    }
}
#[derive(Clone, Copy)]
pub struct BetaObservabilityCampaigns<'a> {
    raw: &'a HttpClient,
}

impl<'a> BetaObservabilityCampaigns<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn delete_campaign(&self, campaign_id: impl AsRef<str>) -> Result<(), SdkError> {
        self.raw
            .delete_campaign_v1_observability_campaigns_campaign_id_delete(campaign_id.as_ref())
            .await
            .map_err(Into::into)
    }

    pub async fn get_campaign_by_id(
        &self,
        campaign_id: impl AsRef<str>,
    ) -> Result<CampaignPreviewView, SdkError> {
        self.raw
            .get_campaign_by_id_v1_observability_campaigns_campaign_id_get(campaign_id.as_ref())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn get_campaign_selected_events(
        &self,
        request: GetCampaignSelectedEventsBetaObservabilityCampaignsRequest,
    ) -> Result<CampaignSelectedEventsView, SdkError> {
        self.raw.get_campaign_selected_events_v1_observability_campaigns_campaign_id_selected_events_get(request.campaign_id.as_str(), request.page_size, request.page).await.map(Into::into).map_err(Into::into)
    }

    pub async fn get_campaign_status_by_id(
        &self,
        campaign_id: impl AsRef<str>,
    ) -> Result<CampaignStatusView, SdkError> {
        self.raw
            .get_campaign_status_by_id_v1_observability_campaigns_campaign_id_status_get(
                campaign_id.as_ref(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn get_campaigns(&self) -> Result<CampaignPreviewsView, SdkError> {
        self.raw
            .get_campaigns_v1_observability_campaigns_get(None, None, None::<&str>)
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn get_campaigns_with(
        &self,
        request: GetCampaignsBetaObservabilityCampaignsRequest,
    ) -> Result<CampaignPreviewsView, SdkError> {
        self.raw
            .get_campaigns_v1_observability_campaigns_get(
                request.page_size,
                request.page,
                request.q.as_deref(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
