// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;
#[derive(Debug, Clone)]
pub struct AdminUserGroupsGetGroupWorkspaceAssignmentsBetaAdminUserGroupsRequest { group_uuid: String, page: Option<i64>, page_size: Option<i64> }
impl AdminUserGroupsGetGroupWorkspaceAssignmentsBetaAdminUserGroupsRequest { pub fn new(group_uuid: impl Into<String>) -> Self { Self { group_uuid: group_uuid.into(), page: None, page_size: None } }
#[must_use] pub fn page(mut self, page: i64) -> Self { self.page = Some(page); self }
#[must_use] pub fn page_size(mut self, page_size: i64) -> Self { self.page_size = Some(page_size); self }
}










#[derive(Debug, Clone)]
pub struct ApiAdminUserGroupsGetUserGroupMembersBetaAdminUserGroupsRequest { group_uuid: String, page: Option<i64>, page_size: Option<i64> }
impl ApiAdminUserGroupsGetUserGroupMembersBetaAdminUserGroupsRequest { pub fn new(group_uuid: impl Into<String>) -> Self { Self { group_uuid: group_uuid.into(), page: None, page_size: None } }
#[must_use] pub fn page(mut self, page: i64) -> Self { self.page = Some(page); self }
#[must_use] pub fn page_size(mut self, page_size: i64) -> Self { self.page_size = Some(page_size); self }
}

#[derive(Debug, Clone, Default)]
pub struct ApiAdminUserGroupsGetUserGroupsBetaAdminUserGroupsRequest { page: Option<i64>, page_size: Option<i64>, search: Option<String> }
impl ApiAdminUserGroupsGetUserGroupsBetaAdminUserGroupsRequest { pub fn new() -> Self { Self { page: None, page_size: None, search: None } }
#[must_use] pub fn page(mut self, page: i64) -> Self { self.page = Some(page); self }
#[must_use] pub fn page_size(mut self, page_size: i64) -> Self { self.page_size = Some(page_size); self }
#[must_use] pub fn search(mut self, search: impl Into<String>) -> Self { self.search = Some(search.into()); self }
}




#[derive(Clone, Copy)]
pub struct BetaAdminUserGroups<'a> { raw: &'a HttpClient }

impl<'a> BetaAdminUserGroups<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self { Self { raw } }
    pub async fn admin_user_groups_get_group_workspace_assignments(&self, request: AdminUserGroupsGetGroupWorkspaceAssignmentsBetaAdminUserGroupsRequest) -> Result<AdminUserGroupsGetGroupWorkspaceAssignmentsBetaAdminUserGroupsResponse, SdkError> {
        self.raw.users_admin_user_groups_get_group_workspace_assignments(request.group_uuid.as_str(), request.page, request.page_size).await.map(Into::into).map_err(Into::into)
    }

    pub async fn admin_user_groups_remove_group_from_workspace(&self, group_uuid: impl AsRef<str>, workspace_uuid: impl AsRef<str>) -> Result<(), SdkError> {
        self.raw.users_admin_user_groups_remove_group_from_workspace(group_uuid.as_ref(), workspace_uuid.as_ref()).await.map_err(Into::into)
    }

    pub async fn admin_user_groups_update_group_workspace_assignment(&self, group_uuid: impl AsRef<str>, workspace_uuid: impl AsRef<str>, request: AdminUserGroupsUpdateGroupWorkspaceAssignmentBetaAdminUserGroupsRequest) -> Result<(), SdkError> {
        self.raw.users_admin_user_groups_update_group_workspace_assignment(group_uuid.as_ref(), workspace_uuid.as_ref(), request.into_raw()).await.map_err(Into::into)
    }

    pub async fn admin_user_groups_update_user_group_organization_role(&self, group_uuid: impl AsRef<str>, request: AdminUserGroupsUpdateUserGroupOrganizationRoleBetaAdminUserGroupsRequest) -> Result<(), SdkError> {
        self.raw.users_admin_user_groups_update_user_group_organization_role(group_uuid.as_ref(), request.into_raw()).await.map_err(Into::into)
    }

    pub async fn api_admin_user_groups_assign_group_to_workspace(&self, group_uuid: impl AsRef<str>, request: ApiAdminUserGroupsAssignGroupToWorkspaceBetaAdminUserGroupsRequest) -> Result<(), SdkError> {
        self.raw.users_api_admin_user_groups_assign_group_to_workspace(group_uuid.as_ref(), request.into_raw()).await.map_err(Into::into)
    }

    pub async fn api_admin_user_groups_assign_users_to_group(&self, group_uuid: impl AsRef<str>, request: ApiAdminUserGroupsAssignUsersToGroupBetaAdminUserGroupsRequest) -> Result<(), SdkError> {
        self.raw.users_api_admin_user_groups_assign_users_to_group(group_uuid.as_ref(), request.into_raw()).await.map_err(Into::into)
    }

    pub async fn api_admin_user_groups_create_user_group(&self, request: ApiAdminUserGroupsCreateUserGroupBetaAdminUserGroupsRequest) -> Result<ApiAdminUserGroupsCreateUserGroupBetaAdminUserGroupsResponse, SdkError> {
        self.raw.users_api_admin_user_groups_create_user_group(request.into_raw()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn api_admin_user_groups_delete_user_group(&self, group_uuid: impl AsRef<str>) -> Result<(), SdkError> {
        self.raw.users_api_admin_user_groups_delete_user_group(group_uuid.as_ref()).await.map_err(Into::into)
    }

    pub async fn api_admin_user_groups_get_nested_groups(&self, group_uuid: impl AsRef<str>) -> Result<ApiAdminUserGroupsGetNestedGroupsBetaAdminUserGroupsResponse, SdkError> {
        self.raw.users_api_admin_user_groups_get_nested_groups(group_uuid.as_ref()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn api_admin_user_groups_get_user_group(&self, group_uuid: impl AsRef<str>) -> Result<ApiAdminUserGroupsGetUserGroupBetaAdminUserGroupsResponse, SdkError> {
        self.raw.users_api_admin_user_groups_get_user_group(group_uuid.as_ref()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn api_admin_user_groups_get_user_group_members(&self, request: ApiAdminUserGroupsGetUserGroupMembersBetaAdminUserGroupsRequest) -> Result<ApiAdminUserGroupsGetUserGroupMembersBetaAdminUserGroupsResponse, SdkError> {
        self.raw.users_api_admin_user_groups_get_user_group_members(request.group_uuid.as_str(), request.page, request.page_size).await.map(Into::into).map_err(Into::into)
    }

    pub async fn api_admin_user_groups_get_user_groups(&self) -> Result<ApiAdminUserGroupsGetUserGroupsBetaAdminUserGroupsResponse, SdkError> {
        self.raw.users_api_admin_user_groups_get_user_groups(None, None, None::<&str>).await.map(Into::into).map_err(Into::into)
    }

    pub async fn api_admin_user_groups_get_user_groups_with(&self, request: ApiAdminUserGroupsGetUserGroupsBetaAdminUserGroupsRequest) -> Result<ApiAdminUserGroupsGetUserGroupsBetaAdminUserGroupsResponse, SdkError> {
        self.raw.users_api_admin_user_groups_get_user_groups(request.page, request.page_size, request.search.as_deref()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn api_admin_user_groups_provision_group_to_workspace(&self, request: ApiAdminUserGroupsProvisionGroupToWorkspaceBetaAdminUserGroupsRequest) -> Result<(), SdkError> {
        self.raw.users_api_admin_user_groups_provision_group_to_workspace(request.into_raw()).await.map_err(Into::into)
    }

    pub async fn api_admin_user_groups_remove_users_from_group(&self, group_uuid: impl AsRef<str>, request: ApiAdminUserGroupsRemoveUsersFromGroupBetaAdminUserGroupsRequest) -> Result<(), SdkError> {
        self.raw.users_api_admin_user_groups_remove_users_from_group(group_uuid.as_ref(), request.into_raw()).await.map_err(Into::into)
    }

    pub async fn api_admin_user_groups_set_nested_groups(&self, group_uuid: impl AsRef<str>, request: ApiAdminUserGroupsSetNestedGroupsBetaAdminUserGroupsRequest) -> Result<(), SdkError> {
        self.raw.users_api_admin_user_groups_set_nested_groups(group_uuid.as_ref(), request.into_raw()).await.map_err(Into::into)
    }

    pub async fn api_admin_user_groups_update_user_group(&self, group_uuid: impl AsRef<str>, request: ApiAdminUserGroupsUpdateUserGroupBetaAdminUserGroupsRequest) -> Result<ApiAdminUserGroupsUpdateUserGroupBetaAdminUserGroupsResponse, SdkError> {
        self.raw.users_api_admin_user_groups_update_user_group(group_uuid.as_ref(), request.into_raw()).await.map(Into::into).map_err(Into::into)
    }
}
