// @generated by codegen/sdk_facade.py; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;

#[derive(Debug, Clone)]
pub struct ListBetaLibrariesDocumentsRequest {
    library_id: String,
    search: Option<String>,
    page_size: Option<i64>,
    page: Option<i64>,
    filters_attributes: Option<String>,
    sort_by: Option<String>,
    sort_order: Option<String>,
}
impl ListBetaLibrariesDocumentsRequest {
    pub fn new(library_id: impl Into<String>) -> Self {
        Self {
            library_id: library_id.into(),
            search: None,
            page_size: None,
            page: None,
            filters_attributes: None,
            sort_by: None,
            sort_order: None,
        }
    }
    #[must_use]
    pub fn search(mut self, search: impl Into<String>) -> Self {
        self.search = Some(search.into());
        self
    }
    #[must_use]
    pub fn page_size(mut self, page_size: i64) -> Self {
        self.page_size = Some(page_size);
        self
    }
    #[must_use]
    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }
    #[must_use]
    pub fn filters_attributes(mut self, filters_attributes: impl Into<String>) -> Self {
        self.filters_attributes = Some(filters_attributes.into());
        self
    }
    #[must_use]
    pub fn sort_by(mut self, sort_by: impl Into<String>) -> Self {
        self.sort_by = Some(sort_by.into());
        self
    }
    #[must_use]
    pub fn sort_order(mut self, sort_order: impl Into<String>) -> Self {
        self.sort_order = Some(sort_order.into());
        self
    }
}
#[derive(Clone, Copy)]
pub struct BetaLibrariesDocuments<'a> {
    raw: &'a HttpClient,
}

impl<'a> BetaLibrariesDocuments<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn status(
        &self,
        library_id: impl AsRef<str>,
        document_id: impl AsRef<str>,
    ) -> Result<ProcessingStatusOutView, SdkError> {
        self.raw
            .libraries_documents_get_status_v1(library_id.as_ref(), document_id.as_ref())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn text_content(
        &self,
        library_id: impl AsRef<str>,
        document_id: impl AsRef<str>,
    ) -> Result<DocumentTextContentView, SdkError> {
        self.raw
            .libraries_documents_get_text_content_v1(library_id.as_ref(), document_id.as_ref())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn get(
        &self,
        library_id: impl AsRef<str>,
        document_id: impl AsRef<str>,
    ) -> Result<DocumentOutView, SdkError> {
        self.raw
            .libraries_documents_get_v1(library_id.as_ref(), document_id.as_ref())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn list(
        &self,
        request: ListBetaLibrariesDocumentsRequest,
    ) -> Result<ListDocumentOutView, SdkError> {
        self.raw
            .libraries_documents_list_v1(
                request.library_id.as_str(),
                request.search.as_deref(),
                request.page_size,
                request.page,
                request.filters_attributes.as_deref(),
                request.sort_by.as_deref(),
                request.sort_order.as_deref(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
