// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;
#[derive(Debug, Clone, Default)]
pub struct UsersApiAdminAuditLogsGetAuditLogsBetaAdminAuditLogsRequest {
    actor_type: Option<String>,
    event_type: Option<String>,
    target_type: Option<String>,
    actor_user_uuid: Option<String>,
    sort: Option<String>,
    after: Option<String>,
    before: Option<String>,
    limit: Option<i64>,
}
impl UsersApiAdminAuditLogsGetAuditLogsBetaAdminAuditLogsRequest {
    pub fn new() -> Self {
        Self {
            actor_type: None,
            event_type: None,
            target_type: None,
            actor_user_uuid: None,
            sort: None,
            after: None,
            before: None,
            limit: None,
        }
    }
    #[must_use]
    pub fn actor_type(mut self, actor_type: impl Into<String>) -> Self {
        self.actor_type = Some(actor_type.into());
        self
    }
    #[must_use]
    pub fn event_type(mut self, event_type: impl Into<String>) -> Self {
        self.event_type = Some(event_type.into());
        self
    }
    #[must_use]
    pub fn target_type(mut self, target_type: impl Into<String>) -> Self {
        self.target_type = Some(target_type.into());
        self
    }
    #[must_use]
    pub fn actor_user_uuid(mut self, actor_user_uuid: impl Into<String>) -> Self {
        self.actor_user_uuid = Some(actor_user_uuid.into());
        self
    }
    #[must_use]
    pub fn sort(mut self, sort: impl Into<String>) -> Self {
        self.sort = Some(sort.into());
        self
    }
    #[must_use]
    pub fn after(mut self, after: impl Into<String>) -> Self {
        self.after = Some(after.into());
        self
    }
    #[must_use]
    pub fn before(mut self, before: impl Into<String>) -> Self {
        self.before = Some(before.into());
        self
    }
    #[must_use]
    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }
}
#[derive(Clone, Copy)]
pub struct BetaAdminAuditLogs<'a> {
    raw: &'a HttpClient,
}

impl<'a> BetaAdminAuditLogs<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn users_api_admin_audit_logs_get_audit_logs(
        &self,
    ) -> Result<UsersApiAdminAuditLogsGetAuditLogsBetaAdminAuditLogsResponse, SdkError> {
        self.raw
            .users_api_admin_audit_logs_get_audit_logs(
                None::<&str>,
                None::<&str>,
                None::<&str>,
                None::<&str>,
                None::<&str>,
                None::<&str>,
                None::<&str>,
                None,
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn users_api_admin_audit_logs_get_audit_logs_with(
        &self,
        request: UsersApiAdminAuditLogsGetAuditLogsBetaAdminAuditLogsRequest,
    ) -> Result<UsersApiAdminAuditLogsGetAuditLogsBetaAdminAuditLogsResponse, SdkError> {
        self.raw
            .users_api_admin_audit_logs_get_audit_logs(
                request.actor_type.as_deref(),
                request.event_type.as_deref(),
                request.target_type.as_deref(),
                request.actor_user_uuid.as_deref(),
                request.sort.as_deref(),
                request.after.as_deref(),
                request.before.as_deref(),
                request.limit,
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
