// @generated by tooling/pipeline/compile_sdk.py; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;
#[derive(Clone, Copy)]
pub struct Beta<'a> {
    raw: &'a HttpClient,
}

impl<'a> Beta<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub fn agents(&self) -> BetaAgents<'a> {
        BetaAgents::new(self.raw)
    }

    pub fn connectors(&self) -> BetaConnectors<'a> {
        BetaConnectors::new(self.raw)
    }

    pub fn conversations(&self) -> BetaConversations<'a> {
        BetaConversations::new(self.raw)
    }

    pub fn libraries(&self) -> BetaLibraries<'a> {
        BetaLibraries::new(self.raw)
    }

    pub fn observability(&self) -> BetaObservability<'a> {
        BetaObservability::new(self.raw)
    }
}
