// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;

#[derive(Debug, Clone)]
pub struct GetSpanByIdBetaObservabilityTracesRequest {
    trace_id: String,
    span_id: String,
    from: Option<String>,
    to: Option<String>,
}
impl GetSpanByIdBetaObservabilityTracesRequest {
    pub fn new(trace_id: impl Into<String>, span_id: impl Into<String>) -> Self {
        Self {
            trace_id: trace_id.into(),
            span_id: span_id.into(),
            from: None,
            to: None,
        }
    }
    #[must_use]
    pub fn from(mut self, from: impl Into<String>) -> Self {
        self.from = Some(from.into());
        self
    }
    #[must_use]
    pub fn to(mut self, to: impl Into<String>) -> Self {
        self.to = Some(to.into());
        self
    }
}

#[derive(Debug, Clone)]
pub struct GetTraceFieldOptionsBetaObservabilityTracesRequest {
    field_name: String,
    from: Option<String>,
    to: Option<String>,
}
impl GetTraceFieldOptionsBetaObservabilityTracesRequest {
    pub fn new(field_name: impl Into<String>) -> Self {
        Self {
            field_name: field_name.into(),
            from: None,
            to: None,
        }
    }
    #[must_use]
    pub fn from(mut self, from: impl Into<String>) -> Self {
        self.from = Some(from.into());
        self
    }
    #[must_use]
    pub fn to(mut self, to: impl Into<String>) -> Self {
        self.to = Some(to.into());
        self
    }
}

#[derive(Debug, Clone)]
pub struct GetTraceSpansBetaObservabilityTracesRequest {
    trace_id: String,
    from: Option<String>,
    to: Option<String>,
    page_size: Option<i64>,
    cursor: Option<String>,
}
impl GetTraceSpansBetaObservabilityTracesRequest {
    pub fn new(trace_id: impl Into<String>) -> Self {
        Self {
            trace_id: trace_id.into(),
            from: None,
            to: None,
            page_size: None,
            cursor: None,
        }
    }
    #[must_use]
    pub fn from(mut self, from: impl Into<String>) -> Self {
        self.from = Some(from.into());
        self
    }
    #[must_use]
    pub fn to(mut self, to: impl Into<String>) -> Self {
        self.to = Some(to.into());
        self
    }
    #[must_use]
    pub fn page_size(mut self, page_size: i64) -> Self {
        self.page_size = Some(page_size);
        self
    }
    #[must_use]
    pub fn cursor(mut self, cursor: impl Into<String>) -> Self {
        self.cursor = Some(cursor.into());
        self
    }
}

#[derive(Clone, Copy)]
pub struct BetaObservabilityTraces<'a> {
    raw: &'a HttpClient,
}

impl<'a> BetaObservabilityTraces<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn aggregate_traces(
        &self,
        from: Option<String>,
        to: Option<String>,
        request: AggregateTracesBetaObservabilityTracesRequest,
    ) -> Result<AggregateTracesBetaObservabilityTracesResponse, SdkError> {
        self.raw
            .aggregate_traces_v1_observability_traces_aggregate_post(from, to, request.into_raw())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn get_span_by_id(
        &self,
        request: GetSpanByIdBetaObservabilityTracesRequest,
    ) -> Result<GetSpanByIdBetaObservabilityTracesResponse, SdkError> {
        self.raw
            .get_span_by_id_v1_observability_traces_trace_id_spans_span_id_get(
                request.trace_id.as_str(),
                request.span_id.as_str(),
                request.from.as_deref(),
                request.to.as_deref(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn get_trace_by_id(
        &self,
        trace_id: impl AsRef<str>,
    ) -> Result<GetTraceByIdBetaObservabilityTracesResponse, SdkError> {
        self.raw
            .get_trace_by_id_v1_observability_traces_trace_id_get(trace_id.as_ref())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn get_trace_field_options(
        &self,
        request: GetTraceFieldOptionsBetaObservabilityTracesRequest,
    ) -> Result<GetTraceFieldOptionsBetaObservabilityTracesResponse, SdkError> {
        self.raw
            .get_trace_field_options_v1_observability_traces_fields_field_name_options_get(
                request.field_name.as_str(),
                request.from.as_deref(),
                request.to.as_deref(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn get_trace_fields(
        &self,
    ) -> Result<GetTraceFieldsBetaObservabilityTracesResponse, SdkError> {
        self.raw
            .get_trace_fields_v1_observability_traces_fields_get()
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn get_trace_spans(
        &self,
        request: GetTraceSpansBetaObservabilityTracesRequest,
    ) -> Result<GetTraceSpansBetaObservabilityTracesResponse, SdkError> {
        self.raw
            .get_trace_spans_v1_observability_traces_trace_id_spans_get(
                request.trace_id.as_str(),
                request.from.as_deref(),
                request.to.as_deref(),
                request.page_size,
                request.cursor.as_deref(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn search_traces(
        &self,
        from: Option<String>,
        to: Option<String>,
        page_size: Option<i64>,
        cursor: Option<String>,
        request: SearchTracesBetaObservabilityTracesRequest,
    ) -> Result<SearchTracesBetaObservabilityTracesResponse, SdkError> {
        self.raw
            .search_traces_v1_observability_traces_search_post(
                from,
                to,
                page_size,
                cursor,
                request.into_raw(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
