// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;

#[derive(Debug, Clone, Default)]
pub struct GetWorkspacesBetaAdminWorkspacesRequest {
    is_archived: Option<bool>,
    page: Option<i64>,
    page_size: Option<i64>,
    search: Option<String>,
}
impl GetWorkspacesBetaAdminWorkspacesRequest {
    pub fn new() -> Self {
        Self {
            is_archived: None,
            page: None,
            page_size: None,
            search: None,
        }
    }
    #[must_use]
    pub fn is_archived(mut self, is_archived: bool) -> Self {
        self.is_archived = Some(is_archived);
        self
    }
    #[must_use]
    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }
    #[must_use]
    pub fn page_size(mut self, page_size: i64) -> Self {
        self.page_size = Some(page_size);
        self
    }
    #[must_use]
    pub fn search(mut self, search: impl Into<String>) -> Self {
        self.search = Some(search.into());
        self
    }
}

#[derive(Clone, Copy)]
pub struct BetaAdminWorkspaces<'a> {
    raw: &'a HttpClient,
}

impl<'a> BetaAdminWorkspaces<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn add_or_update_users_workspaces(
        &self,
        workspace_uuid: impl AsRef<str>,
        request: AddOrUpdateUsersWorkspacesBetaAdminWorkspacesRequest,
    ) -> Result<AddOrUpdateUsersWorkspacesBetaAdminWorkspacesResponse, SdkError> {
        self.raw
            .users_api_admin_workspaces_add_or_update_users_workspaces(
                workspace_uuid.as_ref(),
                request.into_raw(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn add_users_workspaces(
        &self,
        workspace_uuid: impl AsRef<str>,
        request: AddUsersWorkspacesBetaAdminWorkspacesRequest,
    ) -> Result<AddUsersWorkspacesBetaAdminWorkspacesResponse, SdkError> {
        self.raw
            .users_api_admin_workspaces_add_users_workspaces(
                workspace_uuid.as_ref(),
                request.into_raw(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn create_workspace(
        &self,
        request: CreateWorkspaceBetaAdminWorkspacesRequest,
    ) -> Result<CreateWorkspaceBetaAdminWorkspacesResponse, SdkError> {
        self.raw
            .users_api_admin_workspaces_create_workspace(request.into_raw())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn delete_workspaces(&self, workspace_uuid: impl AsRef<str>) -> Result<(), SdkError> {
        self.raw
            .users_api_admin_workspaces_delete_workspaces(workspace_uuid.as_ref())
            .await
            .map_err(Into::into)
    }

    pub async fn get_workspaces(
        &self,
    ) -> Result<GetWorkspacesBetaAdminWorkspacesResponse, SdkError> {
        self.raw
            .users_api_admin_workspaces_get_workspaces(None, None, None, None::<&str>)
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn get_workspaces_with(
        &self,
        request: GetWorkspacesBetaAdminWorkspacesRequest,
    ) -> Result<GetWorkspacesBetaAdminWorkspacesResponse, SdkError> {
        self.raw
            .users_api_admin_workspaces_get_workspaces(
                request.is_archived,
                request.page,
                request.page_size,
                request.search.as_deref(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn remove_users_workspaces(
        &self,
        workspace_uuid: impl AsRef<str>,
        request: RemoveUsersWorkspacesBetaAdminWorkspacesRequest,
    ) -> Result<RemoveUsersWorkspacesBetaAdminWorkspacesResponse, SdkError> {
        self.raw
            .users_api_admin_workspaces_remove_users_workspaces(
                workspace_uuid.as_ref(),
                request.into_raw(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn update_workspaces(
        &self,
        workspace_uuid: impl AsRef<str>,
        request: UpdateWorkspacesBetaAdminWorkspacesRequest,
    ) -> Result<UpdateWorkspacesBetaAdminWorkspacesResponse, SdkError> {
        self.raw
            .users_api_admin_workspaces_update_workspaces(
                workspace_uuid.as_ref(),
                request.into_raw(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
