// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;

#[derive(Debug, Clone)]
pub struct GetByTimeStatsBetaAdminVibeWorkAnalyticsRequest { start_time: i64, end_time: i64, granularity: Option<String> }
impl GetByTimeStatsBetaAdminVibeWorkAnalyticsRequest { pub fn new(start_time: i64, end_time: i64) -> Self { Self { start_time: start_time, end_time: end_time, granularity: None } }
#[must_use] pub fn granularity(mut self, granularity: impl Into<String>) -> Self { self.granularity = Some(granularity.into()); self }
}

#[derive(Clone, Copy)]
pub struct BetaAdminVibeWorkAnalytics<'a> { raw: &'a HttpClient }

impl<'a> BetaAdminVibeWorkAnalytics<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self { Self { raw } }
    pub async fn get_by_agent_stats(&self, start_time: i64, end_time: i64) -> Result<GetByAgentStatsBetaAdminVibeWorkAnalyticsResponse, SdkError> {
        self.raw.get_by_agent_stats_v1_admin_analytics_vibe_work_usage_by_agent_stats(start_time, end_time).await.map(Into::into).map_err(Into::into)
    }

    pub async fn get_by_time_stats(&self, request: GetByTimeStatsBetaAdminVibeWorkAnalyticsRequest) -> Result<GetByTimeStatsBetaAdminVibeWorkAnalyticsResponse, SdkError> {
        self.raw.get_by_time_stats_v1_admin_analytics_vibe_work_usage_by_time_stats(request.start_time, request.end_time, request.granularity.as_deref()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn get_by_user_stats(&self, start_time: i64, end_time: i64) -> Result<GetByUserStatsBetaAdminVibeWorkAnalyticsResponse, SdkError> {
        self.raw.get_by_user_stats_v1_admin_analytics_vibe_work_usage_by_user_stats(start_time, end_time).await.map(Into::into).map_err(Into::into)
    }
}
