// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;



#[derive(Clone, Copy)]
pub struct BetaRagSearchIndexes<'a> { raw: &'a HttpClient }

impl<'a> BetaRagSearchIndexes<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self { Self { raw } }
    pub async fn get_deployment_summaries(&self) -> Result<GetDeploymentSummariesBetaRagSearchIndexesResponse, SdkError> {
        self.raw.get_deployment_summaries_v1_rag_deployments_get().await.map(Into::into).map_err(Into::into)
    }

    pub async fn register_deployment(&self, request: RegisterDeploymentBetaRagSearchIndexesRequest) -> Result<RegisterDeploymentBetaRagSearchIndexesResponse, SdkError> {
        self.raw.register_deployment_v1_rag_deployments_put(request.into_raw()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn unregister_deployment(&self, deployment_id: impl AsRef<str>) -> Result<UnregisterDeploymentBetaRagSearchIndexesResponse, SdkError> {
        self.raw.unregister_deployment_v1_rag_deployments_deployment_id_delete(deployment_id.as_ref()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn update_index_metrics(&self, deployment_id: impl AsRef<str>, request: UpdateIndexMetricsBetaRagSearchIndexesRequest) -> Result<UpdateIndexMetricsBetaRagSearchIndexesResponse, SdkError> {
        self.raw.update_index_metrics_v1_rag_deployments_deployment_id_metrics_put(deployment_id.as_ref(), request.into_raw()).await.map(Into::into).map_err(Into::into)
    }
}
