// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;
use crate::generated::types::*;
use futures_util::StreamExt;

#[derive(Debug, Clone, Default)]
pub struct ListBetaConversationsRequest {
    page: Option<i64>,
    page_size: Option<i64>,
    metadata: Option<String>,
}
impl ListBetaConversationsRequest {
    pub fn new() -> Self {
        Self {
            page: None,
            page_size: None,
            metadata: None,
        }
    }
    #[must_use]
    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }
    #[must_use]
    pub fn page_size(mut self, page_size: i64) -> Self {
        self.page_size = Some(page_size);
        self
    }
    #[must_use]
    pub fn metadata(mut self, metadata: impl Into<String>) -> Self {
        self.metadata = Some(metadata.into());
        self
    }
}

#[derive(Clone, Copy)]
pub struct BetaConversations<'a> {
    raw: &'a HttpClient,
}

impl<'a> BetaConversations<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn append(
        &self,
        conversation_id: impl AsRef<str>,
        request: AppendBetaConversationsRequest,
    ) -> Result<AppendBetaConversationsResponse, SdkError> {
        self.raw
            .agents_api_v1_conversations_append(conversation_id.as_ref(), {
                let mut raw = <AppendBetaConversationsRequest as __RustSdkIntoRaw<
                    crate::generated::types::ConversationAppendRequest,
                >>::into_raw(request);
                raw.stream = Some(false);
                raw
            })
            .await
            .map(__RustSdkFromRaw::from_raw)
            .map_err(Into::into)
    }

    pub async fn append_stream(
        &self,
        conversation_id: impl AsRef<str>,
        request: AppendStreamBetaConversationsRequest,
    ) -> Result<AppendStreamBetaConversationsStream, SdkError> {
        let bytes = self
            .raw
            .agents_api_v1_conversations_append_stream(conversation_id.as_ref(), {
                let mut raw = <AppendStreamBetaConversationsRequest as __RustSdkIntoRaw<
                    crate::generated::types::ConversationAppendStreamRequest,
                >>::into_raw(request);
                raw.stream = Some(true);
                raw
            })
            .await
            .map_err(SdkError::from)?;
        let events =
            crate::streaming::json_events::<_, _, ConversationEvents>(bytes).map(|event| {
                event
                    .map(|event| __RustSdkFromRaw::from_raw(event.data))
                    .map_err(Into::into)
            });
        Ok(Box::pin(events))
    }

    pub async fn delete(&self, conversation_id: impl AsRef<str>) -> Result<(), SdkError> {
        self.raw
            .agents_api_v1_conversations_delete(conversation_id.as_ref())
            .await
            .map_err(Into::into)
    }

    pub async fn get(
        &self,
        conversation_id: impl AsRef<str>,
    ) -> Result<GetBetaConversationsResponse, SdkError> {
        self.raw
            .agents_api_v1_conversations_get(conversation_id.as_ref())
            .await
            .map(__RustSdkFromRaw::from_raw)
            .map_err(Into::into)
    }

    pub async fn get_history(
        &self,
        conversation_id: impl AsRef<str>,
    ) -> Result<GetHistoryBetaConversationsResponse, SdkError> {
        self.raw
            .agents_api_v1_conversations_history(conversation_id.as_ref())
            .await
            .map(__RustSdkFromRaw::from_raw)
            .map_err(Into::into)
    }

    pub async fn get_messages(
        &self,
        conversation_id: impl AsRef<str>,
    ) -> Result<GetMessagesBetaConversationsResponse, SdkError> {
        self.raw
            .agents_api_v1_conversations_messages(conversation_id.as_ref())
            .await
            .map(__RustSdkFromRaw::from_raw)
            .map_err(Into::into)
    }

    pub async fn list(&self) -> Result<ListBetaConversationsResponse, SdkError> {
        self.raw
            .agents_api_v1_conversations_list(None, None, None::<&str>)
            .await
            .map(__RustSdkFromRaw::from_raw)
            .map_err(Into::into)
    }

    pub async fn list_with(
        &self,
        request: ListBetaConversationsRequest,
    ) -> Result<ListBetaConversationsResponse, SdkError> {
        self.raw
            .agents_api_v1_conversations_list(
                request.page,
                request.page_size,
                request.metadata.as_deref(),
            )
            .await
            .map(__RustSdkFromRaw::from_raw)
            .map_err(Into::into)
    }

    pub async fn restart(
        &self,
        conversation_id: impl AsRef<str>,
        request: RestartBetaConversationsRequest,
    ) -> Result<RestartBetaConversationsResponse, SdkError> {
        self.raw
            .agents_api_v1_conversations_restart(conversation_id.as_ref(), {
                let mut raw = <RestartBetaConversationsRequest as __RustSdkIntoRaw<
                    crate::generated::types::ConversationRestartRequest,
                >>::into_raw(request);
                raw.stream = Some(false);
                raw
            })
            .await
            .map(__RustSdkFromRaw::from_raw)
            .map_err(Into::into)
    }

    pub async fn restart_stream(
        &self,
        conversation_id: impl AsRef<str>,
        request: RestartStreamBetaConversationsRequest,
    ) -> Result<RestartStreamBetaConversationsStream, SdkError> {
        let bytes = self
            .raw
            .agents_api_v1_conversations_restart_stream(conversation_id.as_ref(), {
                let mut raw = <RestartStreamBetaConversationsRequest as __RustSdkIntoRaw<
                    crate::generated::types::ConversationRestartStreamRequest,
                >>::into_raw(request);
                raw.stream = Some(true);
                raw
            })
            .await
            .map_err(SdkError::from)?;
        let events =
            crate::streaming::json_events::<_, _, ConversationEvents>(bytes).map(|event| {
                event
                    .map(|event| __RustSdkFromRaw::from_raw(event.data))
                    .map_err(Into::into)
            });
        Ok(Box::pin(events))
    }

    pub async fn start(
        &self,
        request: StartBetaConversationsRequest,
    ) -> Result<StartBetaConversationsResponse, SdkError> {
        self.raw
            .agents_api_v1_conversations_start({
                let mut raw = <StartBetaConversationsRequest as __RustSdkIntoRaw<
                    crate::generated::types::ConversationRequest,
                >>::into_raw(request);
                raw.stream = Some(false);
                raw
            })
            .await
            .map(__RustSdkFromRaw::from_raw)
            .map_err(Into::into)
    }

    pub async fn start_stream(
        &self,
        request: StartStreamBetaConversationsRequest,
    ) -> Result<StartStreamBetaConversationsStream, SdkError> {
        let bytes = self
            .raw
            .agents_api_v1_conversations_start_stream({
                let mut raw = <StartStreamBetaConversationsRequest as __RustSdkIntoRaw<
                    crate::generated::types::ConversationStreamRequest,
                >>::into_raw(request);
                raw.stream = Some(true);
                raw
            })
            .await
            .map_err(SdkError::from)?;
        let events =
            crate::streaming::json_events::<_, _, ConversationEvents>(bytes).map(|event| {
                event
                    .map(|event| __RustSdkFromRaw::from_raw(event.data))
                    .map_err(Into::into)
            });
        Ok(Box::pin(events))
    }
}
