// @generated by tooling/pipeline/compile_sdk.py; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;

#[derive(Debug, Clone)]
pub struct GetAuthUrlBetaConnectorsRequest {
    connector_id_or_name: String,
    app_return_url: Option<String>,
    credentials_name: Option<String>,
}
impl GetAuthUrlBetaConnectorsRequest {
    pub fn new(connector_id_or_name: impl Into<String>) -> Self {
        Self {
            connector_id_or_name: connector_id_or_name.into(),
            app_return_url: None,
            credentials_name: None,
        }
    }
    #[must_use]
    pub fn app_return_url(mut self, app_return_url: impl Into<String>) -> Self {
        self.app_return_url = Some(app_return_url.into());
        self
    }
    #[must_use]
    pub fn credentials_name(mut self, credentials_name: impl Into<String>) -> Self {
        self.credentials_name = Some(credentials_name.into());
        self
    }
}

#[derive(Debug, Clone)]
pub struct GetBetaConnectorsRequest {
    connector_id_or_name: String,
    fetch_customer_data: Option<bool>,
    fetch_connection_secrets: Option<bool>,
}
impl GetBetaConnectorsRequest {
    pub fn new(connector_id_or_name: impl Into<String>) -> Self {
        Self {
            connector_id_or_name: connector_id_or_name.into(),
            fetch_customer_data: None,
            fetch_connection_secrets: None,
        }
    }
    #[must_use]
    pub fn fetch_customer_data(mut self, fetch_customer_data: bool) -> Self {
        self.fetch_customer_data = Some(fetch_customer_data);
        self
    }
    #[must_use]
    pub fn fetch_connection_secrets(mut self, fetch_connection_secrets: bool) -> Self {
        self.fetch_connection_secrets = Some(fetch_connection_secrets);
        self
    }
}

#[derive(Debug, Clone)]
pub struct ListOrganizationCredentialsBetaConnectorsRequest {
    connector_id_or_name: String,
    auth_type: Option<String>,
    fetch_default: Option<bool>,
}
impl ListOrganizationCredentialsBetaConnectorsRequest {
    pub fn new(connector_id_or_name: impl Into<String>) -> Self {
        Self {
            connector_id_or_name: connector_id_or_name.into(),
            auth_type: None,
            fetch_default: None,
        }
    }
    #[must_use]
    pub fn auth_type(mut self, auth_type: impl Into<String>) -> Self {
        self.auth_type = Some(auth_type.into());
        self
    }
    #[must_use]
    pub fn fetch_default(mut self, fetch_default: bool) -> Self {
        self.fetch_default = Some(fetch_default);
        self
    }
}

#[derive(Debug, Clone)]
pub struct ListUserCredentialsBetaConnectorsRequest {
    connector_id_or_name: String,
    auth_type: Option<String>,
    fetch_default: Option<bool>,
}
impl ListUserCredentialsBetaConnectorsRequest {
    pub fn new(connector_id_or_name: impl Into<String>) -> Self {
        Self {
            connector_id_or_name: connector_id_or_name.into(),
            auth_type: None,
            fetch_default: None,
        }
    }
    #[must_use]
    pub fn auth_type(mut self, auth_type: impl Into<String>) -> Self {
        self.auth_type = Some(auth_type.into());
        self
    }
    #[must_use]
    pub fn fetch_default(mut self, fetch_default: bool) -> Self {
        self.fetch_default = Some(fetch_default);
        self
    }
}

#[derive(Debug, Clone, Default)]
pub struct ListBetaConnectorsRequest {
    query_filters: Option<crate::generated::types::ConnectorsQueryFilters>,
    cursor: Option<String>,
    page_size: Option<i64>,
}
impl ListBetaConnectorsRequest {
    pub fn new() -> Self {
        Self {
            query_filters: None,
            cursor: None,
            page_size: None,
        }
    }
    #[must_use]
    pub fn query_filters(
        mut self,
        query_filters: crate::generated::types::ConnectorsQueryFilters,
    ) -> Self {
        self.query_filters = Some(query_filters);
        self
    }
    #[must_use]
    pub fn cursor(mut self, cursor: impl Into<String>) -> Self {
        self.cursor = Some(cursor.into());
        self
    }
    #[must_use]
    pub fn page_size(mut self, page_size: i64) -> Self {
        self.page_size = Some(page_size);
        self
    }
}

#[derive(Debug, Clone)]
pub struct ListWorkspaceCredentialsBetaConnectorsRequest {
    connector_id_or_name: String,
    auth_type: Option<String>,
    fetch_default: Option<bool>,
}
impl ListWorkspaceCredentialsBetaConnectorsRequest {
    pub fn new(connector_id_or_name: impl Into<String>) -> Self {
        Self {
            connector_id_or_name: connector_id_or_name.into(),
            auth_type: None,
            fetch_default: None,
        }
    }
    #[must_use]
    pub fn auth_type(mut self, auth_type: impl Into<String>) -> Self {
        self.auth_type = Some(auth_type.into());
        self
    }
    #[must_use]
    pub fn fetch_default(mut self, fetch_default: bool) -> Self {
        self.fetch_default = Some(fetch_default);
        self
    }
}

#[derive(Clone, Copy)]
pub struct BetaConnectors<'a> {
    raw: &'a HttpClient,
}

impl<'a> BetaConnectors<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn call_tool(
        &self,
        tool_name: impl AsRef<str>,
        connector_id_or_name: impl AsRef<str>,
        credentials_name: Option<String>,
        request: MCPToolCallRequestParams,
    ) -> Result<MCPToolCallResponseView, SdkError> {
        self.raw
            .connector_call_tool_v1(
                tool_name.as_ref(),
                connector_id_or_name.as_ref(),
                credentials_name,
                request.into_raw(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn create_or_update_organization_credentials(
        &self,
        connector_id_or_name: impl AsRef<str>,
        request: CredentialsCreateOrUpdateParams,
    ) -> Result<MessageResponseView, SdkError> {
        self.raw
            .connector_create_or_update_organization_credentials_v1(
                connector_id_or_name.as_ref(),
                request.into_raw(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn create_or_update_user_credentials(
        &self,
        connector_id_or_name: impl AsRef<str>,
        request: CredentialsCreateOrUpdateParams,
    ) -> Result<MessageResponseView, SdkError> {
        self.raw
            .connector_create_or_update_user_credentials_v1(
                connector_id_or_name.as_ref(),
                request.into_raw(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn create_or_update_workspace_credentials(
        &self,
        connector_id_or_name: impl AsRef<str>,
        request: CredentialsCreateOrUpdateParams,
    ) -> Result<MessageResponseView, SdkError> {
        self.raw
            .connector_create_or_update_workspace_credentials_v1(
                connector_id_or_name.as_ref(),
                request.into_raw(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn create(
        &self,
        request: ConnectorMCPCreateParams,
    ) -> Result<ConnectorView, SdkError> {
        self.raw
            .connector_create_v1(request.into_raw())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn delete_organization_credentials(
        &self,
        credentials_name: impl AsRef<str>,
        connector_id_or_name: impl AsRef<str>,
    ) -> Result<MessageResponseView, SdkError> {
        self.raw
            .connector_delete_organization_credentials_v1(
                credentials_name.as_ref(),
                connector_id_or_name.as_ref(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn delete_user_credentials(
        &self,
        credentials_name: impl AsRef<str>,
        connector_id_or_name: impl AsRef<str>,
    ) -> Result<MessageResponseView, SdkError> {
        self.raw
            .connector_delete_user_credentials_v1(
                credentials_name.as_ref(),
                connector_id_or_name.as_ref(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn delete(
        &self,
        connector_id: impl AsRef<str>,
    ) -> Result<MessageResponseView, SdkError> {
        self.raw
            .connector_delete_v1(connector_id.as_ref())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn delete_workspace_credentials(
        &self,
        credentials_name: impl AsRef<str>,
        connector_id_or_name: impl AsRef<str>,
    ) -> Result<MessageResponseView, SdkError> {
        self.raw
            .connector_delete_workspace_credentials_v1(
                credentials_name.as_ref(),
                connector_id_or_name.as_ref(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn get_auth_url(
        &self,
        request: GetAuthUrlBetaConnectorsRequest,
    ) -> Result<AuthUrlResponseView, SdkError> {
        self.raw
            .connector_get_auth_url_v1(
                request.connector_id_or_name.as_str(),
                request.app_return_url.as_deref(),
                request.credentials_name.as_deref(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn get(&self, request: GetBetaConnectorsRequest) -> Result<ConnectorView, SdkError> {
        self.raw
            .connector_get_v1(
                request.connector_id_or_name.as_str(),
                request.fetch_customer_data,
                request.fetch_connection_secrets,
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn list_organization_credentials(
        &self,
        request: ListOrganizationCredentialsBetaConnectorsRequest,
    ) -> Result<CredentialsResponseView, SdkError> {
        self.raw
            .connector_list_organization_credentials_v1(
                request.connector_id_or_name.as_str(),
                request.auth_type.as_deref(),
                request.fetch_default,
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn list_user_credentials(
        &self,
        request: ListUserCredentialsBetaConnectorsRequest,
    ) -> Result<CredentialsResponseView, SdkError> {
        self.raw
            .connector_list_user_credentials_v1(
                request.connector_id_or_name.as_str(),
                request.auth_type.as_deref(),
                request.fetch_default,
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn list(&self) -> Result<PaginatedConnectorsView, SdkError> {
        self.raw
            .connector_list_v1(None, None::<&str>, None)
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn list_with(
        &self,
        request: ListBetaConnectorsRequest,
    ) -> Result<PaginatedConnectorsView, SdkError> {
        self.raw
            .connector_list_v1(
                request.query_filters,
                request.cursor.as_deref(),
                request.page_size,
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn list_workspace_credentials(
        &self,
        request: ListWorkspaceCredentialsBetaConnectorsRequest,
    ) -> Result<CredentialsResponseView, SdkError> {
        self.raw
            .connector_list_workspace_credentials_v1(
                request.connector_id_or_name.as_str(),
                request.auth_type.as_deref(),
                request.fetch_default,
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn update(
        &self,
        connector_id: impl AsRef<str>,
        request: ConnectorMCPUpdateParams,
    ) -> Result<ConnectorView, SdkError> {
        self.raw
            .connector_update_v1(connector_id.as_ref(), request.into_raw())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
