// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;

#[derive(Debug, Clone, Default)]
pub struct UsageGetUsageBetaAdminBillingRequest {
    month: Option<String>,
    year: Option<String>,
    workspace_id: Option<String>,
    api_zone: Option<String>,
}
impl UsageGetUsageBetaAdminBillingRequest {
    pub fn new() -> Self {
        Self {
            month: None,
            year: None,
            workspace_id: None,
            api_zone: None,
        }
    }
    #[must_use]
    pub fn month(mut self, month: impl Into<String>) -> Self {
        self.month = Some(month.into());
        self
    }
    #[must_use]
    pub fn year(mut self, year: impl Into<String>) -> Self {
        self.year = Some(year.into());
        self
    }
    #[must_use]
    pub fn workspace_id(mut self, workspace_id: impl Into<String>) -> Self {
        self.workspace_id = Some(workspace_id.into());
        self
    }
    #[must_use]
    pub fn api_zone(mut self, api_zone: impl Into<String>) -> Self {
        self.api_zone = Some(api_zone.into());
        self
    }
}
#[derive(Clone, Copy)]
pub struct BetaAdminBilling<'a> {
    raw: &'a HttpClient,
}

impl<'a> BetaAdminBilling<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn rate_limits_get_rate_limits(
        &self,
    ) -> Result<RateLimitsGetRateLimitsBetaAdminBillingResponse, SdkError> {
        self.raw
            .users_api_admin_rate_limits_get_rate_limits()
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn spend_limits_get_spend_limits(
        &self,
    ) -> Result<SpendLimitsGetSpendLimitsBetaAdminBillingResponse, SdkError> {
        self.raw
            .users_api_admin_spend_limits_get_spend_limits()
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn spend_limits_update_spend_limits(
        &self,
        request: SpendLimitsUpdateSpendLimitsBetaAdminBillingRequest,
    ) -> Result<SpendLimitsUpdateSpendLimitsBetaAdminBillingResponse, SdkError> {
        self.raw
            .users_api_admin_spend_limits_update_spend_limits(request.into_raw())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn usage_get_usage(&self) -> Result<UsageGetUsageBetaAdminBillingResponse, SdkError> {
        self.raw
            .users_api_admin_usage_get_usage(None::<&str>, None::<&str>, None::<&str>, None::<&str>)
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn usage_get_usage_with(
        &self,
        request: UsageGetUsageBetaAdminBillingRequest,
    ) -> Result<UsageGetUsageBetaAdminBillingResponse, SdkError> {
        self.raw
            .users_api_admin_usage_get_usage(
                request.month.as_deref(),
                request.year.as_deref(),
                request.workspace_id.as_deref(),
                request.api_zone.as_deref(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
