// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;

#[derive(Clone, Copy)]
pub struct BetaAdminScim<'a> {
    raw: &'a HttpClient,
}

impl<'a> BetaAdminScim<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn get_scim_sync_run(
        &self,
        run_id: impl AsRef<str>,
    ) -> Result<GetScimSyncRunBetaAdminScimResponse, SdkError> {
        self.raw
            .users_api_admin_scim_sync_get_scim_sync_run(run_id.as_ref())
            .await
            .map(__RustSdkFromRaw::from_raw)
            .map_err(Into::into)
    }

    pub async fn trigger_scim_sync(
        &self,
        request: TriggerScimSyncBetaAdminScimRequest,
    ) -> Result<TriggerScimSyncBetaAdminScimResponse, SdkError> {
        self.raw
            .users_api_admin_scim_sync_trigger_scim_sync(
                <TriggerScimSyncBetaAdminScimRequest as __RustSdkIntoRaw<
                    crate::generated::types::AdminScimSyncTriggerIN,
                >>::into_raw(request),
            )
            .await
            .map(__RustSdkFromRaw::from_raw)
            .map_err(Into::into)
    }
}
