// @generated by codegen/sdk_facade.py; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;
#[derive(Clone, Copy)]
pub struct BetaLibrariesAccesses<'a> {
    raw: &'a HttpClient,
}

impl<'a> BetaLibrariesAccesses<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn list(&self, library_id: impl AsRef<str>) -> Result<ListSharingOutView, SdkError> {
        self.raw
            .libraries_share_list_v1(library_id.as_ref())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
