// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;

#[derive(Debug, Clone)]
pub struct GetBetaPromptsRequest {
    prompt_id: String,
    version: Option<i32>,
    alias: Option<String>,
    fields: Option<Vec<String>>,
}
impl GetBetaPromptsRequest {
    pub fn new(prompt_id: impl Into<String>) -> Self {
        Self {
            prompt_id: prompt_id.into(),
            version: None,
            alias: None,
            fields: None,
        }
    }
    #[must_use]
    pub fn version(mut self, version: i32) -> Self {
        self.version = Some(version);
        self
    }
    #[must_use]
    pub fn alias(mut self, alias: impl Into<String>) -> Self {
        self.alias = Some(alias.into());
        self
    }
    #[must_use]
    pub fn fields(mut self, fields: Vec<String>) -> Self {
        self.fields = Some(fields);
        self
    }
}

#[derive(Debug, Clone)]
pub struct GetVersionBetaPromptsRequest {
    prompt_id: String,
    version: i32,
    fields: Option<Vec<String>>,
}
impl GetVersionBetaPromptsRequest {
    pub fn new(prompt_id: impl Into<String>, version: i32) -> Self {
        Self {
            prompt_id: prompt_id.into(),
            version: version,
            fields: None,
        }
    }
    #[must_use]
    pub fn fields(mut self, fields: Vec<String>) -> Self {
        self.fields = Some(fields);
        self
    }
}

#[derive(Debug, Clone, Default)]
pub struct ListBetaPromptsRequest {
    page_size: Option<i32>,
    page_token: Option<String>,
    alias: Option<String>,
    fields: Option<Vec<String>>,
    sort_field: Option<crate::generated::types::ListSortField>,
    sort_direction: Option<crate::generated::types::ListSortDirection>,
    sort_by: Option<String>,
    sort_direction_2: Option<String>,
}
impl ListBetaPromptsRequest {
    pub fn new() -> Self {
        Self {
            page_size: None,
            page_token: None,
            alias: None,
            fields: None,
            sort_field: None,
            sort_direction: None,
            sort_by: None,
            sort_direction_2: None,
        }
    }
    #[must_use]
    pub fn page_size(mut self, page_size: i32) -> Self {
        self.page_size = Some(page_size);
        self
    }
    #[must_use]
    pub fn page_token(mut self, page_token: impl Into<String>) -> Self {
        self.page_token = Some(page_token.into());
        self
    }
    #[must_use]
    pub fn alias(mut self, alias: impl Into<String>) -> Self {
        self.alias = Some(alias.into());
        self
    }
    #[must_use]
    pub fn fields(mut self, fields: Vec<String>) -> Self {
        self.fields = Some(fields);
        self
    }
    #[must_use]
    pub fn sort_field(mut self, sort_field: crate::generated::types::ListSortField) -> Self {
        self.sort_field = Some(sort_field);
        self
    }
    #[must_use]
    pub fn sort_direction(
        mut self,
        sort_direction: crate::generated::types::ListSortDirection,
    ) -> Self {
        self.sort_direction = Some(sort_direction);
        self
    }
    #[must_use]
    pub fn sort_by(mut self, sort_by: impl Into<String>) -> Self {
        self.sort_by = Some(sort_by.into());
        self
    }
    #[must_use]
    pub fn sort_direction_2(mut self, sort_direction_2: impl Into<String>) -> Self {
        self.sort_direction_2 = Some(sort_direction_2.into());
        self
    }
}

#[derive(Clone, Copy)]
pub struct BetaPrompts<'a> {
    raw: &'a HttpClient,
}

impl<'a> BetaPrompts<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn create(
        &self,
        request: CreateBetaPromptsRequest,
    ) -> Result<CreateBetaPromptsResponse, SdkError> {
        self.raw
            .prompts_create(request.into_raw())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn create_version(
        &self,
        prompt_id: impl AsRef<str>,
        request: CreateVersionBetaPromptsRequest,
    ) -> Result<CreateVersionBetaPromptsResponse, SdkError> {
        self.raw
            .prompts_create_version(prompt_id.as_ref(), request.into_raw())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn delete(
        &self,
        prompt_id: impl AsRef<str>,
    ) -> Result<DeleteBetaPromptsResponse, SdkError> {
        self.raw
            .prompts_delete(prompt_id.as_ref())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn get(
        &self,
        request: GetBetaPromptsRequest,
    ) -> Result<GetBetaPromptsResponse, SdkError> {
        self.raw
            .prompts_get(
                request.prompt_id.as_str(),
                request.version,
                request.alias.as_deref(),
                request.fields,
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn get_version(
        &self,
        request: GetVersionBetaPromptsRequest,
    ) -> Result<GetVersionBetaPromptsResponse, SdkError> {
        self.raw
            .prompts_get_version(request.prompt_id.as_str(), request.version, request.fields)
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn list(&self) -> Result<ListBetaPromptsResponse, SdkError> {
        self.raw
            .prompts_list(
                None,
                None::<&str>,
                None::<&str>,
                None,
                None,
                None,
                None::<&str>,
                None::<&str>,
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn list_with(
        &self,
        request: ListBetaPromptsRequest,
    ) -> Result<ListBetaPromptsResponse, SdkError> {
        self.raw
            .prompts_list(
                request.page_size,
                request.page_token.as_deref(),
                request.alias.as_deref(),
                request.fields,
                request.sort_field,
                request.sort_direction,
                request.sort_by.as_deref(),
                request.sort_direction_2.as_deref(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn list_versions(
        &self,
        prompt_id: impl AsRef<str>,
    ) -> Result<ListVersionsBetaPromptsResponse, SdkError> {
        self.raw
            .prompts_list_versions(prompt_id.as_ref())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn update(
        &self,
        prompt_id: impl AsRef<str>,
        request: UpdateBetaPromptsRequest,
    ) -> Result<UpdateBetaPromptsResponse, SdkError> {
        self.raw
            .prompts_update(prompt_id.as_ref(), request.into_raw())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn update_version_metadata(
        &self,
        prompt_id: impl AsRef<str>,
        version: i32,
        request: UpdateVersionMetadataBetaPromptsRequest,
    ) -> Result<UpdateVersionMetadataBetaPromptsResponse, SdkError> {
        self.raw
            .prompts_update_version_metadata(prompt_id.as_ref(), version, request.into_raw())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
