// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;

#[derive(Debug, Clone)]
pub struct GetBetaAgentsRequest {
    agent_id: String,
    agent_version: Option<String>,
}
impl GetBetaAgentsRequest {
    pub fn new(agent_id: impl Into<String>) -> Self {
        Self {
            agent_id: agent_id.into(),
            agent_version: None,
        }
    }
    #[must_use]
    pub fn agent_version(mut self, agent_version: impl Into<String>) -> Self {
        self.agent_version = Some(agent_version.into());
        self
    }
}

#[derive(Debug, Clone, Default)]
pub struct ListPagesBetaAgentsRequest {
    page_size: Option<i64>,
    deployment_chat: Option<String>,
    sources: Option<String>,
    name: Option<String>,
    search: Option<String>,
    id: Option<String>,
    metadata: Option<String>,
    page_token: Option<String>,
}
impl ListPagesBetaAgentsRequest {
    pub fn new() -> Self {
        Self {
            page_size: None,
            deployment_chat: None,
            sources: None,
            name: None,
            search: None,
            id: None,
            metadata: None,
            page_token: None,
        }
    }
    #[must_use]
    pub fn page_size(mut self, page_size: i64) -> Self {
        self.page_size = Some(page_size);
        self
    }
    #[must_use]
    pub fn deployment_chat(mut self, deployment_chat: impl Into<String>) -> Self {
        self.deployment_chat = Some(deployment_chat.into());
        self
    }
    #[must_use]
    pub fn sources(mut self, sources: impl Into<String>) -> Self {
        self.sources = Some(sources.into());
        self
    }
    #[must_use]
    pub fn name(mut self, name: impl Into<String>) -> Self {
        self.name = Some(name.into());
        self
    }
    #[must_use]
    pub fn search(mut self, search: impl Into<String>) -> Self {
        self.search = Some(search.into());
        self
    }
    #[must_use]
    pub fn id(mut self, id: impl Into<String>) -> Self {
        self.id = Some(id.into());
        self
    }
    #[must_use]
    pub fn metadata(mut self, metadata: impl Into<String>) -> Self {
        self.metadata = Some(metadata.into());
        self
    }
    #[must_use]
    pub fn page_token(mut self, page_token: impl Into<String>) -> Self {
        self.page_token = Some(page_token.into());
        self
    }
}

#[derive(Clone, Copy)]
pub struct BetaAgents<'a> {
    raw: &'a HttpClient,
}

impl<'a> BetaAgents<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn create_version_alias(
        &self,
        agent_id: impl AsRef<str>,
        alias: impl AsRef<str>,
        version: i64,
    ) -> Result<AgentAliasResponseView, SdkError> {
        self.raw
            .agents_api_v1_agents_create_or_update_alias(agent_id.as_ref(), alias.as_ref(), version)
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn delete(&self, agent_id: impl AsRef<str>) -> Result<(), SdkError> {
        self.raw
            .agents_api_v1_agents_delete(agent_id.as_ref())
            .await
            .map_err(Into::into)
    }

    pub async fn delete_version_alias(
        &self,
        agent_id: impl AsRef<str>,
        alias: impl AsRef<str>,
    ) -> Result<(), SdkError> {
        self.raw
            .agents_api_v1_agents_delete_alias(agent_id.as_ref(), alias.as_ref())
            .await
            .map_err(Into::into)
    }

    pub async fn get(&self, request: GetBetaAgentsRequest) -> Result<AgentView, SdkError> {
        self.raw
            .agents_api_v1_agents_get(request.agent_id.as_str(), request.agent_version.as_deref())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn get_version(
        &self,
        agent_id: impl AsRef<str>,
        version: impl AsRef<str>,
    ) -> Result<AgentView, SdkError> {
        self.raw
            .agents_api_v1_agents_get_version(agent_id.as_ref(), version.as_ref())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn list_pages(&self) -> Result<AgentListPageView, SdkError> {
        self.raw
            .agents_api_v1_agents_list_pages(
                None,
                None::<&str>,
                None::<&str>,
                None::<&str>,
                None::<&str>,
                None::<&str>,
                None::<&str>,
                None::<&str>,
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn list_pages_with(
        &self,
        request: ListPagesBetaAgentsRequest,
    ) -> Result<AgentListPageView, SdkError> {
        self.raw
            .agents_api_v1_agents_list_pages(
                request.page_size,
                request.deployment_chat.as_deref(),
                request.sources.as_deref(),
                request.name.as_deref(),
                request.search.as_deref(),
                request.id.as_deref(),
                request.metadata.as_deref(),
                request.page_token.as_deref(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn update_version(
        &self,
        agent_id: impl AsRef<str>,
        version: i64,
    ) -> Result<AgentView, SdkError> {
        self.raw
            .agents_api_v1_agents_update_version(agent_id.as_ref(), version)
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
