// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;
use crate::generated::types::*;
use futures_util::StreamExt;

#[derive(Clone, Copy)]
pub struct Chat<'a> {
    raw: &'a HttpClient,
}

impl<'a> Chat<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn complete(
        &self,
        request: CompleteChatRequest,
    ) -> Result<CompleteChatResponse, SdkError> {
        self.raw
            .chat_completion_v1_chat_completions_post({
                let mut raw = <CompleteChatRequest as __RustSdkIntoRaw<
                    crate::generated::types::ChatCompletionRequest,
                >>::into_raw(request);
                raw.stream = Some(false);
                raw
            })
            .await
            .map(__RustSdkFromRaw::from_raw)
            .map_err(Into::into)
    }

    pub async fn parse(&self, request: ParseChatRequest) -> Result<ParseChatResponse, SdkError> {
        self.raw
            .chat_completion_v1_chat_completions_post({
                let mut raw = <ParseChatRequest as __RustSdkIntoRaw<
                    crate::generated::types::ChatCompletionRequest,
                >>::into_raw(request);
                raw.stream = Some(false);
                raw
            })
            .await
            .map(__RustSdkFromRaw::from_raw)
            .map_err(Into::into)
    }

    pub async fn parse_stream(
        &self,
        request: ParseStreamChatRequest,
    ) -> Result<ParseStreamChatStream, SdkError> {
        let bytes = self
            .raw
            .chat_completion_v1_chat_completions_post_stream({
                let mut raw = <ParseStreamChatRequest as __RustSdkIntoRaw<
                    crate::generated::types::ChatCompletionRequest,
                >>::into_raw(request);
                raw.stream = Some(true);
                raw
            })
            .await
            .map_err(SdkError::from)?;
        let events = crate::streaming::json_events::<_, _, CompletionChunk>(bytes).map(|event| {
            event
                .map(|event| __RustSdkFromRaw::from_raw(event.data))
                .map_err(Into::into)
        });
        Ok(Box::pin(events))
    }

    pub async fn stream(&self, request: StreamChatRequest) -> Result<StreamChatStream, SdkError> {
        let bytes = self
            .raw
            .chat_completion_v1_chat_completions_post_stream({
                let mut raw = <StreamChatRequest as __RustSdkIntoRaw<
                    crate::generated::types::ChatCompletionRequest,
                >>::into_raw(request);
                raw.stream = Some(true);
                raw
            })
            .await
            .map_err(SdkError::from)?;
        let events = crate::streaming::json_events::<_, _, CompletionChunk>(bytes).map(|event| {
            event
                .map(|event| __RustSdkFromRaw::from_raw(event.data))
                .map_err(Into::into)
        });
        Ok(Box::pin(events))
    }
}
