// @generated by codegen/sdk_facade.py; do not edit by hand.
use std::pin::Pin;

use futures_util::{Stream, StreamExt};

use super::SdkError;
use crate::generated::client::HttpClient;
use crate::generated::types::*;
use crate::streaming;

/// A chat message with textual content.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum Message {
    System(String),
    User(String),
    Assistant(String),
}

impl Message {
    pub fn system(content: impl Into<String>) -> Self {
        Self::System(content.into())
    }
    pub fn user(content: impl Into<String>) -> Self {
        Self::User(content.into())
    }
    pub fn assistant(content: impl Into<String>) -> Self {
        Self::Assistant(content.into())
    }
}

impl From<Message> for ChatCompletionRequestMessagesItemUnion {
    fn from(message: Message) -> Self {
        match message {
            Message::System(content) => Self::SystemMessage(SystemMessage {
                content: SystemMessageContent::String(content),
                role: None,
            }),
            Message::User(content) => Self::UserMessage(UserMessage {
                content: Some(UserMessageContent::String(content)),
                role: None,
            }),
            Message::Assistant(content) => Self::AssistantMessage(AssistantMessage {
                content: Some(Some(AssistantMessageContent::String(content))),
                prefix: None,
                role: None,
                tool_calls: None,
            }),
        }
    }
}

/// A generated ergonomic wrapper over [`ChatCompletionRequest`].
#[derive(Debug, Clone)]
pub struct ChatRequest {
    raw: ChatCompletionRequest,
}

impl ChatRequest {
    pub fn new(model: impl Into<String>, messages: impl IntoIterator<Item = Message>) -> Self {
        Self {
            raw: ChatCompletionRequest::new(
                messages.into_iter().map(Into::into).collect(),
                model.into(),
            ),
        }
    }

    pub fn from_raw(raw: ChatCompletionRequest) -> Self {
        Self { raw }
    }

    #[must_use]
    pub fn frequency_penalty(mut self, frequency_penalty: f64) -> Self {
        self.raw.frequency_penalty = Some(frequency_penalty);
        self
    }

    #[must_use]
    pub fn guardrails(mut self, guardrails: Vec<GuardrailConfig>) -> Self {
        self.raw.guardrails = Some(Some(guardrails));
        self
    }

    #[must_use]
    pub fn guardrails_null(mut self) -> Self {
        self.raw.guardrails = Some(None);
        self
    }

    #[must_use]
    pub fn max_tokens(mut self, max_tokens: i64) -> Self {
        self.raw.max_tokens = Some(Some(max_tokens));
        self
    }

    #[must_use]
    pub fn max_tokens_null(mut self) -> Self {
        self.raw.max_tokens = Some(None);
        self
    }

    #[must_use]
    pub fn metadata(mut self, metadata: ChatCompletionRequestMetadata) -> Self {
        self.raw.metadata = Some(Some(metadata));
        self
    }

    #[must_use]
    pub fn metadata_null(mut self) -> Self {
        self.raw.metadata = Some(None);
        self
    }

    #[must_use]
    pub fn n(mut self, n: i64) -> Self {
        self.raw.n = Some(Some(n));
        self
    }

    #[must_use]
    pub fn n_null(mut self) -> Self {
        self.raw.n = Some(None);
        self
    }

    #[must_use]
    pub fn parallel_tool_calls(mut self, parallel_tool_calls: bool) -> Self {
        self.raw.parallel_tool_calls = Some(parallel_tool_calls);
        self
    }

    #[must_use]
    pub fn prediction(mut self, prediction: Prediction) -> Self {
        self.raw.prediction = Some(prediction);
        self
    }

    #[must_use]
    pub fn presence_penalty(mut self, presence_penalty: f64) -> Self {
        self.raw.presence_penalty = Some(presence_penalty);
        self
    }

    #[must_use]
    pub fn prompt_cache_key(mut self, prompt_cache_key: impl Into<String>) -> Self {
        self.raw.prompt_cache_key = Some(Some(prompt_cache_key.into()));
        self
    }

    #[must_use]
    pub fn prompt_cache_key_null(mut self) -> Self {
        self.raw.prompt_cache_key = Some(None);
        self
    }

    #[must_use]
    pub fn prompt_mode(mut self, prompt_mode: MistralPromptMode) -> Self {
        self.raw.prompt_mode = Some(Some(prompt_mode));
        self
    }

    #[must_use]
    pub fn prompt_mode_null(mut self) -> Self {
        self.raw.prompt_mode = Some(None);
        self
    }

    #[must_use]
    pub fn random_seed(mut self, random_seed: i64) -> Self {
        self.raw.random_seed = Some(Some(random_seed));
        self
    }

    #[must_use]
    pub fn random_seed_null(mut self) -> Self {
        self.raw.random_seed = Some(None);
        self
    }

    #[must_use]
    pub fn reasoning_effort(
        mut self,
        reasoning_effort: ChatCompletionRequestReasoningEffort,
    ) -> Self {
        self.raw.reasoning_effort = Some(reasoning_effort);
        self
    }

    #[must_use]
    pub fn response_format(mut self, response_format: ResponseFormat) -> Self {
        self.raw.response_format = Some(response_format);
        self
    }

    #[must_use]
    pub fn safe_prompt(mut self, safe_prompt: bool) -> Self {
        self.raw.safe_prompt = Some(safe_prompt);
        self
    }

    #[must_use]
    pub fn stop(mut self, stop: ChatCompletionRequestStop) -> Self {
        self.raw.stop = Some(stop);
        self
    }

    #[must_use]
    pub fn temperature(mut self, temperature: f64) -> Self {
        self.raw.temperature = Some(Some(temperature));
        self
    }

    #[must_use]
    pub fn temperature_null(mut self) -> Self {
        self.raw.temperature = Some(None);
        self
    }

    #[must_use]
    pub fn tool_choice(mut self, tool_choice: ChatCompletionRequestToolChoice) -> Self {
        self.raw.tool_choice = Some(tool_choice);
        self
    }

    #[must_use]
    pub fn tools(mut self, tools: Vec<Tool>) -> Self {
        self.raw.tools = Some(Some(tools));
        self
    }

    #[must_use]
    pub fn tools_null(mut self) -> Self {
        self.raw.tools = Some(None);
        self
    }

    #[must_use]
    pub fn top_p(mut self, top_p: f64) -> Self {
        self.raw.top_p = Some(top_p);
        self
    }

    pub fn as_raw(&self) -> &ChatCompletionRequest {
        &self.raw
    }
    pub fn into_raw(self) -> ChatCompletionRequest {
        self.raw
    }

    fn into_raw_with_stream(mut self, stream: bool) -> ChatCompletionRequest {
        self.raw.stream = Some(stream);
        self.raw
    }
}

/// A stable facade over the generated chat completion response.
#[derive(Debug, Clone)]
pub struct ChatResponse {
    raw: ChatCompletionResponse,
}

impl ChatResponse {
    pub fn text(&self) -> Option<&str> {
        let content = self
            .raw
            .choices
            .first()?
            .message
            .content
            .as_ref()?
            .as_ref()?;
        match content {
            AssistantMessageContent::String(text) => Some(text),
            AssistantMessageContent::ContentChunkArray(_) => None,
        }
    }
    pub fn raw(&self) -> &ChatCompletionResponse {
        &self.raw
    }
    pub fn into_raw(self) -> ChatCompletionResponse {
        self.raw
    }
}

impl From<ChatCompletionResponse> for ChatResponse {
    fn from(raw: ChatCompletionResponse) -> Self {
        Self { raw }
    }
}

/// A stable facade over one generated streaming chunk.
#[derive(Debug, Clone)]
pub struct ChatStreamChunk {
    raw: CompletionChunk,
}

impl ChatStreamChunk {
    pub fn text(&self) -> Option<&str> {
        let content = self.raw.choices.first()?.delta.content.as_ref()?.as_ref()?;
        match content {
            DeltaMessageContent::String(text) => Some(text),
            DeltaMessageContent::ContentChunkArrayInline(_) => None,
        }
    }
    pub fn raw(&self) -> &CompletionChunk {
        &self.raw
    }
    pub fn into_raw(self) -> CompletionChunk {
        self.raw
    }
}

impl From<CompletionChunk> for ChatStreamChunk {
    fn from(raw: CompletionChunk) -> Self {
        Self { raw }
    }
}

pub type ChatStream =
    Pin<Box<dyn Stream<Item = Result<ChatStreamChunk, SdkError>> + Send + 'static>>;

#[derive(Clone, Copy)]
pub struct Chat<'a> {
    raw: &'a HttpClient,
}

impl<'a> Chat<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }

    pub async fn complete(&self, request: ChatRequest) -> Result<ChatResponse, SdkError> {
        self.raw
            .chat_completion_v1_chat_completions_post(request.into_raw_with_stream(false))
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn stream(&self, request: ChatRequest) -> Result<ChatStream, SdkError> {
        let bytes = self
            .raw
            .chat_completion_v1_chat_completions_post_stream(request.into_raw_with_stream(true))
            .await
            .map_err(SdkError::from)?;
        let events = streaming::json_events::<_, _, CompletionChunk>(bytes)
            .map(|event| event.map(|event| event.data.into()).map_err(Into::into));
        Ok(Box::pin(events))
    }
}
