// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;

#[derive(Clone, Copy)]
pub struct Classifiers<'a> {
    raw: &'a HttpClient,
}

impl<'a> Classifiers<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn classify(
        &self,
        request: ClassifyClassifiersRequest,
    ) -> Result<ClassifyClassifiersResponse, SdkError> {
        self.raw
            .classifications_v1_classifications_post(
                <ClassifyClassifiersRequest as __RustSdkIntoRaw<
                    crate::generated::types::ClassificationRequest,
                >>::into_raw(request),
            )
            .await
            .map(__RustSdkFromRaw::from_raw)
            .map_err(Into::into)
    }

    pub async fn classify_chat(
        &self,
        request: ClassifyChatClassifiersRequest,
    ) -> Result<ClassifyChatClassifiersResponse, SdkError> {
        self.raw
            .chat_classifications_v1_chat_classifications_post(
                <ClassifyChatClassifiersRequest as __RustSdkIntoRaw<
                    crate::generated::types::ChatClassificationRequest,
                >>::into_raw(request),
            )
            .await
            .map(__RustSdkFromRaw::from_raw)
            .map_err(Into::into)
    }

    pub async fn moderate(
        &self,
        request: ModerateClassifiersRequest,
    ) -> Result<ModerateClassifiersResponse, SdkError> {
        self.raw
            .moderations_v1_moderations_post(<ModerateClassifiersRequest as __RustSdkIntoRaw<
                crate::generated::types::ClassificationRequest,
            >>::into_raw(request))
            .await
            .map(__RustSdkFromRaw::from_raw)
            .map_err(Into::into)
    }

    pub async fn moderate_chat(
        &self,
        request: ModerateChatClassifiersRequest,
    ) -> Result<ModerateChatClassifiersResponse, SdkError> {
        self.raw
            .chat_moderations_v1_chat_moderations_post(
                <ModerateChatClassifiersRequest as __RustSdkIntoRaw<
                    crate::generated::types::ChatModerationRequest,
                >>::into_raw(request),
            )
            .await
            .map(__RustSdkFromRaw::from_raw)
            .map_err(Into::into)
    }
}
