// @generated by codegen/sdk_facade.py; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;

#[derive(Clone, Copy)]
pub struct Classifiers<'a> {
    raw: &'a HttpClient,
}

impl<'a> Classifiers<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }

    pub async fn moderate(
        &self,
        request: ClassificationParams,
    ) -> Result<ModerationResultSet, SdkError> {
        self.raw
            .moderations_v1_moderations_post(request.into_raw())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn moderate_chat(
        &self,
        request: ChatModerationParams,
    ) -> Result<ModerationResultSet, SdkError> {
        self.raw
            .chat_moderations_v1_chat_moderations_post(request.into_raw())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn classify(
        &self,
        request: ClassificationParams,
    ) -> Result<ClassificationResultSet, SdkError> {
        self.raw
            .classifications_v1_classifications_post(request.into_raw())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn classify_chat(
        &self,
        request: ChatClassificationParams,
    ) -> Result<ClassificationResultSet, SdkError> {
        self.raw
            .chat_classifications_v1_chat_classifications_post(request.into_raw())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
