// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;
#[derive(Clone, Copy)]
pub struct Deprecated<'a> {
    raw: &'a HttpClient,
}

impl<'a> Deprecated<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub fn fine_tuning(&self) -> DeprecatedFineTuning<'a> {
        DeprecatedFineTuning::new(self.raw)
    }
}
