// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;
#[derive(Debug, Clone, Default)]
pub struct GetFineTuningJobsDeprecatedFineTuningRequest {
    page: Option<i64>,
    page_size: Option<i64>,
    model: Option<String>,
    created_after: Option<String>,
    created_before: Option<String>,
    created_by_me: Option<bool>,
    status: Option<String>,
    wandb_project: Option<String>,
    wandb_name: Option<String>,
    suffix: Option<String>,
}
impl GetFineTuningJobsDeprecatedFineTuningRequest {
    pub fn new() -> Self {
        Self {
            page: None,
            page_size: None,
            model: None,
            created_after: None,
            created_before: None,
            created_by_me: None,
            status: None,
            wandb_project: None,
            wandb_name: None,
            suffix: None,
        }
    }
    #[must_use]
    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }
    #[must_use]
    pub fn page_size(mut self, page_size: i64) -> Self {
        self.page_size = Some(page_size);
        self
    }
    #[must_use]
    pub fn model(mut self, model: impl Into<String>) -> Self {
        self.model = Some(model.into());
        self
    }
    #[must_use]
    pub fn created_after(mut self, created_after: impl Into<String>) -> Self {
        self.created_after = Some(created_after.into());
        self
    }
    #[must_use]
    pub fn created_before(mut self, created_before: impl Into<String>) -> Self {
        self.created_before = Some(created_before.into());
        self
    }
    #[must_use]
    pub fn created_by_me(mut self, created_by_me: bool) -> Self {
        self.created_by_me = Some(created_by_me);
        self
    }
    #[must_use]
    pub fn status(mut self, status: impl Into<String>) -> Self {
        self.status = Some(status.into());
        self
    }
    #[must_use]
    pub fn wandb_project(mut self, wandb_project: impl Into<String>) -> Self {
        self.wandb_project = Some(wandb_project.into());
        self
    }
    #[must_use]
    pub fn wandb_name(mut self, wandb_name: impl Into<String>) -> Self {
        self.wandb_name = Some(wandb_name.into());
        self
    }
    #[must_use]
    pub fn suffix(mut self, suffix: impl Into<String>) -> Self {
        self.suffix = Some(suffix.into());
        self
    }
}
#[derive(Clone, Copy)]
pub struct DeprecatedFineTuning<'a> {
    raw: &'a HttpClient,
}

impl<'a> DeprecatedFineTuning<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn get_fine_tuning_jobs(&self) -> Result<JobsOutView, SdkError> {
        self.raw
            .jobs_api_routes_fine_tuning_get_fine_tuning_jobs(
                None,
                None,
                None::<&str>,
                None::<&str>,
                None::<&str>,
                None,
                None::<&str>,
                None::<&str>,
                None::<&str>,
                None::<&str>,
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn get_fine_tuning_jobs_with(
        &self,
        request: GetFineTuningJobsDeprecatedFineTuningRequest,
    ) -> Result<JobsOutView, SdkError> {
        self.raw
            .jobs_api_routes_fine_tuning_get_fine_tuning_jobs(
                request.page,
                request.page_size,
                request.model.as_deref(),
                request.created_after.as_deref(),
                request.created_before.as_deref(),
                request.created_by_me,
                request.status.as_deref(),
                request.wandb_project.as_deref(),
                request.wandb_name.as_deref(),
                request.suffix.as_deref(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
