// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;
#[derive(Clone, Copy)]
pub struct Embeddings<'a> {
    raw: &'a HttpClient,
}

impl<'a> Embeddings<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn create(
        &self,
        request: CreateEmbeddingsRequest,
    ) -> Result<CreateEmbeddingsResponse, SdkError> {
        self.raw
            .embeddings_v1_embeddings_post(<CreateEmbeddingsRequest as __RustSdkIntoRaw<
                crate::generated::types::EmbeddingRequest,
            >>::into_raw(request))
            .await
            .map(__RustSdkFromRaw::from_raw)
            .map_err(Into::into)
    }
}
