// @generated by codegen/sdk_facade.py; do not edit by hand.
use super::SdkError;
use crate::generated::types::*;
use futures_util::Stream;
use std::pin::Pin;

#[derive(Debug, Clone)]
#[non_exhaustive]
pub enum Message {
    Assistant(String),
    System(String),
    Tool(String),
    User(String),
}

impl Message {
    pub fn assistant(content: impl Into<String>) -> Self {
        Self::Assistant(content.into())
    }
    pub fn system(content: impl Into<String>) -> Self {
        Self::System(content.into())
    }
    pub fn tool(content: impl Into<String>) -> Self {
        Self::Tool(content.into())
    }
    pub fn user(content: impl Into<String>) -> Self {
        Self::User(content.into())
    }
}

impl From<Message> for ChatCompletionRequestMessagesItemUnion {
    fn from(value: Message) -> Self {
        match value {
            Message::Assistant(content) => Self::AssistantMessage(AssistantMessage {
                content: Some(Some(AssistantMessageContent::String(content))),
                prefix: None,
                role: None,
                tool_calls: None,
            }),
            Message::System(content) => Self::SystemMessage(SystemMessage {
                content: SystemMessageContent::String(content),
                role: None,
            }),
            Message::Tool(content) => Self::ToolMessage(ToolMessage {
                content: Some(ToolMessageContent::String(content)),
                name: None,
                role: None,
                tool_call_id: None,
            }),
            Message::User(content) => Self::UserMessage(UserMessage {
                content: Some(UserMessageContent::String(content)),
                role: None,
            }),
        }
    }
}

#[derive(Debug, Clone)]
pub struct ChatRequest {
    raw: ChatCompletionRequest,
}

impl ChatRequest {
    pub fn new(model: impl Into<String>, messages: impl IntoIterator<Item = Message>) -> Self {
        Self {
            raw: ChatCompletionRequest {
                frequency_penalty: None,
                guardrails: None,
                max_tokens: None,
                messages: messages.into_iter().map(Into::into).collect(),
                metadata: None,
                model: model.into(),
                n: None,
                parallel_tool_calls: None,
                prediction: None,
                presence_penalty: None,
                prompt_cache_key: None,
                prompt_mode: None,
                random_seed: None,
                reasoning_effort: None,
                response_format: None,
                safe_prompt: None,
                stop: None,
                stream: None,
                temperature: None,
                tool_choice: None,
                tools: None,
                top_p: None,
            },
        }
    }
    #[must_use]
    pub fn frequency_penalty(mut self, frequency_penalty: f64) -> Self {
        self.raw.frequency_penalty = Some(frequency_penalty);
        self
    }

    #[must_use]
    pub fn guardrails(mut self, guardrails: Vec<GuardrailConfig>) -> Self {
        self.raw.guardrails = Some(Some(guardrails));
        self
    }

    #[must_use]
    pub fn guardrails_null(mut self) -> Self {
        self.raw.guardrails = Some(None);
        self
    }

    #[must_use]
    pub fn max_tokens(mut self, max_tokens: i64) -> Self {
        self.raw.max_tokens = Some(Some(max_tokens));
        self
    }

    #[must_use]
    pub fn max_tokens_null(mut self) -> Self {
        self.raw.max_tokens = Some(None);
        self
    }

    #[must_use]
    pub fn metadata(mut self, metadata: ChatCompletionRequestMetadata) -> Self {
        self.raw.metadata = Some(Some(metadata));
        self
    }

    #[must_use]
    pub fn metadata_null(mut self) -> Self {
        self.raw.metadata = Some(None);
        self
    }

    #[must_use]
    pub fn n(mut self, n: i64) -> Self {
        self.raw.n = Some(Some(n));
        self
    }

    #[must_use]
    pub fn n_null(mut self) -> Self {
        self.raw.n = Some(None);
        self
    }

    #[must_use]
    pub fn parallel_tool_calls(mut self, parallel_tool_calls: bool) -> Self {
        self.raw.parallel_tool_calls = Some(parallel_tool_calls);
        self
    }

    #[must_use]
    pub fn prediction(mut self, prediction: Prediction) -> Self {
        self.raw.prediction = Some(prediction);
        self
    }

    #[must_use]
    pub fn presence_penalty(mut self, presence_penalty: f64) -> Self {
        self.raw.presence_penalty = Some(presence_penalty);
        self
    }

    #[must_use]
    pub fn prompt_cache_key(mut self, prompt_cache_key: impl Into<String>) -> Self {
        self.raw.prompt_cache_key = Some(Some(prompt_cache_key.into()));
        self
    }

    #[must_use]
    pub fn prompt_cache_key_null(mut self) -> Self {
        self.raw.prompt_cache_key = Some(None);
        self
    }

    #[must_use]
    pub fn prompt_mode(mut self, prompt_mode: MistralPromptMode) -> Self {
        self.raw.prompt_mode = Some(Some(prompt_mode));
        self
    }

    #[must_use]
    pub fn prompt_mode_null(mut self) -> Self {
        self.raw.prompt_mode = Some(None);
        self
    }

    #[must_use]
    pub fn random_seed(mut self, random_seed: i64) -> Self {
        self.raw.random_seed = Some(Some(random_seed));
        self
    }

    #[must_use]
    pub fn random_seed_null(mut self) -> Self {
        self.raw.random_seed = Some(None);
        self
    }

    #[must_use]
    pub fn reasoning_effort(
        mut self,
        reasoning_effort: ChatCompletionRequestReasoningEffort,
    ) -> Self {
        self.raw.reasoning_effort = Some(reasoning_effort);
        self
    }

    #[must_use]
    pub fn response_format(mut self, response_format: ResponseFormat) -> Self {
        self.raw.response_format = Some(response_format);
        self
    }

    #[must_use]
    pub fn safe_prompt(mut self, safe_prompt: bool) -> Self {
        self.raw.safe_prompt = Some(safe_prompt);
        self
    }

    #[must_use]
    pub fn stop(mut self, stop: ChatCompletionRequestStop) -> Self {
        self.raw.stop = Some(stop);
        self
    }

    #[must_use]
    pub fn temperature(mut self, temperature: f64) -> Self {
        self.raw.temperature = Some(Some(temperature));
        self
    }

    #[must_use]
    pub fn temperature_null(mut self) -> Self {
        self.raw.temperature = Some(None);
        self
    }

    #[must_use]
    pub fn tool_choice(mut self, tool_choice: ChatCompletionRequestToolChoice) -> Self {
        self.raw.tool_choice = Some(tool_choice);
        self
    }

    #[must_use]
    pub fn tools(mut self, tools: Vec<Tool>) -> Self {
        self.raw.tools = Some(Some(tools));
        self
    }

    #[must_use]
    pub fn tools_null(mut self) -> Self {
        self.raw.tools = Some(None);
        self
    }

    #[must_use]
    pub fn top_p(mut self, top_p: f64) -> Self {
        self.raw.top_p = Some(top_p);
        self
    }
    pub fn from_raw(raw: ChatCompletionRequest) -> Self {
        Self { raw }
    }
    pub fn as_raw(&self) -> &ChatCompletionRequest {
        &self.raw
    }
    pub fn into_raw(self) -> ChatCompletionRequest {
        self.raw
    }
}

impl From<ChatCompletionRequest> for ChatRequest {
    fn from(raw: ChatCompletionRequest) -> Self {
        Self { raw }
    }
}

#[derive(Debug, Clone)]
pub struct ChatResponse {
    raw: ChatCompletionResponse,
}

impl ChatResponse {
    pub fn text(&self) -> Option<&str> {
        match self
            .raw
            .choices
            .first()?
            .message
            .content
            .as_ref()?
            .as_ref()?
        {
            AssistantMessageContent::String(value) => Some(value),
            _ => None,
        }
    }
    pub fn raw(&self) -> &ChatCompletionResponse {
        &self.raw
    }
    pub fn into_raw(self) -> ChatCompletionResponse {
        self.raw
    }
}

impl From<ChatCompletionResponse> for ChatResponse {
    fn from(raw: ChatCompletionResponse) -> Self {
        Self { raw }
    }
}

#[derive(Debug, Clone)]
pub struct ChatStreamChunk {
    raw: CompletionChunk,
}

impl ChatStreamChunk {
    pub fn text(&self) -> Option<&str> {
        match self.raw.choices.first()?.delta.content.as_ref()?.as_ref()? {
            DeltaMessageContent::String(value) => Some(value),
            _ => None,
        }
    }
    pub fn raw(&self) -> &CompletionChunk {
        &self.raw
    }
    pub fn into_raw(self) -> CompletionChunk {
        self.raw
    }
}

impl From<CompletionChunk> for ChatStreamChunk {
    fn from(raw: CompletionChunk) -> Self {
        Self { raw }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct OcrPage<'a> {
    raw: &'a OCRPageObject,
}

impl<'a> OcrPage<'a> {
    pub(crate) fn new(raw: &'a OCRPageObject) -> Self {
        Self { raw }
    }
    pub fn index(&self) -> i64 {
        self.raw.index
    }
    pub fn markdown(&self) -> &str {
        &self.raw.markdown
    }
    pub fn raw(&self) -> &'a OCRPageObject {
        self.raw
    }
}

#[derive(Debug, Clone)]
pub struct OcrRequest {
    raw: OCRRequest,
}

impl OcrRequest {
    pub fn document_url(model: impl Into<String>, document_url: impl Into<String>) -> Self {
        Self {
            raw: OCRRequest {
                bbox_annotation_format: None,
                confidence_scores_granularity: None,
                document: OCRRequestDocument::DocumentURLChunk(DocumentURLChunk {
                    document_name: None,
                    document_url: document_url.into(),
                    r#type: None,
                }),
                document_annotation_format: None,
                document_annotation_prompt: None,
                extract_footer: None,
                extract_header: None,
                id: None,
                image_limit: None,
                image_min_size: None,
                include_blocks: None,
                include_image_base64: None,
                model: Some(model.into()),
                pages: None,
                table_format: None,
            },
        }
    }

    pub fn file_id(model: impl Into<String>, file_id: uuid::Uuid) -> Self {
        Self {
            raw: OCRRequest {
                bbox_annotation_format: None,
                confidence_scores_granularity: None,
                document: OCRRequestDocument::FileChunk(FileChunk {
                    file_id,
                    r#type: None,
                }),
                document_annotation_format: None,
                document_annotation_prompt: None,
                extract_footer: None,
                extract_header: None,
                id: None,
                image_limit: None,
                image_min_size: None,
                include_blocks: None,
                include_image_base64: None,
                model: Some(model.into()),
                pages: None,
                table_format: None,
            },
        }
    }

    pub fn image_url(model: impl Into<String>, image_url: impl Into<String>) -> Self {
        Self {
            raw: OCRRequest {
                bbox_annotation_format: None,
                confidence_scores_granularity: None,
                document: OCRRequestDocument::ImageURLChunk(ImageURLChunk {
                    image_url: ImageURLChunkImageUrl::String(image_url.into()),
                    r#type: None,
                }),
                document_annotation_format: None,
                document_annotation_prompt: None,
                extract_footer: None,
                extract_header: None,
                id: None,
                image_limit: None,
                image_min_size: None,
                include_blocks: None,
                include_image_base64: None,
                model: Some(model.into()),
                pages: None,
                table_format: None,
            },
        }
    }
    #[must_use]
    pub fn bbox_annotation_format(mut self, bbox_annotation_format: ResponseFormat) -> Self {
        self.raw.bbox_annotation_format = Some(Some(bbox_annotation_format));
        self
    }

    #[must_use]
    pub fn bbox_annotation_format_null(mut self) -> Self {
        self.raw.bbox_annotation_format = Some(None);
        self
    }

    #[must_use]
    pub fn confidence_scores_granularity(
        mut self,
        confidence_scores_granularity: OCRRequestConfidenceScoresGranularity,
    ) -> Self {
        self.raw.confidence_scores_granularity = Some(Some(confidence_scores_granularity));
        self
    }

    #[must_use]
    pub fn confidence_scores_granularity_null(mut self) -> Self {
        self.raw.confidence_scores_granularity = Some(None);
        self
    }

    #[must_use]
    pub fn document_annotation_format(
        mut self,
        document_annotation_format: ResponseFormat,
    ) -> Self {
        self.raw.document_annotation_format = Some(Some(document_annotation_format));
        self
    }

    #[must_use]
    pub fn document_annotation_format_null(mut self) -> Self {
        self.raw.document_annotation_format = Some(None);
        self
    }

    #[must_use]
    pub fn document_annotation_prompt(
        mut self,
        document_annotation_prompt: impl Into<String>,
    ) -> Self {
        self.raw.document_annotation_prompt = Some(Some(document_annotation_prompt.into()));
        self
    }

    #[must_use]
    pub fn document_annotation_prompt_null(mut self) -> Self {
        self.raw.document_annotation_prompt = Some(None);
        self
    }

    #[must_use]
    pub fn extract_footer(mut self, extract_footer: bool) -> Self {
        self.raw.extract_footer = Some(extract_footer);
        self
    }

    #[must_use]
    pub fn extract_header(mut self, extract_header: bool) -> Self {
        self.raw.extract_header = Some(extract_header);
        self
    }

    #[must_use]
    pub fn id(mut self, id: impl Into<String>) -> Self {
        self.raw.id = Some(id.into());
        self
    }

    #[must_use]
    pub fn image_limit(mut self, image_limit: i64) -> Self {
        self.raw.image_limit = Some(Some(image_limit));
        self
    }

    #[must_use]
    pub fn image_limit_null(mut self) -> Self {
        self.raw.image_limit = Some(None);
        self
    }

    #[must_use]
    pub fn image_min_size(mut self, image_min_size: i64) -> Self {
        self.raw.image_min_size = Some(Some(image_min_size));
        self
    }

    #[must_use]
    pub fn image_min_size_null(mut self) -> Self {
        self.raw.image_min_size = Some(None);
        self
    }

    #[must_use]
    pub fn include_blocks(mut self, include_blocks: bool) -> Self {
        self.raw.include_blocks = Some(include_blocks);
        self
    }

    #[must_use]
    pub fn include_image_base64(mut self, include_image_base64: bool) -> Self {
        self.raw.include_image_base64 = Some(Some(include_image_base64));
        self
    }

    #[must_use]
    pub fn include_image_base64_null(mut self) -> Self {
        self.raw.include_image_base64 = Some(None);
        self
    }

    #[must_use]
    pub fn pages(mut self, pages: OCRRequestPages) -> Self {
        self.raw.pages = Some(Some(pages));
        self
    }

    #[must_use]
    pub fn pages_null(mut self) -> Self {
        self.raw.pages = Some(None);
        self
    }

    #[must_use]
    pub fn table_format(mut self, table_format: OCRRequestTableFormat) -> Self {
        self.raw.table_format = Some(Some(table_format));
        self
    }

    #[must_use]
    pub fn table_format_null(mut self) -> Self {
        self.raw.table_format = Some(None);
        self
    }
    pub fn from_raw(raw: OCRRequest) -> Self {
        Self { raw }
    }
    pub fn as_raw(&self) -> &OCRRequest {
        &self.raw
    }
    pub fn into_raw(self) -> OCRRequest {
        self.raw
    }
}

impl From<OCRRequest> for OcrRequest {
    fn from(raw: OCRRequest) -> Self {
        Self { raw }
    }
}

#[derive(Debug, Clone)]
pub struct OcrResponse {
    raw: OCRResponse,
}

impl OcrResponse {
    pub fn model(&self) -> &str {
        &self.raw.model
    }
    pub fn pages(&self) -> impl ExactSizeIterator<Item = OcrPage<'_>> {
        self.raw.pages.iter().map(OcrPage::new)
    }
    pub fn raw(&self) -> &OCRResponse {
        &self.raw
    }
    pub fn into_raw(self) -> OCRResponse {
        self.raw
    }
}

impl From<OCRResponse> for OcrResponse {
    fn from(raw: OCRResponse) -> Self {
        Self { raw }
    }
}

#[derive(Debug, Clone)]
pub struct ModelListResponse {
    raw: ModelList,
}

impl ModelListResponse {
    pub fn raw(&self) -> &ModelList {
        &self.raw
    }
    pub fn into_raw(self) -> ModelList {
        self.raw
    }
}

impl From<ModelList> for ModelListResponse {
    fn from(raw: ModelList) -> Self {
        Self { raw }
    }
}

pub type ChatStream =
    Pin<Box<dyn Stream<Item = Result<ChatStreamChunk, SdkError>> + Send + 'static>>;
