// @generated by codegen/sdk_facade.py; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;
use crate::generated::types::*;
use crate::streaming;
use futures_util::StreamExt;

#[derive(Clone, Copy)]
pub struct Fim<'a> {
    raw: &'a HttpClient,
}

impl<'a> Fim<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }

    pub async fn complete(&self, request: FimRequest) -> Result<FimResponse, SdkError> {
        self.raw
            .fim_completion_v1_fim_completions_post({
                let mut raw = request.into_raw();
                raw.stream = Some(false);
                raw
            })
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn stream(&self, request: FimRequest) -> Result<FimStream, SdkError> {
        let bytes = self
            .raw
            .fim_completion_v1_fim_completions_post_stream({
                let mut raw = request.into_raw();
                raw.stream = Some(true);
                raw
            })
            .await
            .map_err(SdkError::from)?;
        let events = streaming::json_events::<_, _, CompletionChunk>(bytes).map(|event| {
            event
                .map(|event| FimStreamChunk::from(event.data))
                .map_err(Into::into)
        });
        Ok(Box::pin(events))
    }
}
