// @generated by codegen/sdk_facade.py; do not edit by hand.
pub mod audio;
mod audio_voices;
pub mod batch;
mod batch_jobs;
pub mod beta;
mod beta_agents;
mod beta_connectors;
mod beta_conversations;
mod beta_libraries;
mod beta_libraries_accesses;
mod beta_libraries_documents;
mod beta_observability;
mod beta_observability_datasets;
mod beta_observability_datasets_records;
mod beta_observability_judges;
pub mod chat;
pub mod classifiers;
pub mod embeddings;
pub mod error;
mod facade_types;
pub mod files;
pub mod fim;
pub mod models;
pub mod ocr;
pub mod workflows;
mod workflows_deployments;
mod workflows_events;
mod workflows_executions;
mod workflows_metrics;
mod workflows_runs;
mod workflows_schedules;

pub use audio::Audio;
pub use audio_voices::AudioVoices;
pub use batch::Batch;
pub use batch_jobs::BatchJobs;
pub use beta::Beta;
pub use beta_agents::BetaAgents;
pub use beta_connectors::BetaConnectors;
pub use beta_conversations::BetaConversations;
pub use beta_libraries::BetaLibraries;
pub use beta_libraries_accesses::BetaLibrariesAccesses;
pub use beta_libraries_documents::BetaLibrariesDocuments;
pub use beta_observability::BetaObservability;
pub use beta_observability_datasets::BetaObservabilityDatasets;
pub use beta_observability_datasets_records::BetaObservabilityDatasetsRecords;
pub use beta_observability_judges::BetaObservabilityJudges;
pub use chat::Chat;
pub use classifiers::Classifiers;
pub use embeddings::Embeddings;
pub use error::{ApiError, SdkError, TransportError, TransportErrorKind};
pub use facade_types::{
    AgentAliasResponseView, AgentListPageView, AgentView, ArchiveModelResponse,
    AuthUrlResponseView, BaseModel, BatchExecutionBodyParams, BatchExecutionResponseView,
    BatchJobOutView, BatchJobsOutView, BinaryStream, ChatClassificationInput,
    ChatClassificationParams, ChatModerationInput, ChatModerationParams, ChatRequest, ChatResponse,
    ChatStream, ChatStreamChunk, ClassificationInput, ClassificationParams, ClassificationResult,
    ClassificationResultSet, ClassifierConversation, ClassifierFineTunedModel,
    CompletionFineTunedModel, ConnectorView, ConversationHistoryView, ConversationMessagesView,
    ConversationResponseView, CredentialsResponseView, DatasetExportView, DatasetImportTaskView,
    DatasetImportTasksView, DatasetPreviewView, DatasetPreviewsView, DatasetRecordView,
    DatasetRecordsView, DatasetView, DeleteDatasetRecordsInSchemaParams, DeleteModelResponse,
    DeletedFile, DeploymentDetailResponseView, DeploymentListResponseView, DocumentOutView,
    DocumentTextContentView, Embedding, EmbeddingInput, EmbeddingParams, EmbeddingResult,
    FileDetails, FileInfo, FileList, FileSignedUrl, FimRequest, FimResponse, FimStream,
    FimStreamChunk, FineTunedModel, JudgeOutputView, JudgePreviewView, JudgePreviewsView,
    LibraryInParams, LibraryInUpdateParams, LibraryOutView, ListDocumentOutView,
    ListLibraryOutView, ListSharingOutView, ListWorkflowEventResponseView, MCPToolCallResponseView,
    Message, MessageResponseView, ModelListResponse, ModelResponse, ModerationResult,
    ModerationResultSet, OcrPage, OcrRequest, OcrResponse, PaginatedConnectorsView,
    PatchDatasetInSchemaParams, PostDatasetImportFromDatasetInSchemaParams,
    PostDatasetImportFromFileInSchemaParams, PostDatasetImportFromPlaygroundInSchemaParams,
    PostDatasetInSchemaParams, ProcessingStatusOutView, QueryWorkflowResponseView,
    ResetInvocationBodyParams, SharingOutView, SignalWorkflowResponseView, StopSequences,
    TranscriptionResponseView, UnarchiveModelResponse, UpdateModelRequest, UpdateModelResponse,
    UpdateWorkflowResponseView, UploadFileOutView, VoiceCreateRequestParams, VoiceListResponseView,
    VoiceResponseView, VoiceUpdateRequestParams, WorkflowArchiveResponseView,
    WorkflowExecutionListResponseView, WorkflowExecutionResponseView,
    WorkflowExecutionTraceEventsResponseView, WorkflowExecutionTraceOTelResponseView,
    WorkflowExecutionTraceSummaryResponseView, WorkflowGetResponseView, WorkflowMetricsView,
    WorkflowRegistrationGetResponseView, WorkflowRegistrationListResponseView,
    WorkflowScheduleListResponseView, WorkflowScheduleResponseView, WorkflowUnarchiveResponseView,
    WorkflowUpdateRequestParams, WorkflowUpdateResponseView,
};
pub use files::Files;
pub use fim::Fim;
pub use models::Models;
pub use ocr::Ocr;
pub use workflows::Workflows;
pub use workflows_deployments::WorkflowsDeployments;
pub use workflows_events::WorkflowsEvents;
pub use workflows_executions::WorkflowsExecutions;
pub use workflows_metrics::WorkflowsMetrics;
pub use workflows_runs::WorkflowsRuns;
pub use workflows_schedules::WorkflowsSchedules;

use crate::generated::client::HttpClient;

#[derive(Clone)]
pub struct Mistral {
    raw: HttpClient,
}

impl Mistral {
    pub fn new(api_key: impl Into<String>) -> Self {
        Self {
            raw: HttpClient::new().with_api_key(api_key),
        }
    }
    #[must_use]
    pub fn with_base_url(mut self, base_url: impl Into<String>) -> Self {
        self.raw = self.raw.with_base_url(base_url);
        self
    }
    pub fn chat(&self) -> Chat<'_> {
        Chat::new(&self.raw)
    }
    pub fn ocr(&self) -> Ocr<'_> {
        Ocr::new(&self.raw)
    }
    pub fn models(&self) -> Models<'_> {
        Models::new(&self.raw)
    }
    pub fn embeddings(&self) -> Embeddings<'_> {
        Embeddings::new(&self.raw)
    }
    pub fn fim(&self) -> Fim<'_> {
        Fim::new(&self.raw)
    }
    pub fn classifiers(&self) -> Classifiers<'_> {
        Classifiers::new(&self.raw)
    }
    pub fn files(&self) -> Files<'_> {
        Files::new(&self.raw)
    }
    pub fn beta(&self) -> Beta<'_> {
        Beta::new(&self.raw)
    }
    pub fn workflows(&self) -> Workflows<'_> {
        Workflows::new(&self.raw)
    }
    pub fn audio(&self) -> Audio<'_> {
        Audio::new(&self.raw)
    }
    pub fn batch(&self) -> Batch<'_> {
        Batch::new(&self.raw)
    }
    pub fn raw(&self) -> &HttpClient {
        &self.raw
    }
}
