// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
pub mod agents;
pub mod audio;
mod audio_speech;
mod audio_transcriptions;
mod audio_voices;
pub mod batch;
mod batch_jobs;
pub mod beta;
mod beta_admin;
mod beta_admin_api_keys;
mod beta_admin_audit_logs;
mod beta_admin_billing;
mod beta_admin_scim;
mod beta_admin_user_groups;
mod beta_admin_users;
mod beta_admin_vibe_code_analytics;
mod beta_admin_vibe_work_analytics;
mod beta_admin_workspaces;
mod beta_agents;
mod beta_connectors;
mod beta_conversations;
mod beta_libraries;
mod beta_libraries_accesses;
mod beta_libraries_documents;
mod beta_observability;
mod beta_observability_campaigns;
mod beta_observability_chat_completion_events;
mod beta_observability_chat_completion_events_fields;
mod beta_observability_datasets;
mod beta_observability_datasets_records;
mod beta_observability_judges;
mod beta_observability_logs;
mod beta_observability_spans;
mod beta_observability_traces;
mod beta_prompts;
mod beta_rag;
mod beta_rag_ingestion_pipeline_configurations;
mod beta_rag_search_indexes;
mod beta_skills;
mod beta_users;
pub mod chat;
pub mod classifiers;
pub mod embeddings;
pub mod error;
pub mod events;
mod facade_types;
pub mod files;
pub mod fim;
pub mod models;
pub mod ocr;
pub mod workflows;
mod workflows_deployments;
mod workflows_events;
mod workflows_executions;
mod workflows_metrics;
mod workflows_runs;
mod workflows_schedules;

pub use agents::Agents;
pub use audio::Audio;
pub use audio_speech::AudioSpeech;
pub use audio_transcriptions::AudioTranscriptions;
pub use audio_voices::AudioVoices;
pub use batch::Batch;
pub use batch_jobs::BatchJobs;
pub use beta::Beta;
pub use beta_admin::BetaAdmin;
pub use beta_admin_api_keys::BetaAdminApiKeys;
pub use beta_admin_audit_logs::BetaAdminAuditLogs;
pub use beta_admin_billing::BetaAdminBilling;
pub use beta_admin_scim::BetaAdminScim;
pub use beta_admin_user_groups::BetaAdminUserGroups;
pub use beta_admin_users::BetaAdminUsers;
pub use beta_admin_vibe_code_analytics::BetaAdminVibeCodeAnalytics;
pub use beta_admin_vibe_work_analytics::BetaAdminVibeWorkAnalytics;
pub use beta_admin_workspaces::BetaAdminWorkspaces;
pub use beta_agents::BetaAgents;
pub use beta_connectors::BetaConnectors;
pub use beta_conversations::BetaConversations;
pub use beta_libraries::BetaLibraries;
pub use beta_libraries_accesses::BetaLibrariesAccesses;
pub use beta_libraries_documents::BetaLibrariesDocuments;
pub use beta_observability::BetaObservability;
pub use beta_observability_campaigns::BetaObservabilityCampaigns;
pub use beta_observability_chat_completion_events::BetaObservabilityChatCompletionEvents;
pub use beta_observability_chat_completion_events_fields::BetaObservabilityChatCompletionEventsFields;
pub use beta_observability_datasets::BetaObservabilityDatasets;
pub use beta_observability_datasets_records::BetaObservabilityDatasetsRecords;
pub use beta_observability_judges::BetaObservabilityJudges;
pub use beta_observability_logs::BetaObservabilityLogs;
pub use beta_observability_spans::BetaObservabilitySpans;
pub use beta_observability_traces::BetaObservabilityTraces;
pub use beta_prompts::BetaPrompts;
pub use beta_rag::BetaRag;
pub use beta_rag_ingestion_pipeline_configurations::BetaRagIngestionPipelineConfigurations;
pub use beta_rag_search_indexes::BetaRagSearchIndexes;
pub use beta_skills::BetaSkills;
pub use beta_users::BetaUsers;
pub use chat::Chat;
pub use classifiers::Classifiers;
pub use embeddings::Embeddings;
pub use error::{ApiError, SdkError, TransportError, TransportErrorKind};
pub use events::Events;
pub use facade_types::{
    ActivateForConsumerBetaConnectorsResponse,
    AddOrUpdateUsersWorkspacesBetaAdminWorkspacesRequest,
    AddOrUpdateUsersWorkspacesBetaAdminWorkspacesResponse,
    AddUsersWorkspacesBetaAdminWorkspacesRequest, AddUsersWorkspacesBetaAdminWorkspacesResponse,
    AdminUserGroupsGetGroupWorkspaceAssignmentsBetaAdminUserGroupsResponse,
    AdminUserGroupsUpdateGroupWorkspaceAssignmentBetaAdminUserGroupsRequest,
    AdminUserGroupsUpdateUserGroupOrganizationRoleBetaAdminUserGroupsRequest,
    AggregateSpansBetaObservabilitySpansRequest, AggregateSpansBetaObservabilitySpansRequestMetric,
    AggregateSpansBetaObservabilitySpansRequestTimeDimension,
    AggregateSpansBetaObservabilitySpansResponse, AggregateTracesBetaObservabilityTracesRequest,
    AggregateTracesBetaObservabilityTracesRequestMetric,
    AggregateTracesBetaObservabilityTracesRequestTimeDimension,
    AggregateTracesBetaObservabilityTracesResponse,
    ApiAdminUserGroupsAssignGroupToWorkspaceBetaAdminUserGroupsRequest,
    ApiAdminUserGroupsAssignUsersToGroupBetaAdminUserGroupsRequest,
    ApiAdminUserGroupsCreateUserGroupBetaAdminUserGroupsRequest,
    ApiAdminUserGroupsCreateUserGroupBetaAdminUserGroupsResponse,
    ApiAdminUserGroupsGetNestedGroupsBetaAdminUserGroupsResponse,
    ApiAdminUserGroupsGetUserGroupBetaAdminUserGroupsResponse,
    ApiAdminUserGroupsGetUserGroupMembersBetaAdminUserGroupsResponse,
    ApiAdminUserGroupsGetUserGroupsBetaAdminUserGroupsResponse,
    ApiAdminUserGroupsProvisionGroupToWorkspaceBetaAdminUserGroupsRequest,
    ApiAdminUserGroupsRemoveUsersFromGroupBetaAdminUserGroupsRequest,
    ApiAdminUserGroupsSetNestedGroupsBetaAdminUserGroupsRequest,
    ApiAdminUserGroupsUpdateUserGroupBetaAdminUserGroupsRequest,
    ApiAdminUserGroupsUpdateUserGroupBetaAdminUserGroupsResponse, AppendBetaConversationsRequest,
    AppendBetaConversationsRequestCompletionArgs,
    AppendBetaConversationsRequestCompletionArgsPrediction,
    AppendBetaConversationsRequestCompletionArgsResponseFormat,
    AppendBetaConversationsRequestCompletionArgsResponseFormatJsonSchema,
    AppendBetaConversationsResponse, AppendStreamBetaConversationsRequest,
    AppendStreamBetaConversationsRequestCompletionArgs,
    AppendStreamBetaConversationsRequestCompletionArgsPrediction,
    AppendStreamBetaConversationsRequestCompletionArgsResponseFormat,
    AppendStreamBetaConversationsRequestCompletionArgsResponseFormatJsonSchema,
    AppendStreamBetaConversationsStream, AppendStreamBetaConversationsStreamItem,
    ArchiveModelsResponse, ArchiveWorkflowWorkflowsResponse,
    BatchCancelWorkflowExecutionsWorkflowsExecutionsRequest,
    BatchCancelWorkflowExecutionsWorkflowsExecutionsResponse,
    BatchTerminateWorkflowExecutionsWorkflowsExecutionsRequest,
    BatchTerminateWorkflowExecutionsWorkflowsExecutionsResponse, BinaryStream,
    BulkArchiveWorkflowsWorkflowsRequest, BulkArchiveWorkflowsWorkflowsResponse,
    BulkDeleteBetaObservabilityDatasetsRecordsRequest, BulkUnarchiveWorkflowsWorkflowsRequest,
    BulkUnarchiveWorkflowsWorkflowsResponse, CallToolBetaConnectorsRequest,
    CallToolBetaConnectorsResponse, CancelBatchJobsResponse, ClassifyChatClassifiersRequest,
    ClassifyChatClassifiersResponse, ClassifyClassifiersRequest, ClassifyClassifiersResponse,
    CompleteAgentsRequest, CompleteAgentsResponse, CompleteAudioSpeechRequest,
    CompleteAudioSpeechResponse, CompleteAudioTranscriptionsRequest,
    CompleteAudioTranscriptionsResponse, CompleteChatRequest, CompleteChatResponse,
    CompleteFimRequest, CompleteFimResponse, CreateApiKeyBetaAdminApiKeysRequest,
    CreateApiKeyBetaAdminApiKeysResponse, CreateAudioVoicesRequest, CreateAudioVoicesResponse,
    CreateBatchJobsRequest, CreateBatchJobsResponse, CreateBetaAgentsRequest,
    CreateBetaAgentsRequestCompletionArgs, CreateBetaAgentsRequestCompletionArgsPrediction,
    CreateBetaAgentsRequestCompletionArgsResponseFormat,
    CreateBetaAgentsRequestCompletionArgsResponseFormatJsonSchema, CreateBetaAgentsRequestTools,
    CreateBetaAgentsRequestToolsCodeInterpreterTool,
    CreateBetaAgentsRequestToolsCodeInterpreterToolToolConfiguration,
    CreateBetaAgentsRequestToolsCustomConnector,
    CreateBetaAgentsRequestToolsCustomConnectorAuthorization,
    CreateBetaAgentsRequestToolsCustomConnectorAuthorizationAPIKeyAuth,
    CreateBetaAgentsRequestToolsCustomConnectorAuthorizationOAuth2TokenAuth,
    CreateBetaAgentsRequestToolsCustomConnectorToolConfiguration,
    CreateBetaAgentsRequestToolsDocumentLibraryTool,
    CreateBetaAgentsRequestToolsDocumentLibraryToolToolConfiguration,
    CreateBetaAgentsRequestToolsFunctionTool, CreateBetaAgentsRequestToolsFunctionToolFunction,
    CreateBetaAgentsRequestToolsImageGenerationTool,
    CreateBetaAgentsRequestToolsImageGenerationToolToolConfiguration,
    CreateBetaAgentsRequestToolsWebSearchPremiumTool,
    CreateBetaAgentsRequestToolsWebSearchPremiumToolToolConfiguration,
    CreateBetaAgentsRequestToolsWebSearchTool,
    CreateBetaAgentsRequestToolsWebSearchToolToolConfiguration, CreateBetaAgentsResponse,
    CreateBetaConnectorsRequest, CreateBetaConnectorsRequestAuthData,
    CreateBetaConnectorsRequestOauth2ServerMetadata, CreateBetaConnectorsResponse,
    CreateBetaLibrariesRequest, CreateBetaLibrariesResponse,
    CreateBetaObservabilityDatasetsRequest, CreateBetaObservabilityDatasetsResponse,
    CreateBetaObservabilityJudgesRequest, CreateBetaObservabilityJudgesRequestOutput,
    CreateBetaObservabilityJudgesRequestOutputJudgeClassificationOutput,
    CreateBetaObservabilityJudgesRequestOutputJudgeRegressionOutput,
    CreateBetaObservabilityJudgesResponse, CreateBetaPromptsRequest, CreateBetaPromptsResponse,
    CreateBetaSkillsRequest, CreateBetaSkillsResponse,
    CreateCampaignBetaObservabilityCampaignsRequest,
    CreateCampaignBetaObservabilityCampaignsResponse, CreateDeploymentWorkflowsDeploymentsRequest,
    CreateDeploymentWorkflowsDeploymentsRequestResources,
    CreateDeploymentWorkflowsDeploymentsRequestSpec, CreateDeploymentWorkflowsDeploymentsResponse,
    CreateEmbeddingsRequest, CreateEmbeddingsResponse,
    CreateOrUpdateOrganizationCredentialsBetaConnectorsRequest,
    CreateOrUpdateOrganizationCredentialsBetaConnectorsRequestCredentials,
    CreateOrUpdateOrganizationCredentialsBetaConnectorsRequestCredentialsOauth,
    CreateOrUpdateOrganizationCredentialsBetaConnectorsResponse,
    CreateOrUpdateUserCredentialsBetaConnectorsRequest,
    CreateOrUpdateUserCredentialsBetaConnectorsRequestCredentials,
    CreateOrUpdateUserCredentialsBetaConnectorsRequestCredentialsOauth,
    CreateOrUpdateUserCredentialsBetaConnectorsResponse,
    CreateOrUpdateWorkspaceCredentialsBetaConnectorsRequest,
    CreateOrUpdateWorkspaceCredentialsBetaConnectorsRequestCredentials,
    CreateOrUpdateWorkspaceCredentialsBetaConnectorsRequestCredentialsOauth,
    CreateOrUpdateWorkspaceCredentialsBetaConnectorsResponse,
    CreateRecordBetaObservabilityDatasetsRequest, CreateRecordBetaObservabilityDatasetsResponse,
    CreateVersionAliasBetaAgentsResponse, CreateVersionBetaPromptsRequest,
    CreateVersionBetaPromptsResponse, CreateVersionBetaSkillsRequest,
    CreateVersionBetaSkillsResponse, CreateWorkspaceBetaAdminWorkspacesRequest,
    CreateWorkspaceBetaAdminWorkspacesResponse, DeactivateForConsumerBetaConnectorsResponse,
    DeleteAllUserCredentialsBetaConnectorsResponse, DeleteApiKeyBetaAdminApiKeysResponse,
    DeleteAudioVoicesResponse, DeleteBatchJobBatchJobsResponse, DeleteBetaConnectorsResponse,
    DeleteBetaLibrariesAccessesRequest, DeleteBetaLibrariesAccessesResponse,
    DeleteBetaLibrariesResponse, DeleteBetaPromptsResponse, DeleteBetaSkillsResponse,
    DeleteDeploymentWorkflowsDeploymentsResponse, DeleteFilesResponse, DeleteModelsResponse,
    DeleteOrganizationCredentialsBetaConnectorsResponse,
    DeleteUserCredentialsBetaConnectorsResponse, DeleteWorkspaceCredentialsBetaConnectorsResponse,
    ExecuteWorkflowRegistrationWorkflowsRequest, ExecuteWorkflowRegistrationWorkflowsResponse,
    ExecuteWorkflowRegistrationWorkflowsResponseWorkflowExecutionResponse,
    ExecuteWorkflowRegistrationWorkflowsResponseWorkflowExecutionSyncResponse,
    ExecuteWorkflowWorkflowsRequest, ExecuteWorkflowWorkflowsResponse,
    ExecuteWorkflowWorkflowsResponseWorkflowExecutionResponse,
    ExecuteWorkflowWorkflowsResponseWorkflowExecutionSyncResponse,
    ExportToJsonlBetaObservabilityDatasetsResponse,
    ExtractedTextSignedUrlBetaLibrariesDocumentsResponse,
    FetchBetaObservabilityDatasetsRecordsResponse, FetchBetaObservabilityDatasetsResponse,
    FetchBetaObservabilityJudgesResponse, FetchTaskBetaObservabilityDatasetsResponse,
    GetApiKeysBetaAdminApiKeysResponse, GetAudioVoicesResponse, GetAuthUrlBetaConnectorsResponse,
    GetAuthenticationMethodsBetaConnectorsResponse,
    GetAuthenticationMethodsBetaConnectorsResponseItem, GetBatchJobsResponse,
    GetBetaAgentsResponse, GetBetaConnectorsResponse, GetBetaConversationsResponse,
    GetBetaConversationsResponseAgentConversation, GetBetaConversationsResponseModelConversation,
    GetBetaLibrariesDocumentsResponse, GetBetaLibrariesResponse, GetBetaPromptsResponse,
    GetBetaSkillsResponse, GetByAgentStatsBetaAdminVibeWorkAnalyticsResponse,
    GetByTimeStatsBetaAdminVibeWorkAnalyticsResponse,
    GetByUserStatsBetaAdminVibeWorkAnalyticsResponse,
    GetCampaignByIdBetaObservabilityCampaignsResponse,
    GetCampaignSelectedEventsBetaObservabilityCampaignsResponse,
    GetCampaignStatusByIdBetaObservabilityCampaignsResponse,
    GetCampaignsBetaObservabilityCampaignsResponse,
    GetChatCompletionEventBetaObservabilityChatCompletionEventsResponse,
    GetChatCompletionEventIdsBetaObservabilityChatCompletionEventsRequest,
    GetChatCompletionEventIdsBetaObservabilityChatCompletionEventsResponse,
    GetChatCompletionEventsBetaObservabilityChatCompletionEventsRequest,
    GetChatCompletionEventsBetaObservabilityChatCompletionEventsResponse,
    GetChatCompletionFieldOptionsBetaObservabilityChatCompletionEventsFieldsResponse,
    GetChatCompletionFieldOptionsCountsBetaObservabilityChatCompletionEventsFieldsRequest,
    GetChatCompletionFieldOptionsCountsBetaObservabilityChatCompletionEventsFieldsResponse,
    GetChatCompletionFieldsBetaObservabilityChatCompletionEventsFieldsResponse,
    GetConfigsBetaRagIngestionPipelineConfigurationsResponse,
    GetConfigsBetaRagIngestionPipelineConfigurationsResponseItem,
    GetDeploymentLogsWorkflowsDeploymentsResponse,
    GetDeploymentSummariesBetaRagSearchIndexesResponse, GetDeploymentWorkflowsDeploymentsResponse,
    GetHistoryBetaConversationsResponse, GetIdentityBetaUsersResponse,
    GetLogFieldOptionsBetaObservabilityLogsResponse, GetLogFieldsBetaObservabilityLogsResponse,
    GetMessagesBetaConversationsResponse, GetOrganizationStatsBetaAdminVibeCodeAnalyticsResponse,
    GetRunHistoryWorkflowsRunsResponse, GetRunWorkflowsRunsResponse,
    GetScheduleWorkflowsSchedulesResponse, GetSchedulesWorkflowsSchedulesResponse,
    GetScimSyncRunBetaAdminScimResponse, GetSignedUrlBetaLibrariesDocumentsResponse,
    GetSignedUrlFilesResponse,
    GetSimilarChatCompletionEventsBetaObservabilityChatCompletionEventsResponse,
    GetSpanByIdBetaObservabilityTracesResponse,
    GetSpanEvaluationFieldOptionsBetaObservabilitySpansResponse,
    GetSpanEvaluationFieldsBetaObservabilitySpansResponse,
    GetSpanFieldOptionsBetaObservabilitySpansResponse, GetSpanFieldsBetaObservabilitySpansResponse,
    GetStreamEventsEventsStream, GetStreamEventsEventsStreamItem,
    GetStreamEventsEventsStreamItemStreamEventSseErrorData,
    GetStreamEventsEventsStreamItemStreamEventSsePayload, GetStreamEventsWorkflowsEventsStream,
    GetStreamEventsWorkflowsEventsStreamItem,
    GetStreamEventsWorkflowsEventsStreamItemStreamEventSseErrorData,
    GetStreamEventsWorkflowsEventsStreamItemStreamEventSsePayload,
    GetTraceByIdBetaObservabilityTracesResponse,
    GetTraceFieldOptionsBetaObservabilityTracesResponse,
    GetTraceFieldsBetaObservabilityTracesResponse, GetTraceSpansBetaObservabilityTracesResponse,
    GetVersionBetaAgentsResponse, GetVersionBetaPromptsResponse, GetVersionBetaSkillsResponse,
    GetWorkflowEventsEventsResponse, GetWorkflowEventsWorkflowsEventsResponse,
    GetWorkflowExecutionHistoryWorkflowsExecutionsResponse,
    GetWorkflowExecutionLogsWorkflowsExecutionsResponse,
    GetWorkflowExecutionTraceEventsWorkflowsExecutionsResponse,
    GetWorkflowExecutionTraceInfoWorkflowsExecutionsResponse,
    GetWorkflowExecutionTraceOtelWorkflowsExecutionsResponse,
    GetWorkflowExecutionTraceSummaryWorkflowsExecutionsResponse,
    GetWorkflowExecutionWorkflowsExecutionsResponse, GetWorkflowMetricsWorkflowsMetricsResponse,
    GetWorkflowRegistrationWorkflowsResponse, GetWorkflowRegistrationsWorkflowsResponse,
    GetWorkflowWorkflowsResponse, GetWorkflowsWorkflowsResponse,
    GetWorkspaceStatsBetaAdminVibeCodeAnalyticsResponse, GetWorkspacesBetaAdminWorkspacesResponse,
    ImportFromDatasetRecordsBetaObservabilityDatasetsRequest,
    ImportFromDatasetRecordsBetaObservabilityDatasetsResponse,
    ImportFromFileBetaObservabilityDatasetsRequest,
    ImportFromFileBetaObservabilityDatasetsResponse,
    ImportFromPlaygroundBetaObservabilityDatasetsRequest,
    ImportFromPlaygroundBetaObservabilityDatasetsResponse,
    JudgeBetaObservabilityDatasetsRecordsRequest,
    JudgeBetaObservabilityDatasetsRecordsRequestJudgeDefinition,
    JudgeBetaObservabilityDatasetsRecordsRequestJudgeDefinitionOutput,
    JudgeBetaObservabilityDatasetsRecordsRequestJudgeDefinitionOutputJudgeClassificationOutput,
    JudgeBetaObservabilityDatasetsRecordsRequestJudgeDefinitionOutputJudgeRegressionOutput,
    JudgeBetaObservabilityDatasetsRecordsResponse,
    JudgeChatCompletionEventBetaObservabilityChatCompletionEventsRequest,
    JudgeChatCompletionEventBetaObservabilityChatCompletionEventsRequestJudgeDefinition,
    JudgeChatCompletionEventBetaObservabilityChatCompletionEventsRequestJudgeDefinitionOutput,
    JudgeChatCompletionEventBetaObservabilityChatCompletionEventsRequestJudgeDefinitionOutputJudgeClassificationOutput,
    JudgeChatCompletionEventBetaObservabilityChatCompletionEventsRequestJudgeDefinitionOutputJudgeRegressionOutput,
    JudgeChatCompletionEventBetaObservabilityChatCompletionEventsResponse,
    JudgeConversationBetaObservabilityJudgesRequest,
    JudgeConversationBetaObservabilityJudgesResponse,
    LibrariesDocumentsUpdateV1BetaLibrariesDocumentsRequest,
    LibrariesDocumentsUpdateV1BetaLibrariesDocumentsResponse,
    LibrariesUpdateV1BetaLibrariesRequest, LibrariesUpdateV1BetaLibrariesResponse,
    ListAudioVoicesResponse, ListBatchJobsResponseView, ListBetaAgentsResponse,
    ListBetaAgentsResponseItem, ListBetaConnectorsResponse, ListBetaConversationsResponse,
    ListBetaLibrariesAccessesResponse, ListBetaLibrariesDocumentsResponse,
    ListBetaLibrariesResponse, ListBetaObservabilityDatasetsResponse,
    ListBetaObservabilityJudgesResponse, ListBetaPromptsResponse, ListBetaSkillsResponse,
    ListDeploymentWorkersWorkflowsDeploymentsResponse, ListDeploymentsWorkflowsDeploymentsResponse,
    ListFilesResponseView, ListModelsResponse, ListOrganizationCredentialsBetaConnectorsResponse,
    ListOrganizationsBetaUsersResponse, ListPagesBetaAgentsResponse,
    ListRecordsBetaObservabilityDatasetsResponse, ListRunsWorkflowsRunsResponse,
    ListTasksBetaObservabilityDatasetsResponse, ListToolsBetaConnectorsResponse,
    ListUserCredentialsBetaConnectorsResponse, ListVersionAliasesBetaAgentsResponse,
    ListVersionAliasesBetaAgentsResponseItem, ListVersionsBetaAgentsResponse,
    ListVersionsBetaAgentsResponseItem, ListVersionsBetaPromptsResponse,
    ListVersionsBetaSkillsResponse, ListWorkspaceCredentialsBetaConnectorsResponse,
    ListWorkspacesBetaUsersResponse, ModerateChatClassifiersRequest,
    ModerateChatClassifiersResponse, ModerateClassifiersRequest, ModerateClassifiersResponse,
    ParseChatRequest, ParseChatResponse, ParseStreamChatRequest, ParseStreamChatStream,
    ParseStreamChatStreamItem, PatchBetaLibrariesDocumentsRequest,
    PatchBetaLibrariesDocumentsResponse, PatchBetaLibrariesRequest, PatchBetaLibrariesResponse,
    PauseScheduleWorkflowsSchedulesRequest,
    PostDatasetRecordsFromCampaignBetaObservabilityDatasetsRequest,
    PostDatasetRecordsFromCampaignBetaObservabilityDatasetsResponse,
    PostDatasetRecordsFromExplorerBetaObservabilityDatasetsRequest,
    PostDatasetRecordsFromExplorerBetaObservabilityDatasetsResponse, ProcessOcrRequest,
    ProcessOcrResponse, QueryWorkflowExecutionWorkflowsExecutionsRequest,
    QueryWorkflowExecutionWorkflowsExecutionsResponse,
    RateLimitsGetRateLimitsBetaAdminBillingResponse,
    RegisterConfigBetaRagIngestionPipelineConfigurationsRequest,
    RegisterConfigBetaRagIngestionPipelineConfigurationsResponse,
    RegisterDeploymentBetaRagSearchIndexesRequest, RegisterDeploymentBetaRagSearchIndexesResponse,
    RemoveUsersWorkspacesBetaAdminWorkspacesRequest,
    RemoveUsersWorkspacesBetaAdminWorkspacesResponse, ResetWorkflowWorkflowsExecutionsRequest,
    RestartBetaConversationsRequest, RestartBetaConversationsRequestCompletionArgs,
    RestartBetaConversationsRequestCompletionArgsPrediction,
    RestartBetaConversationsRequestCompletionArgsResponseFormat,
    RestartBetaConversationsRequestCompletionArgsResponseFormatJsonSchema,
    RestartBetaConversationsResponse, RestartDeploymentWorkflowsDeploymentsResponse,
    RestartStreamBetaConversationsRequest, RestartStreamBetaConversationsRequestCompletionArgs,
    RestartStreamBetaConversationsRequestCompletionArgsPrediction,
    RestartStreamBetaConversationsRequestCompletionArgsResponseFormat,
    RestartStreamBetaConversationsRequestCompletionArgsResponseFormatJsonSchema,
    RestartStreamBetaConversationsStream, RestartStreamBetaConversationsStreamItem,
    ResumeScheduleWorkflowsSchedulesRequest, RetrieveFilesResponse, RetrieveModelsResponse,
    RetrieveModelsResponseBaseModelCard, RetrieveModelsResponseFTModelCard,
    RolesGetRolesBetaAdminUsersResponse, ScheduleWorkflowWorkflowsSchedulesRequest,
    ScheduleWorkflowWorkflowsSchedulesRequestSchedule,
    ScheduleWorkflowWorkflowsSchedulesRequestSchedulePolicy,
    ScheduleWorkflowWorkflowsSchedulesResponse,
    SearchLatestSpanEvaluationsBetaObservabilitySpansRequest,
    SearchLatestSpanEvaluationsBetaObservabilitySpansResponse,
    SearchLogsBetaObservabilityLogsRequest, SearchLogsBetaObservabilityLogsResponse,
    SearchSpanEvaluationsBetaObservabilitySpansRequest,
    SearchSpanEvaluationsBetaObservabilitySpansResponse, SearchSpansBetaObservabilitySpansRequest,
    SearchSpansBetaObservabilitySpansResponse, SearchTracesBetaObservabilityTracesRequest,
    SearchTracesBetaObservabilityTracesResponse, ShareBetaConnectorsResponse,
    SignalWorkflowExecutionWorkflowsExecutionsRequest,
    SignalWorkflowExecutionWorkflowsExecutionsResponse,
    SpendLimitsGetSpendLimitsBetaAdminBillingResponse,
    SpendLimitsUpdateSpendLimitsBetaAdminBillingRequest,
    SpendLimitsUpdateSpendLimitsBetaAdminBillingResponse, StartBetaConversationsRequest,
    StartBetaConversationsRequestCompletionArgs,
    StartBetaConversationsRequestCompletionArgsPrediction,
    StartBetaConversationsRequestCompletionArgsResponseFormat,
    StartBetaConversationsRequestCompletionArgsResponseFormatJsonSchema,
    StartBetaConversationsRequestTools, StartBetaConversationsRequestToolsCodeInterpreterTool,
    StartBetaConversationsRequestToolsCodeInterpreterToolToolConfiguration,
    StartBetaConversationsRequestToolsCustomConnector,
    StartBetaConversationsRequestToolsCustomConnectorAuthorization,
    StartBetaConversationsRequestToolsCustomConnectorAuthorizationAPIKeyAuth,
    StartBetaConversationsRequestToolsCustomConnectorAuthorizationOAuth2TokenAuth,
    StartBetaConversationsRequestToolsCustomConnectorToolConfiguration,
    StartBetaConversationsRequestToolsDocumentLibraryTool,
    StartBetaConversationsRequestToolsDocumentLibraryToolToolConfiguration,
    StartBetaConversationsRequestToolsFunctionTool,
    StartBetaConversationsRequestToolsFunctionToolFunction,
    StartBetaConversationsRequestToolsImageGenerationTool,
    StartBetaConversationsRequestToolsImageGenerationToolToolConfiguration,
    StartBetaConversationsRequestToolsWebSearchPremiumTool,
    StartBetaConversationsRequestToolsWebSearchPremiumToolToolConfiguration,
    StartBetaConversationsRequestToolsWebSearchTool,
    StartBetaConversationsRequestToolsWebSearchToolToolConfiguration,
    StartBetaConversationsResponse, StartDeploymentWorkflowsDeploymentsResponse,
    StartStreamBetaConversationsRequest, StartStreamBetaConversationsRequestCompletionArgs,
    StartStreamBetaConversationsRequestCompletionArgsPrediction,
    StartStreamBetaConversationsRequestCompletionArgsResponseFormat,
    StartStreamBetaConversationsRequestCompletionArgsResponseFormatJsonSchema,
    StartStreamBetaConversationsRequestTools,
    StartStreamBetaConversationsRequestToolsCodeInterpreterTool,
    StartStreamBetaConversationsRequestToolsCodeInterpreterToolToolConfiguration,
    StartStreamBetaConversationsRequestToolsCustomConnector,
    StartStreamBetaConversationsRequestToolsCustomConnectorAuthorization,
    StartStreamBetaConversationsRequestToolsCustomConnectorAuthorizationAPIKeyAuth,
    StartStreamBetaConversationsRequestToolsCustomConnectorAuthorizationOAuth2TokenAuth,
    StartStreamBetaConversationsRequestToolsCustomConnectorToolConfiguration,
    StartStreamBetaConversationsRequestToolsDocumentLibraryTool,
    StartStreamBetaConversationsRequestToolsDocumentLibraryToolToolConfiguration,
    StartStreamBetaConversationsRequestToolsFunctionTool,
    StartStreamBetaConversationsRequestToolsFunctionToolFunction,
    StartStreamBetaConversationsRequestToolsImageGenerationTool,
    StartStreamBetaConversationsRequestToolsImageGenerationToolToolConfiguration,
    StartStreamBetaConversationsRequestToolsWebSearchPremiumTool,
    StartStreamBetaConversationsRequestToolsWebSearchPremiumToolToolConfiguration,
    StartStreamBetaConversationsRequestToolsWebSearchTool,
    StartStreamBetaConversationsRequestToolsWebSearchToolToolConfiguration,
    StartStreamBetaConversationsStream, StartStreamBetaConversationsStreamItem,
    StatusBetaLibrariesDocumentsResponse, StopDeploymentWorkflowsDeploymentsResponse,
    StreamAgentsRequest, StreamAgentsResponse, StreamAudioTranscriptionsRequest,
    StreamAudioTranscriptionsStream, StreamAudioTranscriptionsStreamItem, StreamChatRequest,
    StreamChatStream, StreamChatStreamItem, StreamDeploymentLogsWorkflowsDeploymentsStream,
    StreamDeploymentLogsWorkflowsDeploymentsStreamItem,
    StreamDeploymentLogsWorkflowsDeploymentsStreamItemDeploymentLogRecord,
    StreamDeploymentLogsWorkflowsDeploymentsStreamItemStreamError, StreamFimRequest,
    StreamFimStream, StreamFimStreamItem, StreamWorkflowExecutionLogsWorkflowsExecutionsStream,
    StreamWorkflowExecutionLogsWorkflowsExecutionsStreamItem,
    StreamWorkflowExecutionLogsWorkflowsExecutionsStreamItemExecutionLogRecord,
    StreamWorkflowExecutionLogsWorkflowsExecutionsStreamItemStreamError,
    StreamWorkflowsExecutionsStream, StreamWorkflowsExecutionsStreamItem,
    StreamWorkflowsExecutionsStreamItemStreamEventSseErrorData,
    StreamWorkflowsExecutionsStreamItemStreamEventSsePayload,
    TextContentBetaLibrariesDocumentsResponse, TriggerScheduleWorkflowsSchedulesRequest,
    TriggerScimSyncBetaAdminScimRequest, TriggerScimSyncBetaAdminScimRequestSyncConfig,
    TriggerScimSyncBetaAdminScimResponse, UnarchiveModelsResponse,
    UnarchiveWorkflowWorkflowsResponse, UnregisterDeploymentBetaRagSearchIndexesResponse,
    UnshareBetaConnectorsResponse, UpdateAudioVoicesRequest, UpdateAudioVoicesResponse,
    UpdateBetaAgentsRequest, UpdateBetaAgentsRequestCompletionArgs,
    UpdateBetaAgentsRequestCompletionArgsPrediction,
    UpdateBetaAgentsRequestCompletionArgsResponseFormat,
    UpdateBetaAgentsRequestCompletionArgsResponseFormatJsonSchema, UpdateBetaAgentsRequestTools,
    UpdateBetaAgentsRequestToolsCodeInterpreterTool,
    UpdateBetaAgentsRequestToolsCodeInterpreterToolToolConfiguration,
    UpdateBetaAgentsRequestToolsCustomConnector,
    UpdateBetaAgentsRequestToolsCustomConnectorAuthorization,
    UpdateBetaAgentsRequestToolsCustomConnectorAuthorizationAPIKeyAuth,
    UpdateBetaAgentsRequestToolsCustomConnectorAuthorizationOAuth2TokenAuth,
    UpdateBetaAgentsRequestToolsCustomConnectorToolConfiguration,
    UpdateBetaAgentsRequestToolsDocumentLibraryTool,
    UpdateBetaAgentsRequestToolsDocumentLibraryToolToolConfiguration,
    UpdateBetaAgentsRequestToolsFunctionTool, UpdateBetaAgentsRequestToolsFunctionToolFunction,
    UpdateBetaAgentsRequestToolsImageGenerationTool,
    UpdateBetaAgentsRequestToolsImageGenerationToolToolConfiguration,
    UpdateBetaAgentsRequestToolsWebSearchPremiumTool,
    UpdateBetaAgentsRequestToolsWebSearchPremiumToolToolConfiguration,
    UpdateBetaAgentsRequestToolsWebSearchTool,
    UpdateBetaAgentsRequestToolsWebSearchToolToolConfiguration, UpdateBetaAgentsResponse,
    UpdateBetaConnectorsRequest, UpdateBetaConnectorsResponse,
    UpdateBetaObservabilityDatasetsRequest, UpdateBetaObservabilityDatasetsResponse,
    UpdateBetaObservabilityJudgesRequest, UpdateBetaObservabilityJudgesRequestOutput,
    UpdateBetaObservabilityJudgesRequestOutputJudgeClassificationOutput,
    UpdateBetaObservabilityJudgesRequestOutputJudgeRegressionOutput, UpdateBetaPromptsRequest,
    UpdateBetaPromptsResponse, UpdateBetaSkillsRequest, UpdateBetaSkillsResponse,
    UpdateDeploymentWorkflowsDeploymentsRequest,
    UpdateDeploymentWorkflowsDeploymentsRequestResources,
    UpdateDeploymentWorkflowsDeploymentsRequestSpec, UpdateDeploymentWorkflowsDeploymentsResponse,
    UpdateIndexMetricsBetaRagSearchIndexesRequest, UpdateIndexMetricsBetaRagSearchIndexesResponse,
    UpdateModelsRequest, UpdateModelsResponse, UpdateModelsResponseClassifierFineTunedModel,
    UpdateModelsResponseCompletionFineTunedModel, UpdateOrCreateBetaLibrariesAccessesRequest,
    UpdateOrCreateBetaLibrariesAccessesResponse,
    UpdatePayloadBetaObservabilityDatasetsRecordsRequest,
    UpdatePropertiesBetaObservabilityDatasetsRecordsRequest,
    UpdateRunInfoBetaRagIngestionPipelineConfigurationsRequest,
    UpdateRunInfoBetaRagIngestionPipelineConfigurationsResponse,
    UpdateScheduleWorkflowsSchedulesRequest, UpdateScheduleWorkflowsSchedulesRequestSchedule,
    UpdateScheduleWorkflowsSchedulesRequestSchedulePolicy,
    UpdateScheduleWorkflowsSchedulesResponse, UpdateVersionBetaAgentsResponse,
    UpdateVersionMetadataBetaPromptsRequest, UpdateVersionMetadataBetaPromptsResponse,
    UpdateVersionMetadataBetaSkillsRequest, UpdateVersionMetadataBetaSkillsResponse,
    UpdateWorkflowExecutionWorkflowsExecutionsRequest,
    UpdateWorkflowExecutionWorkflowsExecutionsResponse, UpdateWorkflowWorkflowsRequest,
    UpdateWorkflowWorkflowsResponse, UpdateWorkspacesBetaAdminWorkspacesRequest,
    UpdateWorkspacesBetaAdminWorkspacesResponse, UploadBetaLibrariesDocumentsRequest,
    UploadBetaLibrariesDocumentsResponse, UploadFilesRequest, UploadFilesResponse,
    UsageGetUsageBetaAdminBillingResponse,
    UsersApiAdminAuditLogsGetAuditLogsBetaAdminAuditLogsResponse,
    UsersApiAdminAuditLogsGetAuditLogsBetaAdminAuditLogsResponseItem,
    UsersCreateUsersBetaAdminUsersRequest, UsersCreateUsersBetaAdminUsersResponse,
    UsersDeleteInviteBetaAdminUsersResponse, UsersDeleteUserBetaAdminUsersResponse,
    UsersGetInviteBetaAdminUsersResponse, UsersGetInviteBetaAdminUsersResponseItem,
    UsersGetUserBetaAdminUsersResponse, UsersGetUsersBetaAdminUsersResponse,
    UsersInviteUsersBetaAdminUsersRequest, UsersInviteUsersBetaAdminUsersResponse,
    UsersUpdateUserBetaAdminUsersRequest, UsersUpdateUserBetaAdminUsersResponse,
};
pub use files::Files;
pub use fim::Fim;
pub use models::Models;
pub use ocr::Ocr;
pub use workflows::Workflows;
pub use workflows_deployments::WorkflowsDeployments;
pub use workflows_events::WorkflowsEvents;
pub use workflows_executions::WorkflowsExecutions;
pub use workflows_metrics::WorkflowsMetrics;
pub use workflows_runs::WorkflowsRuns;
pub use workflows_schedules::WorkflowsSchedules;

use crate::generated::client::HttpClient;

#[derive(Clone)]
pub struct Mistral {
    raw: HttpClient,
}

impl Mistral {
    pub fn new(api_key: impl Into<String>) -> Self {
        Self {
            raw: HttpClient::new().with_api_key(api_key),
        }
    }
    #[must_use]
    pub fn with_base_url(mut self, base_url: impl Into<String>) -> Self {
        self.raw = self.raw.with_base_url(base_url);
        self
    }
    pub fn agents(&self) -> Agents<'_> {
        Agents::new(&self.raw)
    }
    pub fn audio(&self) -> Audio<'_> {
        Audio::new(&self.raw)
    }
    pub fn batch(&self) -> Batch<'_> {
        Batch::new(&self.raw)
    }
    pub fn beta(&self) -> Beta<'_> {
        Beta::new(&self.raw)
    }
    pub fn chat(&self) -> Chat<'_> {
        Chat::new(&self.raw)
    }
    pub fn classifiers(&self) -> Classifiers<'_> {
        Classifiers::new(&self.raw)
    }
    pub fn embeddings(&self) -> Embeddings<'_> {
        Embeddings::new(&self.raw)
    }
    pub fn events(&self) -> Events<'_> {
        Events::new(&self.raw)
    }
    pub fn files(&self) -> Files<'_> {
        Files::new(&self.raw)
    }
    pub fn fim(&self) -> Fim<'_> {
        Fim::new(&self.raw)
    }
    pub fn models(&self) -> Models<'_> {
        Models::new(&self.raw)
    }
    pub fn ocr(&self) -> Ocr<'_> {
        Ocr::new(&self.raw)
    }
    pub fn workflows(&self) -> Workflows<'_> {
        Workflows::new(&self.raw)
    }
    pub fn raw(&self) -> &HttpClient {
        &self.raw
    }
}
