// @generated by codegen/sdk_facade.py; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;
#[derive(Clone, Copy)]
pub struct Models<'a> {
    raw: &'a HttpClient,
}

impl<'a> Models<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }

    pub async fn list(&self) -> Result<ModelListResponse, SdkError> {
        self.raw
            .list_models_v1_models_get(None::<&str>, None::<&str>)
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn list_with(
        &self,
        provider: Option<&str>,
        model: Option<&str>,
    ) -> Result<ModelListResponse, SdkError> {
        self.raw
            .list_models_v1_models_get(provider, model)
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
