// @generated by tooling/pipeline/compile_sdk.py; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;
#[derive(Debug, Clone)]
pub struct GetWorkflowMetricsWorkflowsMetricsRequest {
    workflow_name: String,
    start_time: Option<String>,
    end_time: Option<String>,
}
impl GetWorkflowMetricsWorkflowsMetricsRequest {
    pub fn new(workflow_name: impl Into<String>) -> Self {
        Self {
            workflow_name: workflow_name.into(),
            start_time: None,
            end_time: None,
        }
    }
    #[must_use]
    pub fn start_time(mut self, start_time: impl Into<String>) -> Self {
        self.start_time = Some(start_time.into());
        self
    }
    #[must_use]
    pub fn end_time(mut self, end_time: impl Into<String>) -> Self {
        self.end_time = Some(end_time.into());
        self
    }
}
#[derive(Clone, Copy)]
pub struct WorkflowsMetrics<'a> {
    raw: &'a HttpClient,
}

impl<'a> WorkflowsMetrics<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn get_workflow_metrics(
        &self,
        request: GetWorkflowMetricsWorkflowsMetricsRequest,
    ) -> Result<WorkflowMetricsView, SdkError> {
        self.raw
            .get_workflow_metrics_v1_workflows_workflow_name_metrics_get(
                request.workflow_name.as_str(),
                request.start_time.as_deref(),
                request.end_time.as_deref(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
