// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;

#[derive(Debug, Clone, Default)]
pub struct ListDeploymentsWorkflowsDeploymentsRequest {
    active_only: Option<bool>,
    workflow_name: Option<String>,
}
impl ListDeploymentsWorkflowsDeploymentsRequest {
    pub fn new() -> Self {
        Self {
            active_only: None,
            workflow_name: None,
        }
    }
    #[must_use]
    pub fn active_only(mut self, active_only: bool) -> Self {
        self.active_only = Some(active_only);
        self
    }
    #[must_use]
    pub fn workflow_name(mut self, workflow_name: impl Into<String>) -> Self {
        self.workflow_name = Some(workflow_name.into());
        self
    }
}
#[derive(Clone, Copy)]
pub struct WorkflowsDeployments<'a> {
    raw: &'a HttpClient,
}

impl<'a> WorkflowsDeployments<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn get_deployment(
        &self,
        name: impl AsRef<str>,
    ) -> Result<DeploymentDetailResponseView, SdkError> {
        self.raw
            .get_deployment_v1_workflows_deployments_name_get(name.as_ref())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn list_deployments(&self) -> Result<DeploymentListResponseView, SdkError> {
        self.raw
            .list_deployments_v1_workflows_deployments_get(None, None::<&str>)
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn list_deployments_with(
        &self,
        request: ListDeploymentsWorkflowsDeploymentsRequest,
    ) -> Result<DeploymentListResponseView, SdkError> {
        self.raw
            .list_deployments_v1_workflows_deployments_get(
                request.active_only,
                request.workflow_name.as_deref(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
