// @generated by codegen/sdk_facade.py; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;
#[derive(Clone, Copy)]
pub struct WorkflowsWorkers<'a> {
    raw: &'a HttpClient,
}

impl<'a> WorkflowsWorkers<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn get_worker_info(&self) -> Result<WorkerInfoView, SdkError> {
        self.raw
            .get_worker_info_v1_workflows_workers_whoami_get()
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
