// @generated by tooling/pipeline/compile_sdk.py; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;

#[derive(Debug, Clone, Default)]
pub struct ListRunsWorkflowsRunsRequest {
    workflow_identifier: Option<String>,
    search: Option<String>,
    status: Option<String>,
    page_size: Option<i64>,
    next_page_token: Option<String>,
}
impl ListRunsWorkflowsRunsRequest {
    pub fn new() -> Self {
        Self {
            workflow_identifier: None,
            search: None,
            status: None,
            page_size: None,
            next_page_token: None,
        }
    }
    #[must_use]
    pub fn workflow_identifier(mut self, workflow_identifier: impl Into<String>) -> Self {
        self.workflow_identifier = Some(workflow_identifier.into());
        self
    }
    #[must_use]
    pub fn search(mut self, search: impl Into<String>) -> Self {
        self.search = Some(search.into());
        self
    }
    #[must_use]
    pub fn status(mut self, status: impl Into<String>) -> Self {
        self.status = Some(status.into());
        self
    }
    #[must_use]
    pub fn page_size(mut self, page_size: i64) -> Self {
        self.page_size = Some(page_size);
        self
    }
    #[must_use]
    pub fn next_page_token(mut self, next_page_token: impl Into<String>) -> Self {
        self.next_page_token = Some(next_page_token.into());
        self
    }
}
#[derive(Clone, Copy)]
pub struct WorkflowsRuns<'a> {
    raw: &'a HttpClient,
}

impl<'a> WorkflowsRuns<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn get_run(
        &self,
        run_id: impl AsRef<str>,
    ) -> Result<WorkflowExecutionResponseView, SdkError> {
        self.raw
            .get_run_v1_workflows_runs_run_id_get(run_id.as_ref())
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn list_runs(&self) -> Result<WorkflowExecutionListResponseView, SdkError> {
        self.raw
            .list_runs_v1_workflows_runs_get(
                None::<&str>,
                None::<&str>,
                None::<&str>,
                None,
                None::<&str>,
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }

    pub async fn list_runs_with(
        &self,
        request: ListRunsWorkflowsRunsRequest,
    ) -> Result<WorkflowExecutionListResponseView, SdkError> {
        self.raw
            .list_runs_v1_workflows_runs_get(
                request.workflow_identifier.as_deref(),
                request.search.as_deref(),
                request.status.as_deref(),
                request.page_size,
                request.next_page_token.as_deref(),
            )
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
