// @generated by rust-sdk-generator via sdk-build; do not edit by hand.
use futures_util::StreamExt;
use crate::generated::types::*;
use super::*;
use crate::generated::client::HttpClient;
#[derive(Debug, serde::Deserialize)]
#[serde(untagged)]
enum __StreamDeploymentLogsWorkflowsDeploymentsStreamItemRaw {
    DeploymentLogRecord(DeploymentLogRecord),
    StreamError(StreamError)
}



#[derive(Debug, Clone)]
pub struct GetDeploymentWorkflowsDeploymentsRequest { name: String, workflow_name: Option<String> }
impl GetDeploymentWorkflowsDeploymentsRequest { pub fn new(name: impl Into<String>) -> Self { Self { name: name.into(), workflow_name: None } }
#[must_use] pub fn workflow_name(mut self, workflow_name: impl Into<String>) -> Self { self.workflow_name = Some(workflow_name.into()); self }
}

#[derive(Debug, Clone)]
pub struct GetDeploymentLogsWorkflowsDeploymentsRequest { name: String, worker_name: Option<String>, workflow_name: Option<String>, after: Option<String>, before: Option<String>, order: Option<crate::generated::client::GetDeploymentLogsOrder>, cursor: Option<String>, limit: Option<i64> }
impl GetDeploymentLogsWorkflowsDeploymentsRequest { pub fn new(name: impl Into<String>) -> Self { Self { name: name.into(), worker_name: None, workflow_name: None, after: None, before: None, order: None, cursor: None, limit: None } }
#[must_use] pub fn worker_name(mut self, worker_name: impl Into<String>) -> Self { self.worker_name = Some(worker_name.into()); self }
#[must_use] pub fn workflow_name(mut self, workflow_name: impl Into<String>) -> Self { self.workflow_name = Some(workflow_name.into()); self }
#[must_use] pub fn after(mut self, after: impl Into<String>) -> Self { self.after = Some(after.into()); self }
#[must_use] pub fn before(mut self, before: impl Into<String>) -> Self { self.before = Some(before.into()); self }
#[must_use] pub fn order(mut self, order: crate::generated::client::GetDeploymentLogsOrder) -> Self { self.order = Some(order); self }
#[must_use] pub fn cursor(mut self, cursor: impl Into<String>) -> Self { self.cursor = Some(cursor.into()); self }
#[must_use] pub fn limit(mut self, limit: i64) -> Self { self.limit = Some(limit); self }
}

#[derive(Debug, Clone)]
pub struct ListDeploymentWorkersWorkflowsDeploymentsRequest { name: String, worker_status: Option<String>, limit: Option<i64>, cursor: Option<String> }
impl ListDeploymentWorkersWorkflowsDeploymentsRequest { pub fn new(name: impl Into<String>) -> Self { Self { name: name.into(), worker_status: None, limit: None, cursor: None } }
#[must_use] pub fn worker_status(mut self, worker_status: impl Into<String>) -> Self { self.worker_status = Some(worker_status.into()); self }
#[must_use] pub fn limit(mut self, limit: i64) -> Self { self.limit = Some(limit); self }
#[must_use] pub fn cursor(mut self, cursor: impl Into<String>) -> Self { self.cursor = Some(cursor.into()); self }
}

#[derive(Debug, Clone, Default)]
pub struct ListDeploymentsWorkflowsDeploymentsRequest { active_only: Option<bool>, is_hardened: Option<String>, workflow_name: Option<String>, search: Option<String>, order_by: Option<String>, order: Option<crate::generated::client::ListDeploymentsV1WorkflowsDeploymentsGetOrder>, limit: Option<String>, cursor: Option<String>, workspace_id: Option<String> }
impl ListDeploymentsWorkflowsDeploymentsRequest { pub fn new() -> Self { Self { active_only: None, is_hardened: None, workflow_name: None, search: None, order_by: None, order: None, limit: None, cursor: None, workspace_id: None } }
#[must_use] pub fn active_only(mut self, active_only: bool) -> Self { self.active_only = Some(active_only); self }
#[must_use] pub fn is_hardened(mut self, is_hardened: impl Into<String>) -> Self { self.is_hardened = Some(is_hardened.into()); self }
#[must_use] pub fn workflow_name(mut self, workflow_name: impl Into<String>) -> Self { self.workflow_name = Some(workflow_name.into()); self }
#[must_use] pub fn search(mut self, search: impl Into<String>) -> Self { self.search = Some(search.into()); self }
#[must_use] pub fn order_by(mut self, order_by: impl Into<String>) -> Self { self.order_by = Some(order_by.into()); self }
#[must_use] pub fn order(mut self, order: crate::generated::client::ListDeploymentsV1WorkflowsDeploymentsGetOrder) -> Self { self.order = Some(order); self }
#[must_use] pub fn limit(mut self, limit: impl Into<String>) -> Self { self.limit = Some(limit.into()); self }
#[must_use] pub fn cursor(mut self, cursor: impl Into<String>) -> Self { self.cursor = Some(cursor.into()); self }
#[must_use] pub fn workspace_id(mut self, workspace_id: impl Into<String>) -> Self { self.workspace_id = Some(workspace_id.into()); self }
}




#[derive(Debug, Clone)]
pub struct StreamDeploymentLogsWorkflowsDeploymentsRequest { name: String, worker_name: Option<String>, workflow_name: Option<String>, after: Option<String>, last_event_id: Option<String>, last_event_id_2: Option<String> }
impl StreamDeploymentLogsWorkflowsDeploymentsRequest { pub fn new(name: impl Into<String>) -> Self { Self { name: name.into(), worker_name: None, workflow_name: None, after: None, last_event_id: None, last_event_id_2: None } }
#[must_use] pub fn worker_name(mut self, worker_name: impl Into<String>) -> Self { self.worker_name = Some(worker_name.into()); self }
#[must_use] pub fn workflow_name(mut self, workflow_name: impl Into<String>) -> Self { self.workflow_name = Some(workflow_name.into()); self }
#[must_use] pub fn after(mut self, after: impl Into<String>) -> Self { self.after = Some(after.into()); self }
#[must_use] pub fn last_event_id(mut self, last_event_id: impl Into<String>) -> Self { self.last_event_id = Some(last_event_id.into()); self }
#[must_use] pub fn last_event_id_2(mut self, last_event_id_2: impl Into<String>) -> Self { self.last_event_id_2 = Some(last_event_id_2.into()); self }
}

#[derive(Clone, Copy)]
pub struct WorkflowsDeployments<'a> { raw: &'a HttpClient }

impl<'a> WorkflowsDeployments<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self { Self { raw } }
    pub async fn create_deployment(&self, request: CreateDeploymentWorkflowsDeploymentsRequest) -> Result<CreateDeploymentWorkflowsDeploymentsResponse, SdkError> {
        self.raw.create_deployment_v1_workflows_deployments_post(request.into_raw()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn delete_deployment(&self, name: impl AsRef<str>) -> Result<DeleteDeploymentWorkflowsDeploymentsResponse, SdkError> {
        self.raw.delete_deployment_v1_workflows_deployments_name_delete(name.as_ref()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn get_deployment(&self, request: GetDeploymentWorkflowsDeploymentsRequest) -> Result<GetDeploymentWorkflowsDeploymentsResponse, SdkError> {
        self.raw.get_deployment_v1_workflows_deployments_name_get(request.name.as_str(), request.workflow_name.as_deref()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn get_deployment_logs(&self, request: GetDeploymentLogsWorkflowsDeploymentsRequest) -> Result<GetDeploymentLogsWorkflowsDeploymentsResponse, SdkError> {
        self.raw.get_deployment_logs(request.name.as_str(), request.worker_name.as_deref(), request.workflow_name.as_deref(), request.after.as_deref(), request.before.as_deref(), request.order, request.cursor.as_deref(), request.limit).await.map(Into::into).map_err(Into::into)
    }

    pub async fn list_deployment_workers(&self, request: ListDeploymentWorkersWorkflowsDeploymentsRequest) -> Result<ListDeploymentWorkersWorkflowsDeploymentsResponse, SdkError> {
        self.raw.list_deployment_workers_v1_workflows_deployments_name_workers_get(request.name.as_str(), request.worker_status.as_deref(), request.limit, request.cursor.as_deref()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn list_deployments(&self) -> Result<ListDeploymentsWorkflowsDeploymentsResponse, SdkError> {
        self.raw.list_deployments_v1_workflows_deployments_get(None, None::<&str>, None::<&str>, None::<&str>, None::<&str>, None, None::<&str>, None::<&str>, None::<&str>).await.map(Into::into).map_err(Into::into)
    }

    pub async fn list_deployments_with(&self, request: ListDeploymentsWorkflowsDeploymentsRequest) -> Result<ListDeploymentsWorkflowsDeploymentsResponse, SdkError> {
        self.raw.list_deployments_v1_workflows_deployments_get(request.active_only, request.is_hardened.as_deref(), request.workflow_name.as_deref(), request.search.as_deref(), request.order_by.as_deref(), request.order, request.limit.as_deref(), request.cursor.as_deref(), request.workspace_id.as_deref()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn restart_deployment(&self, name: impl AsRef<str>) -> Result<RestartDeploymentWorkflowsDeploymentsResponse, SdkError> {
        self.raw.restart_deployment_v1_workflows_deployments_name_restart_post(name.as_ref()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn start_deployment(&self, name: impl AsRef<str>) -> Result<StartDeploymentWorkflowsDeploymentsResponse, SdkError> {
        self.raw.start_deployment_v1_workflows_deployments_name_start_post(name.as_ref()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn stop_deployment(&self, name: impl AsRef<str>) -> Result<StopDeploymentWorkflowsDeploymentsResponse, SdkError> {
        self.raw.stop_deployment_v1_workflows_deployments_name_stop_post(name.as_ref()).await.map(Into::into).map_err(Into::into)
    }

    pub async fn stream_deployment_logs(&self, request: StreamDeploymentLogsWorkflowsDeploymentsRequest) -> Result<StreamDeploymentLogsWorkflowsDeploymentsStream, SdkError> {
        let bytes = self.raw.stream_deployment_logs(request.name.as_str(), request.worker_name.as_deref(), request.workflow_name.as_deref(), request.after.as_deref(), request.last_event_id.as_deref(), request.last_event_id_2.as_deref()).await.map_err(SdkError::from)?;
        let events = crate::streaming::json_events::<_, _, __StreamDeploymentLogsWorkflowsDeploymentsStreamItemRaw>(bytes)
            .map(|event| event.map(|event| match event.data { __StreamDeploymentLogsWorkflowsDeploymentsStreamItemRaw::DeploymentLogRecord(value) => StreamDeploymentLogsWorkflowsDeploymentsStreamItem::DeploymentLogRecord(StreamDeploymentLogsWorkflowsDeploymentsStreamItemDeploymentLogRecord::from(value)),__StreamDeploymentLogsWorkflowsDeploymentsStreamItemRaw::StreamError(value) => StreamDeploymentLogsWorkflowsDeploymentsStreamItem::StreamError(StreamDeploymentLogsWorkflowsDeploymentsStreamItemStreamError::from(value)) }).map_err(Into::into));
        Ok(Box::pin(events))
    }

    pub async fn update_deployment(&self, name: impl AsRef<str>, request: UpdateDeploymentWorkflowsDeploymentsRequest) -> Result<UpdateDeploymentWorkflowsDeploymentsResponse, SdkError> {
        self.raw.update_deployment_v1_workflows_deployments_name_patch(name.as_ref(), request.into_raw()).await.map(Into::into).map_err(Into::into)
    }
}
