// @generated by codegen/sdk_facade.py; do not edit by hand.
use super::*;
use crate::generated::client::HttpClient;
#[derive(Clone, Copy)]
pub struct WorkflowsSchedules<'a> {
    raw: &'a HttpClient,
}

impl<'a> WorkflowsSchedules<'a> {
    pub(crate) fn new(raw: &'a HttpClient) -> Self {
        Self { raw }
    }
    pub async fn get_schedules(&self) -> Result<WorkflowScheduleListResponseView, SdkError> {
        self.raw
            .get_schedules_v1_workflows_schedules_get()
            .await
            .map(Into::into)
            .map_err(Into::into)
    }
}
