pub use crate::prelude::*;

#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum TargetType {
    User,
    UserGroup,
    Organization,
    Workspace,
    ApiKey,
    AdminApiKey,
    ApiKeyPolicy,
    ServiceAccount,
    Agent,
    Skill,
    Prompt,
    KnowledgeBase,
    CustomVoice,
    Dataset,
    FineTuningJob,
    BatchJob,
    DataCaptureExtractJob,
    LeChatConversation,
    LeChatMemories,
    LeChatFlashAnswers,
    LeChatLocalisation,
    LeChatData,
    Invoice,
    Wallet,
    MonthlyLimit,
    WorkspaceMonthlyLimit,
    SharedBudget,
    AutoRecharge,
    PaymentMethod,
    Subscription,
    BillingInfo,
    Library,
    LibraryDocument,
    Integration,
    ConnectorsGateway,
    ConnectorsDebugger,
    FeaturePermission,
    SecretStoreEntry,
    CrawlerConfig,
    SharedResource,
    RateLimitRule,
    App,
    Deployment,
    Domain,
    PersistentVolume,
    Secret,
    Service,
    TrustedIssuer,
    /// This variant is used for forward compatibility.
    /// If the server sends a value not recognized by the current SDK version,
    /// it will be captured here with the raw string value.
    __Unknown(String),
}
impl Serialize for TargetType {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::User => serializer.serialize_str("USER"),
            Self::UserGroup => serializer.serialize_str("USER_GROUP"),
            Self::Organization => serializer.serialize_str("ORGANIZATION"),
            Self::Workspace => serializer.serialize_str("WORKSPACE"),
            Self::ApiKey => serializer.serialize_str("API_KEY"),
            Self::AdminApiKey => serializer.serialize_str("ADMIN_API_KEY"),
            Self::ApiKeyPolicy => serializer.serialize_str("API_KEY_POLICY"),
            Self::ServiceAccount => serializer.serialize_str("SERVICE_ACCOUNT"),
            Self::Agent => serializer.serialize_str("AGENT"),
            Self::Skill => serializer.serialize_str("SKILL"),
            Self::Prompt => serializer.serialize_str("PROMPT"),
            Self::KnowledgeBase => serializer.serialize_str("KNOWLEDGE_BASE"),
            Self::CustomVoice => serializer.serialize_str("CUSTOM_VOICE"),
            Self::Dataset => serializer.serialize_str("DATASET"),
            Self::FineTuningJob => serializer.serialize_str("FINE_TUNING_JOB"),
            Self::BatchJob => serializer.serialize_str("BATCH_JOB"),
            Self::DataCaptureExtractJob => serializer.serialize_str("DATA_CAPTURE_EXTRACT_JOB"),
            Self::LeChatConversation => serializer.serialize_str("LE_CHAT_CONVERSATION"),
            Self::LeChatMemories => serializer.serialize_str("LE_CHAT_MEMORIES"),
            Self::LeChatFlashAnswers => serializer.serialize_str("LE_CHAT_FLASH_ANSWERS"),
            Self::LeChatLocalisation => serializer.serialize_str("LE_CHAT_LOCALISATION"),
            Self::LeChatData => serializer.serialize_str("LE_CHAT_DATA"),
            Self::Invoice => serializer.serialize_str("INVOICE"),
            Self::Wallet => serializer.serialize_str("WALLET"),
            Self::MonthlyLimit => serializer.serialize_str("MONTHLY_LIMIT"),
            Self::WorkspaceMonthlyLimit => serializer.serialize_str("WORKSPACE_MONTHLY_LIMIT"),
            Self::SharedBudget => serializer.serialize_str("SHARED_BUDGET"),
            Self::AutoRecharge => serializer.serialize_str("AUTO_RECHARGE"),
            Self::PaymentMethod => serializer.serialize_str("PAYMENT_METHOD"),
            Self::Subscription => serializer.serialize_str("SUBSCRIPTION"),
            Self::BillingInfo => serializer.serialize_str("BILLING_INFO"),
            Self::Library => serializer.serialize_str("LIBRARY"),
            Self::LibraryDocument => serializer.serialize_str("LIBRARY_DOCUMENT"),
            Self::Integration => serializer.serialize_str("INTEGRATION"),
            Self::ConnectorsGateway => serializer.serialize_str("CONNECTORS_GATEWAY"),
            Self::ConnectorsDebugger => serializer.serialize_str("CONNECTORS_DEBUGGER"),
            Self::FeaturePermission => serializer.serialize_str("FEATURE_PERMISSION"),
            Self::SecretStoreEntry => serializer.serialize_str("SECRET_STORE_ENTRY"),
            Self::CrawlerConfig => serializer.serialize_str("CRAWLER_CONFIG"),
            Self::SharedResource => serializer.serialize_str("SHARED_RESOURCE"),
            Self::RateLimitRule => serializer.serialize_str("RATE_LIMIT_RULE"),
            Self::App => serializer.serialize_str("APP"),
            Self::Deployment => serializer.serialize_str("DEPLOYMENT"),
            Self::Domain => serializer.serialize_str("DOMAIN"),
            Self::PersistentVolume => serializer.serialize_str("PERSISTENT_VOLUME"),
            Self::Secret => serializer.serialize_str("SECRET"),
            Self::Service => serializer.serialize_str("SERVICE"),
            Self::TrustedIssuer => serializer.serialize_str("TRUSTED_ISSUER"),
            Self::__Unknown(val) => serializer.serialize_str(val),
        }
    }
}

impl<'de> Deserialize<'de> for TargetType {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "USER" => Ok(Self::User),
            "USER_GROUP" => Ok(Self::UserGroup),
            "ORGANIZATION" => Ok(Self::Organization),
            "WORKSPACE" => Ok(Self::Workspace),
            "API_KEY" => Ok(Self::ApiKey),
            "ADMIN_API_KEY" => Ok(Self::AdminApiKey),
            "API_KEY_POLICY" => Ok(Self::ApiKeyPolicy),
            "SERVICE_ACCOUNT" => Ok(Self::ServiceAccount),
            "AGENT" => Ok(Self::Agent),
            "SKILL" => Ok(Self::Skill),
            "PROMPT" => Ok(Self::Prompt),
            "KNOWLEDGE_BASE" => Ok(Self::KnowledgeBase),
            "CUSTOM_VOICE" => Ok(Self::CustomVoice),
            "DATASET" => Ok(Self::Dataset),
            "FINE_TUNING_JOB" => Ok(Self::FineTuningJob),
            "BATCH_JOB" => Ok(Self::BatchJob),
            "DATA_CAPTURE_EXTRACT_JOB" => Ok(Self::DataCaptureExtractJob),
            "LE_CHAT_CONVERSATION" => Ok(Self::LeChatConversation),
            "LE_CHAT_MEMORIES" => Ok(Self::LeChatMemories),
            "LE_CHAT_FLASH_ANSWERS" => Ok(Self::LeChatFlashAnswers),
            "LE_CHAT_LOCALISATION" => Ok(Self::LeChatLocalisation),
            "LE_CHAT_DATA" => Ok(Self::LeChatData),
            "INVOICE" => Ok(Self::Invoice),
            "WALLET" => Ok(Self::Wallet),
            "MONTHLY_LIMIT" => Ok(Self::MonthlyLimit),
            "WORKSPACE_MONTHLY_LIMIT" => Ok(Self::WorkspaceMonthlyLimit),
            "SHARED_BUDGET" => Ok(Self::SharedBudget),
            "AUTO_RECHARGE" => Ok(Self::AutoRecharge),
            "PAYMENT_METHOD" => Ok(Self::PaymentMethod),
            "SUBSCRIPTION" => Ok(Self::Subscription),
            "BILLING_INFO" => Ok(Self::BillingInfo),
            "LIBRARY" => Ok(Self::Library),
            "LIBRARY_DOCUMENT" => Ok(Self::LibraryDocument),
            "INTEGRATION" => Ok(Self::Integration),
            "CONNECTORS_GATEWAY" => Ok(Self::ConnectorsGateway),
            "CONNECTORS_DEBUGGER" => Ok(Self::ConnectorsDebugger),
            "FEATURE_PERMISSION" => Ok(Self::FeaturePermission),
            "SECRET_STORE_ENTRY" => Ok(Self::SecretStoreEntry),
            "CRAWLER_CONFIG" => Ok(Self::CrawlerConfig),
            "SHARED_RESOURCE" => Ok(Self::SharedResource),
            "RATE_LIMIT_RULE" => Ok(Self::RateLimitRule),
            "APP" => Ok(Self::App),
            "DEPLOYMENT" => Ok(Self::Deployment),
            "DOMAIN" => Ok(Self::Domain),
            "PERSISTENT_VOLUME" => Ok(Self::PersistentVolume),
            "SECRET" => Ok(Self::Secret),
            "SERVICE" => Ok(Self::Service),
            "TRUSTED_ISSUER" => Ok(Self::TrustedIssuer),
            _ => Ok(Self::__Unknown(value)),
        }
    }
}

impl fmt::Display for TargetType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::User => write!(f, "USER"),
            Self::UserGroup => write!(f, "USER_GROUP"),
            Self::Organization => write!(f, "ORGANIZATION"),
            Self::Workspace => write!(f, "WORKSPACE"),
            Self::ApiKey => write!(f, "API_KEY"),
            Self::AdminApiKey => write!(f, "ADMIN_API_KEY"),
            Self::ApiKeyPolicy => write!(f, "API_KEY_POLICY"),
            Self::ServiceAccount => write!(f, "SERVICE_ACCOUNT"),
            Self::Agent => write!(f, "AGENT"),
            Self::Skill => write!(f, "SKILL"),
            Self::Prompt => write!(f, "PROMPT"),
            Self::KnowledgeBase => write!(f, "KNOWLEDGE_BASE"),
            Self::CustomVoice => write!(f, "CUSTOM_VOICE"),
            Self::Dataset => write!(f, "DATASET"),
            Self::FineTuningJob => write!(f, "FINE_TUNING_JOB"),
            Self::BatchJob => write!(f, "BATCH_JOB"),
            Self::DataCaptureExtractJob => write!(f, "DATA_CAPTURE_EXTRACT_JOB"),
            Self::LeChatConversation => write!(f, "LE_CHAT_CONVERSATION"),
            Self::LeChatMemories => write!(f, "LE_CHAT_MEMORIES"),
            Self::LeChatFlashAnswers => write!(f, "LE_CHAT_FLASH_ANSWERS"),
            Self::LeChatLocalisation => write!(f, "LE_CHAT_LOCALISATION"),
            Self::LeChatData => write!(f, "LE_CHAT_DATA"),
            Self::Invoice => write!(f, "INVOICE"),
            Self::Wallet => write!(f, "WALLET"),
            Self::MonthlyLimit => write!(f, "MONTHLY_LIMIT"),
            Self::WorkspaceMonthlyLimit => write!(f, "WORKSPACE_MONTHLY_LIMIT"),
            Self::SharedBudget => write!(f, "SHARED_BUDGET"),
            Self::AutoRecharge => write!(f, "AUTO_RECHARGE"),
            Self::PaymentMethod => write!(f, "PAYMENT_METHOD"),
            Self::Subscription => write!(f, "SUBSCRIPTION"),
            Self::BillingInfo => write!(f, "BILLING_INFO"),
            Self::Library => write!(f, "LIBRARY"),
            Self::LibraryDocument => write!(f, "LIBRARY_DOCUMENT"),
            Self::Integration => write!(f, "INTEGRATION"),
            Self::ConnectorsGateway => write!(f, "CONNECTORS_GATEWAY"),
            Self::ConnectorsDebugger => write!(f, "CONNECTORS_DEBUGGER"),
            Self::FeaturePermission => write!(f, "FEATURE_PERMISSION"),
            Self::SecretStoreEntry => write!(f, "SECRET_STORE_ENTRY"),
            Self::CrawlerConfig => write!(f, "CRAWLER_CONFIG"),
            Self::SharedResource => write!(f, "SHARED_RESOURCE"),
            Self::RateLimitRule => write!(f, "RATE_LIMIT_RULE"),
            Self::App => write!(f, "APP"),
            Self::Deployment => write!(f, "DEPLOYMENT"),
            Self::Domain => write!(f, "DOMAIN"),
            Self::PersistentVolume => write!(f, "PERSISTENT_VOLUME"),
            Self::Secret => write!(f, "SECRET"),
            Self::Service => write!(f, "SERVICE"),
            Self::TrustedIssuer => write!(f, "TRUSTED_ISSUER"),
            Self::__Unknown(val) => write!(f, "{}", val),
        }
    }
}
